lballabio/QuantLib

- ql/math/matrix.hpp
Migrated from https://github.com/lballabio/quantlib-old/pull/358 by @pcaspers
> Add boost-style element access and size

- test-suite/optionletstripper.cpp
- test-suite/optionletstripper.hpp
So ... here is the missing test case for the switch strike calculation (I hope, this nicely fits into the existing PR #16. Not to sure, if I got everything right with the new repo.).
> Recompute switchstrike for caplets #328

- ql/time/calendar.cpp
- ql/time/calendar.hpp
otherwise a lonely message like "boost assertion failed px!=0" may be thrown with no further hint
> add check for non-empty calendar implementation

- ql/termstructures/volatility/swaption/swaptionvolcube2.cpp
- ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp
- ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp
this is useful not only within the inheritance chain, but also for
client code
> expose option date calculation

- ql/currencies/europe.cpp
- ql/currencies/europe.hpp
- ql/time/calendars/ukraine.cpp
Added support for Ukrainian hryvnia.
```c++
class UAHCurrency : public Currency {
public:
UAHCurrency();
};
UAHCurrency::UAHCurrency() {
static boost::shared_ptr<Data> uahData(
new Data("Ukrainian hryvnia", "UAH", 980,
"hrn", "", 100,
Rounding(),
"%1$.2f %3%"));
data_ = uahData;
}
```
Also, Defender's Day (14 October) added to the list of non-business days according to the recent changes in legislation.
```c++
// Defender's Day
|| (d == 14 && m == October))
```
> Ukraine data

- ql/instruments/nonstandardswap.cpp
- ql/instruments/nonstandardswap.hpp
This extends the instrument a bit --- actually it handled the gearings and spreads as vectors internally already, only the constructors did no expose this flexibility (for whatever reason).
> Non-constant gearings / spreads in NonstandardSwap

- ql/experimental/math/moorepenroseinverse.hpp
- ql/math/matrix.hpp
- test-suite/matrices.cpp
- test-suite/matrices.hpp
This adds a SVD-based calculation of the Moore-Penrose inverse matrix. It is tested against an example given in the MatLab documentation.
> Moore-Penrose Inverse

- ql/math/matrixutilities/choleskydecomposition.cpp
- test-suite/matrices.cpp
- test-suite/matrices.hpp
For a semi definite matrix with Eigenvalues
```eigenvalues=[ 0.0287076; 0.0121878; 0.00704268; 0.00179693; 0.00030437; 5.60751e-05; 2.74717e-05; 6.6124e-07; 7.58951e-20; 1.10105e-20; 5.35378e-21 ]```
I got ```inf``` - entries in the result, where ```0``` is expected. This PR fixes that problem.
> Fix for numerical "0/0" in Cholesky Decomposition

- ql/indexes/ibor/audlibor.hpp
- ql/indexes/ibor/cadlibor.hpp
- ql/indexes/ibor/chflibor.hpp
- ql/indexes/ibor/dkklibor.hpp
- ql/indexes/ibor/eurlibor.hpp
- ql/indexes/ibor/gbplibor.hpp
- ql/indexes/ibor/jpylibor.hpp
- ql/indexes/ibor/libor.hpp
- ql/indexes/ibor/nzdlibor.hpp
- ql/indexes/ibor/seklibor.hpp
- ql/indexes/ibor/trlibor.hpp
- ql/indexes/ibor/usdlibor.hpp
Fixes for transfer from BBA LIBOR to ICE LIBOR and discontinuation of NZD, SEK, DKK, AUD and CAD LIBOR as of 2013.
Fixes #66.
> Updated LIBOR docs.

- ql/cashflows/capflooredcoupon.cpp
- ql/cashflows/couponpricer.cpp
I am constructing a leg containing some CappedFlooredCoupons based on an InterestRateIndex (on that general level). Then a subsequent call to setCouponPricer on that leg won't visit those coupons. This adds the visit methods required in that situation.
> Fix Pricer Setter

- ql/methods/montecarlo/longstaffschwartzpathpricer.hpp
this has both a better memory footprint and a better performance, see http://quantlib.10058.n7.nabble.com/incremental-statistics-td16828.html
> replace general by incremental statistics

- ql/pricingengines/mclongstaffschwartzengine.hpp
- ql/pricingengines/vanilla/mcamericanengine.hpp
@klausspanderen, this is the change we discussed, may you have a look at what I came up with ?
This fixes the current behavior of reusing the paths for calibration in pricing (except zero seed (and PseudoRandom) is used), which implies a high biased MC estimator. One can also use different RNG traits for calibration (e.g. PseudoRandom) and pricing (e.g. LowDiscrepancy) now. The interface is kept backward compatible.
I think there are three engines deriving from ```MCLongstaffSchwartzEngine```. I amended ```MCAmericanEngine``` such that it fully uses the extended interface. If you like this extension, I can do the same with ```MCAmericanBasketEngine```. The third engine is the experimental ```MCAmericanPathEngine```. This one bascially copies the code of ```MCLongstaffSchwartzEngine``` …
> Disentangle RNGs for calibration and pricing in LS engine

- ql/pricingengines/swaption/blackswaptionengine.cpp
- ql/pricingengines/swaption/blackswaptionengine.hpp
The displacement should be read from a given swaption volatility structure whenever possible and not be hardcoded in the engine constructor. Any chance we get this into 1.8, since there is a major "volatility" upgrade introduced with it anyway?
> Read displacement from volatility structure if possible

- man/BasketLosses.1
- man/CVAIRS.1
- man/Gaussian1dModels.1
- man/LatentModel.1
- man/MultidimIntegral.1
Usual motivation: as we'll have a binary in the Debian package, we ought to have a manual page for the binary.
> new (stub) CVAIRS manual page

- ql/instruments/capfloor.cpp
- ql/instruments/capfloor.hpp
- ql/instruments/swaption.cpp
this is a solution in order to have normal implied volatility for cap/floor. 
Maybe a better solution is to add the pricing engine directly in impliedVolatility(..), @pcaspers what do you think?
> added normal implied volatility calculation

- ql/cashflows/cashflows.cpp
- ql/cashflows/cashflows.hpp
- ql/cashflows/coupon.cpp
- ql/cashflows/coupon.hpp
- ql/experimental/credit/randomdefaultlatentmodel.hpp
- ql/pricingengines/bond/bondfunctions.cpp
- ql/pricingengines/bond/bondfunctions.hpp
- ql/termstructures/volatility/swaption/gaussian1dswaptionvolatility.cpp
- ql/termstructures/volatility/swaption/gaussian1dswaptionvolatility.hpp
- ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp
- ql/termstructures/yield/discountcurve.hpp
- ql/time/calendar.cpp
- ql/time/calendar.hpp
- ql/time/date.cpp
- ql/time/date.hpp
- ql/time/daycounter.hpp
- ql/time/daycounters/actual365nl.hpp
- ql/time/daycounters/business252.cpp
- ql/time/daycounters/business252.hpp
- ql/time/daycounters/one.hpp
- ql/time/daycounters/simpledaycounter.cpp
- ql/time/daycounters/simpledaycounter.hpp
- ql/time/daycounters/thirty360.cpp
- ql/time/daycounters/thirty360.hpp
- ql/time/ecb.cpp
- ql/time/schedule.cpp
- test-suite/calendars.cpp
- test-suite/cashflows.cpp
- test-suite/dates.cpp
- test-suite/timeseries.cpp
I am not 100% sure about this one, but on my system ```QuantLib::Date```'s serial number is stored using 64bit (```BigInteger``` aka ```long```), although 32bit would be enough to cover ```Date::minSerialNumber()``` to ```Date::maxSerialNumber()```. Maybe long is from the time when ```int``` was still 16bit? The type ```int_fast32_t``` is available at least since boost 1.46, the doc says
> The typedef int_fast#_t, with # replaced by the width, designates the fastest signed integer type with a width of at least # bits. Similarly, the typedef name uint_fast#_t designates the fastest unsigned integer type with a width of at least # bits.
On my system, ```int_fast32_t``` is 32bit. We could probably use an unsigned type as well, but this could produce warnings in client code like the ones on …
> change date's serial number type to fast32

- ql/pricingengines/barrier/binomialbarrierengine.hpp
Boyle-Lau optimization for single barriers options and binomial trees is meant to be used only with CRR trees.  
Previously the caller had to explicitly disable the optimization, this patch does it automatically
> Auto-deactivate Boyle-Lau optimization if not using a CRR tree

- ql/time/date.cpp
sometimes iso dates come out as ```2015-70-60``` instead of ```2015-07-06```, I believe when in ```out``` something like ```std::left```was set --- this ensures that the zeros are placed on the left side of the month and day digits
> ensure correct format during output of date

- .gitignore
Visual Studio 14 seems to create this "new" local database to the project folder, most probably it should be ignored from commits.
> Adding *VC.db to .gitIgnore

- ql/time/calendars/southafrica.cpp
Hi, another one shot holiday for election day Wednesday 3 Aug 2016. Thanks, Jasen
> South Africa calendar updated for election day holiday 3 Aug

- ql/math/optimization/constraint.hpp
minor thing, but if you for example combine NoConstraint() with BoundaryConstraint() and the lower bound in the latter is negative, the lower bound of the composite will be (close to) zero
> fix default implementation of lower bound

- test-suite/paralleltestrunner.hpp
A code change in the boost 1.62 unit test framework requires a fix in the parallel unit test runner.
> parallel unit test runner: fixed boost 1.62 issue

- ql/experimental/termstructures/multicurvesensitivities.hpp
prevents a linking error seen in RQuantLib
> add missing 'inline' attribute to free functions

- ql/instruments/makecapfloor.cpp
See the comment in the code, for some currencies the construction of a cap floor surface with an optionlet stripper fails because MakeVanillaSwap can not deduce a tenor for the fixed leg. This is not even needed though in MakeCapFloor, so we can just set it to some value.
> avoid exception if default tenor is unknown

- ql/pricingengines/vanilla/analyticeuropeanengine.cpp
- ql/pricingengines/vanilla/analyticeuropeanengine.hpp
- test-suite/europeanoption.cpp
- test-suite/europeanoption.hpp
As suggested in my email to quantlib-users on 7th December 2016, I propose updating AnalyticEuropeanEngine so that it can support separate rate curves for discounting and estimation of the forward price. My mail to quantlib-users provides a more detailed description.
The update involves enhancing the constructor for AnalyticEuropeanEngine, so that it includes an optional second argument for the discount curve. If this is left empty/null then the engine reverts to its previous behaviour (i.e. same rate curve used for discounting and estimation of forward price).
> AnalyticEuropeanEngine to support multi-curve pricing

- ql/cashflows/lineartsrpricer.cpp
- ql/cashflows/lineartsrpricer.hpp
- ql/math/interpolations/lagrangeinterpolation.hpp
I got error C2864: 'QuantLib::LinearTsrPricer::defaultLowerBound' : only static const integral data members can be initialized within a class. This fix the compilation
> Fixed compilation error introduced with commit 224a0e6.

- ql/termstructures/inflation/seasonality.cpp
If seasonalityFactors_ is an empty vector it still passes the
validate() checks. Later in isConsistent() the call to
seasonalityFactor() will calculate x % nFactors with nFactors = 0
which will produce a fp exception 8 signal.
> avoid signal fp exception 8

- ql/cashflows/cashflows.cpp
- ql/cashflows/cashflows.hpp
- ql/pricingengines/bond/bondfunctions.cpp
- ql/pricingengines/bond/bondfunctions.hpp
This PR adds a template parameter to CashFlows and BondFunctions to allow them to take an arbitrary solver, instead of the default NewtonSafe solver (such as the Brent solver). These changes are backwards compatible due to the change involving a function template overload.
I am willing to make any requested further changes and can squash them if requested.
> Allow arbitrary bond yield solver

- ql/time/dategenerationrule.cpp
- ql/time/dategenerationrule.hpp
- ql/time/schedule.cpp
- test-suite/schedule.cpp
- test-suite/schedule.hpp
> Add CDS2015, a new DateGeneration rule

- ql/cashflows/fixedratecoupon.cpp
- test-suite/cashflows.cpp
- test-suite/cashflows.hpp
See #210 for an overview of the problem this PR addresses.
This is a simple fix for the one case that I need working right now, but I also noticed the same potential issue in a few other places:
```
cashflowvectors.hpp
cpicoupon.cpp
rangeaccrual.cpp
yoyinflationcoupon.cpp
```
I know very little about what these files handle, so I limited the scope of this PR to the code I do understand and have tested.
Speaking of testing, I couldn't find any tests for FixedRateCoupon, so I didn't add any tests to cover this issue. Any guidance on that front would be appreciated.
> Fix leg creation not respecting endOfMonth flag

- ql/indexes/inflationindex.cpp
Use the lagged period for calculating the number of days over which to interpolate.
> Fix inflation index reference period

- .travis.yml
- Examples/BasketLosses/BasketLosses.cpp
- Examples/BermudanSwaption/BermudanSwaption.cpp
- Examples/Bonds/Bonds.cpp
- Examples/CDS/CDS.cpp
- Examples/CVAIRS/CVAIRS.cpp
- Examples/CallableBonds/CallableBonds.cpp
- Examples/ConvertibleBonds/ConvertibleBonds.cpp
- Examples/DiscreteHedging/DiscreteHedging.cpp
- Examples/EquityOption/EquityOption.cpp
- Examples/FRA/FRA.cpp
- Examples/FittedBondCurve/FittedBondCurve.cpp
- Examples/Gaussian1dModels/Gaussian1dModels.cpp
- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- Examples/LatentModel/LatentModel.cpp
- Examples/MultidimIntegral/MultidimIntegral.cpp
- Examples/Replication/Replication.cpp
- Examples/Repo/Repo.cpp
- Examples/Swap/swapvaluation.cpp
Instead of including the global `ql/quantlib.hpp` header, examples only include what they need.
This decreases the compilation time of each example by an amount going from 60% to 80%.
> Speed up compilation of examples

- ql/termstructures/volatility/optionlet/optionletstripper1.cpp
- ql/termstructures/volatility/optionlet/optionletstripper1.hpp
I suggest to remove the CapFloorMatrix class member variable of OptionletStripper1 and use a local variable within OptionletStripper1::performCalculations instead in order to save memory. These matrices tends to get rather large when using several different optionlet surfaces in parallel in order to price different currencies and option tenors. Apparently there hasn't been any use case for the initialized matrix and the corresponding bool in the last ten years, and the matrix currently would be recreated anyway whenever performCalculations is called in the current implementation.
> OptionletStripper1: Local CapFloorMatrix

- ql/time/calendars/iceland.cpp
- ql/time/calendars/iceland.hpp
> Iceland calendar doesn't adjust New Year's Day to Monday.

- ql/indexes/ibor/cadlibor.hpp
- ql/indexes/ibor/cdor.hpp
Regarding to the OpenGamma "Interest Rate Instruments and Market Conventions Guide" as well as market data provider Bloomberg and IKON (Reuters) the convantion should be Act365 F and spot lag should be 0 instead of Act360 and 2 used so far in cdor.hpp and cadlibor.hpp
Best Regards
> Amendment of day count convention and spot lag by CAD fixings

- ql/math/optimization/constraint.hpp
- ql/math/optimization/problem.hpp
I used an instance of Constraint (instead of NoConstraint) for an optimisation and got a px != 0 runtime error. These are brutal to locate sometimes ...
> provide better error message than px != 0

- .travis.yml
The image is stored on the Docker Hub; the current one contains an installation of the latest Boost version in the latest long-term Ubuntu release.
The approach should be easily extended to multiple jobs, each in a different image; in turn, this would allow to use different Boost releases (to check compatibility with older ones) or different Ubuntu releases (to try out older or newer gcc versions).
> Perform Travis build in Docker image

- ql/experimental/finitedifferences/fdmhestonfwdop.cpp
- ql/experimental/finitedifferences/hestonrndcalculator.cpp
- ql/methods/finitedifferences/operators/fdmhestonhullwhiteop.cpp
- ql/methods/finitedifferences/solvers/fdm1dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm2dblackscholessolver.cpp
- ql/methods/finitedifferences/solvers/fdm2dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm3dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdmbackwardsolver.cpp
- ql/methods/finitedifferences/solvers/fdmblackscholessolver.cpp
- ql/methods/finitedifferences/solvers/fdmhestonhullwhitesolver.cpp
- ql/methods/finitedifferences/solvers/fdmhestonsolver.cpp
- ql/methods/finitedifferences/solvers/fdmhullwhitesolver.cpp
- ql/methods/finitedifferences/solvers/fdmsimple2dbssolver.cpp
- ql/pricingengines/barrier/fdblackscholesbarrierengine.cpp
- ql/pricingengines/barrier/fdhestonbarrierengine.cpp
- test-suite/hestonmodel.cpp
- test-suite/hestonslvmodel.cpp
boost suggests to use make_shared for the construction of shared_ptr for efficiency reasons. This is done in this pull request for some code I have been involved in.
> move some boost::shared_ptr construction to boost::make_shared

- ql/experimental/commodities/commoditycurve.hpp
- ql/experimental/volatility/abcdatmvolcurve.hpp
- ql/termstructure.hpp
- ql/termstructures/volatility/capfloor/capfloortermvolcurve.hpp
- ql/termstructures/volatility/capfloor/capfloortermvolsurface.hpp
- ql/termstructures/volatility/interpolatedsmilesection.hpp
The header ql/time/daycounters/actual365fixed.hpp was included in ql/termstructure.hpp but not used in the interface of the base class.
> Move inclusion of specific header from base class to derived.

- ql/indexes/interestrateindex.hpp
Looking at the implementation of SwapSpreadIndex (in ql/experimental/coupons), the fixing method won't work properly unless we make InterestRateIndex::pastFixing() virtual.
This extends to other custom indices which rely on historical fixings for some underlying indices instead of providing native fixings themselves.
> make past fixing virtual

- ql/pricingengines/blackformula.cpp
- ql/pricingengines/blackformula.hpp
- test-suite/blackformula.cpp
- test-suite/blackformula.hpp
"An Adaptive Successive Over-relaxation Method for Computing the Black-Scholes Implied Volatility"
M. Li, http://mpra.ub.uni-muenchen.de/6867/
Starting point of the iteration is calculated based on
"An Explicit Implicit Volatility Formula",  R. Radoicic, D. Stefanica,
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2908494
See also: http://chasethedevil.github.io/post/implied-volatility-from-black-scholes-price/
> Adaptive successive over-relaxation method for implied volatility calculation

- ql/math/array.hpp
- ql/math/interpolations/kernelinterpolation2d.hpp
- ql/math/matrixutilities/bicgstab.cpp
- ql/math/matrixutilities/bicgstab.hpp
- ql/math/matrixutilities/gmres.cpp
- ql/math/matrixutilities/gmres.hpp
- ql/math/optimization/simplex.cpp
- ql/math/optimization/simulatedannealing.hpp
It was being implemented (explicitly or implicitly) in a few places in the library.  We can as well make it available as a function.
> Add Norm2 function for Array.

- ql/cashflows/fixedratecoupon.cpp
- ql/cashflows/fixedratecoupon.hpp
- ql/cashflows/overnightindexedcoupon.cpp
- ql/cashflows/overnightindexedcoupon.hpp
- ql/instruments/makeois.cpp
- ql/instruments/makeois.hpp
- ql/instruments/overnightindexedswap.cpp
- ql/instruments/overnightindexedswap.hpp
Adding the possibility to apply a payment lag to overnight indexed swaps.
This can be convention in some markets, such as USD where we believe a 2bd payment lag is applied.
The change is backward compatible, and default to a 0bd adjustment. The test suite has been re-run successfully after the change.
> Payment lag for OIS

- ql/cashflows/cashflows.cpp
- test-suite/bonds.cpp
- test-suite/bonds.hpp
> update yearFraction calculation to next coupon date for #282

- Examples/CDS/CDS.cpp
- ql/cashflows/fixedratecoupon.cpp
- ql/experimental/credit/riskybond.cpp
- ql/experimental/credit/riskybond.hpp
- ql/instruments/creditdefaultswap.cpp
- ql/instruments/creditdefaultswap.hpp
- ql/instruments/makecds.cpp
- ql/instruments/makecds.hpp
- ql/pricingengines/credit/integralcdsengine.cpp
- ql/pricingengines/credit/isdacdsengine.cpp
- ql/pricingengines/credit/isdacdsengine.hpp
- ql/pricingengines/credit/midpointcdsengine.cpp
- ql/termstructures/credit/defaultprobabilityhelpers.cpp
- ql/termstructures/credit/defaultprobabilityhelpers.hpp
- ql/termstructures/credit/piecewisedefaultcurve.hpp
- ql/time/daycounters/actual360.hpp
- test-suite/creditdefaultswap.cpp
- test-suite/creditdefaultswap.hpp
- test-suite/defaultprobabilitycurves.cpp
Comments/reviews welcome! This closes #108 .
> CDS ISDA pricing engine

- ql/pricingengines/asian/mc_discr_arith_av_price.hpp
- ql/pricingengines/asian/mc_discr_arith_av_strike.hpp
- ql/pricingengines/asian/mc_discr_geom_av_price.hpp
- ql/pricingengines/asian/mcdiscreteasianengine.hpp
- ql/timegrid.hpp
- test-suite/asianoptions.cpp
- test-suite/asianoptions.hpp
Fixes #242.
When all fixing dates are in the past, or when today's date is the last fixing date, it's not possible to build a time grid for the simulation.  In the best case, this caused a generic exception; in the worst case, this would cause an access violation and crash the program.
The code now detects these cases and throws an exception with a proper message.
Also, the PR contains a couple of related fixes.  The `TimeGrid` constructor would crash when passed an empty iterator range, and the payoff of Asian options was discounted from the last fixing date instead of the exercise date.
> Detect the case when it's not possible to run a Monte Carlo simulation for Asian options

- ql/termstructures/credit/interpolatedsurvivalprobabilitycurve.hpp
Small refactoring to be in line with the classes InterpolatedHazardRateCurve and InterpolatedDefaultDensityCurve.
With a view to expose this curve in Python and call it in a simpler way.
> Small refactoring of InterpolatedSurvivalProbabilityCurve

- ql/indexes/ibor/fedfunds.cpp
- ql/time/calendars/unitedstates.cpp
- ql/time/calendars/unitedstates.hpp
A few calendar issues:
1) US Government Bond market does not observe Veteran's Day on Friday if it falls on Saturday.  See SIFMA website for verification (specifically the 2006 archive, and current 2017 as well).  Not sure the most elegant way to implement, so just created a generic VeteransDayNoSaturday method that can be used by all calendars.
2) In the US, OIS instruments follow the Federal Reserve bankwire calendar (https://www.frbservices.org/holidayschedules/), which have most holidays not observed if they fall on a Saturday.  Created a new calendar for this, and updated the default calendar for fedfunds.cpp
This is my first time contributing, and I am not a C++ developer by any means, so I hope I didn't butcher the process, and apologize in advance if I did.
> Federal Reserve calendar addition; fixed bug in US Government Bond calendar

- ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp
optionTime and swapLength are swapped when computing the smile section's shift, better rely on the public shift method anyway instead on the internal interpolation object
> fix interpolation of shift

- Docs/Makefile.am
There is no requirement for sed command in Makefile.am as QuantLib.3 is
generated by Doxygen (version >= 1.8.5) already.
Closes #340.
> Minor fix for man page generation.

- ql/math/randomnumbers/sobolrsg.hpp
- test-suite/lowdiscrepancysequences.cpp
Some 64 bit systems (mac, linux) define unsigned long as 64 bit. With the huge number of constants the Sobol sequence requires this results in code bloat with no improvement in performance. The analysis done on the constants was all done assuming 32 bit integers as well, there is no benefit to going to 64 bit until someone publishes some direction integers for it.
>  Replaced "unsigned long" with "uint32_t" in SobolRsg

- ql/experimental/volatility/zabrsmilesection.hpp
- ql/methods/finitedifferences/operators/triplebandlinearop.cpp
- ql/methods/lattices/lattice.hpp
- ql/pricingengines/swaption/gaussian1dswaptionengine.cpp
please see http://www.openmp.org/wp-content/uploads/cspec20.pdf page 12.
Only MSVC seems to enforce this. I've only commented out the ones in
.hpp files. there is one remaining instance in
gaussian1dswaptionengine.cpp, which works fine as I only compile
QuantLib with default options.
> integer in '#pragma omp for' loop must be signed

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/termstructures/yield/Makefile.am
- ql/termstructures/yield/compositezeroyieldstructure.hpp
- test-suite/termstructures.cpp
- test-suite/termstructures.hpp
Implements a `YieldTermStructure` that is based on a binary function of two input `YieldTermStructure`s. This is analogous to `CompositeQuote`, but for yields.
Real world use case: generating an implied inflation yield term structure from a nominal curve and a real curve.
> Implement CompositeZeroYieldStructure

- test-suite/distributions.cpp
- test-suite/paralleltestrunner.hpp
- test-suite/squarerootclvmodel.cpp
>  adapt parallel unit test runner for the upcoming boost 1.66 release 

- ql/experimental/callablebonds/callablebond.cpp
- ql/experimental/callablebonds/callablebond.hpp
- ql/experimental/callablebonds/treecallablebondengine.cpp
- ql/experimental/callablebonds/treecallablebondengine.hpp
- ql/models/shortrate/onefactormodel.cpp
- ql/models/shortrate/onefactormodel.hpp
This approach correctly reproduces the market convention for OAS calculation for log-normal models, where the spread is after the dynamics have been determined, i.e.,  the volatility is relative to the un-spreaded yield curve not the spreaded yield curve.  For this reason this approach is preferred to the approach in #250
> OAS calculation implemented by adding an additional apread to the short rate model

- ql/experimental/credit/onefactoraffinesurvival.hpp
It was used by `InterpolatedAffineHazardRateCurve`, but not declared.
> Add missing OneFactorAffineSurvivalStructure constructor.

- ql/experimental/inflation/cpicapfloortermpricesurface.hpp
In the current version overlapping strike regions for caps and floors (as they are usual in the actual market quotes) are not handled correctly - if extra safety checks are enabled an exception from the bilinear interpolator is thrown ("values are not sorted", which refers to the strike input); if they are not enabled the code runs, but will produce false results. This PR fixes this and also cleans up everything a bit.
> handle case of overlapping strike regions for caps and floors

- ql/instruments/creditdefaultswap.cpp
the test was already amended in the pure running cds case.
> Do not error when using CDS2015 rule

- ql/math/optimization/projectedconstraint.hpp
The upperBound and lowerBound vectors were not matching the size of projected currentValue() vector when a parameter is fixed.
Was raising an error in Constraint class (upperBound and lowerBound functions).
> Projected constraint bug fix

- ql/experimental/inflation/cpicapfloortermpricesurface.hpp
- test-suite/inflationcpicapfloor.cpp
The `CPICapFloorTermPriceSurface` class' constructor takes cap and floor strikes in percentage e.g. 1 for 0.01. The underlying interpolation on strikes is set up in these units also so that the various methods for querying a premium expect the strike in the same units. However, in the `price` method [here](https://github.com/lballabio/QuantLib/blob/612027233c953cfbbe57c3f2b0537ce0b54b28dc/ql/experimental/inflation/cpicapfloortermpricesurface.hpp#L332), entering a strike `k` in percentage units leads to an error.
Commits e9ee6cd381fd7c61c922d63e2a2ba3855fe5b556 and a294761c1ef7bd6cc323ef4b1490a54f41919c56 in this pull request show in the unit tests how this leads to errors.
This pull request fixes this by expecting the strike values in the constructor to be entered without any assumed …
> Fix inconsistent strike units in CPI cap/floor term price surface

- ql/instruments/makecapfloor.cpp
MakeCapFloor uses a vanillaswap which needs a FixedLegDayCounter. Certain currencys have a default DayCounter. This fix avoid the exception for other currencys.
> avoid exception if default fixLegDayCounter is unknown

- ql/math/interpolations/cubicinterpolation.hpp
- test-suite/interpolations.cpp
- test-suite/interpolations.hpp
Fixes #377 
NaN is originally from Line 578. When either of the min or max slope is zero, we'll see it's divided by zero. Here I added a pre-check, if that's the case, make tmp_[i] zero directly.
Sorry for replicate PR for typo in branch name.
> Resolve NaN issue when data to fit is identical

- CMakeLists.txt
CMake builds are broken at present because they are not generating config.hpp. This is done as part of configure, and cannot be easily replicated in CMake without some duplication. This patch takes the easy approach and simply copies across the ANSI configuration and installs it as part of make install. For details on the discussion, see [1]
[1] https://github.com/lballabio/QuantLib/issues/396
Fixes #396.
> CMake: generate and install config.hpp

- ql/instruments/forwardrateagreement.cpp
- ql/instruments/forwardrateagreement.hpp
- test-suite/Makefile.am
- test-suite/forwardrateagreement.cpp
- test-suite/forwardrateagreement.hpp
- test-suite/quantlibtestsuite.cpp
This is an attempt at fixing #371. I don't really understand how the tests work, so i cargo-culted heavily.
Closes #371.
> Don't query the curve in the ForwardRateAgreement constructor

- ql/time/calendars/czechrepublic.cpp
Since 2016, good friday is a bank holiday in czech republic:
https://www.cnb.cz/en/public/media_service/schedules/media_svatky.html
https://prague.tv/en/s72/Directory/c212-Relocation/n5201-Good-Friday-Czech-Republic-s-New-13th-Holiday
> Add new good friday holiday.

- ql/models/shortrate/twofactormodel.cpp
Closes #362 - Initializes the processes vector to size 2 in `TwoFactorModel::ShortRateDynamics::process`
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
> #362 - Initialize processes vector to size of 2.

- ql/time/calendars/turkey.cpp
- ql/time/calendars/turkey.hpp
Holidays >= 2019 are not yet officially anounced by borsaistanbul.com and probably need further validation - however not including them at all is worse in my opinion.
> Additional Turkey Holidays > 2014.

- ql/experimental/coupons/lognormalcmsspreadpricer.cpp
- ql/experimental/coupons/lognormalcmsspreadpricer.hpp
- ql/experimental/coupons/swapspreadindex.hpp
- test-suite/Makefile.am
- test-suite/cmsspread.cpp
- test-suite/cmsspread.hpp
- test-suite/quantlibtestsuite.cpp
- use Bachelier Formula instead of 1D numerical integration, the referenced SSRN paper will be updated accordingly
- add unit tests
> Revise CMS Spread Pricer

- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.cpp
- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.hpp
to avoid a circular reference in case the calibration instrument is priced based on the same Andreasen-Huge volatility surface later on.
> create copy of calibration instrument in Andreasen-Huge Volatility interpolation

- ql/instruments/nonstandardswaption.cpp
Swaption and FloatFloatSwaption were fixed in 1.6, but NonstandardSwaption was forgotten
> add missing registration

- test-suite/piecewiseyieldcurve.cpp
> Use the correct conventions to initialize deposit helpers.

- ql/time/calendars/hungary.cpp
- ql/time/calendars/hungary.hpp
Since 2017, good friday is a bank holiday in hungary:
http://abouthungary.hu/news-in-brief/hungary-to-observe-good-friday-as-a-public-holiday/
http://hungarytoday.hu/news/official-good-friday-voted-become-hungarys-eleventh-public-holiday-89938
> Add good friday holiday to hungarian calendar.

- ql/math/optimization/levenbergmarquardt.cpp
- ql/math/optimization/lmdif.cpp
Relying on null pointer will break if we ever use `nullptr`.
> Use safer boost::function interface.

- test-suite/asianoptions.cpp
- test-suite/barrieroption.cpp
- test-suite/basketoption.cpp
- test-suite/cdo.cpp
- test-suite/europeanoption.cpp
- test-suite/extendedtrees.cpp
- test-suite/hestonmodel.cpp
- test-suite/marketmodel.cpp
- test-suite/optionletstripper.cpp
- test-suite/paralleltestrunner.hpp
- test-suite/zabr.cpp
Change log Boost.Test v3.7 / boost 1.67:
Breaking changes: Adding test cases with the same name to the same test suite is reported as an error. This impacts template and parametrized test cases, as well as manually registered tests. Make sure you have no duplicate names.
> boost 1.67 (beta 1) does not allow to register the same test case name multiple times

- ql/termstructures/volatility/optionlet/optionletstripper2.cpp
if the atm strike lies outside the domain given by the OptionletStripper1's fixed strikes, an exception is thrown in OptionletStripper2; if this is not intentional (i.e. if we do not want to enforce atm to fall into this range for some reason), I'd propose to enable extrapolation on the local adapters
> enable extrapolation on local adapters

- ql/math/initializers.hpp
- test-suite/matrices.cpp
- test-suite/matrices.hpp
Libraries like Eigen or dlib offer convenience initializers for matrices, in Eigen you can for example write
```
Matrix3d m;
m << 1,2,3,
4,5,6,
7,8,9;
```
This pull request aims at providing similar initializers for ```Matrix``` and ```Array```. They do not add any overhead to the existing classes and work "in place". By including the additional header you can then write
```
Array a(5);
a << 1,2,3,4,5;
```
or
```
Matrix m(3,3);
m << 1,2,3,
4,5,6,
7,8,9;
```
> add initializers for arrays and matrices

- ql/experimental/shortrate/generalizedhullwhite.cpp
- ql/experimental/shortrate/generalizedhullwhite.hpp
Some work on the GHW class. This will change the behaviour of existing programs that use the class. The main constructor will now use linear interpolation with flat extrapolation which is how most of the commercial code I've seen works. The previous default involved some hand coded approximations.
The class now supports the Jamshidian pricing engine (under Hull-White only!) and agrees well with tree prices when the number of time steps is set very large. Calibration of model parameters in a typical fashion is supported. Some significant work will need to be done to get finite difference support.
The code could use a little cleaning up. I've commented out dead code which should be removed and added a few utility classes that would be better placed elsewhere.
Sample program that uses almost …
> GeneralizedHullWhite

- ql/instruments/bond.cpp
- ql/instruments/bond.hpp
- ql/instruments/capfloor.cpp
- ql/instruments/capfloor.hpp
- ql/instruments/swap.cpp
- ql/instruments/swap.hpp
- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/ratehelpers.cpp
in #427 we made the floating rate coupon lazy, as a result some instruments contain nested lazy objects now; therefore it makes sense to implement the deepUpdate() method for them, which is done in this PR
furthermore this allows to simplify the update within rate helpers, now just calling deepUpdate() instead of formerly recalculate(); we could think about optimising the deepUpdate() implementation by caching the indices of floating rate coupons and only update them, but for a start I would stick with this simple implementation
last but not least with the lazy coupons from #427 the exposure simulation in our open risk engine does no longer work when disabling observability, which can be fixed by calling deepUpdate(), but this requires the implementation of this method in the relevant …
> updates for lazy frcs and deepUpdate() implementations

- ql/time/schedule.cpp
Fixes #360.
Added pre-check before popping the back elements from isRegular. Since isRegular is regarding intervals between dates. Its size is always dates.size() - 1. So it's unnecessary to check dates's length as long as we confirm isRegular is not empty.
> Check if isRegular is empty before popping elements

- ql/experimental/math/latentmodel.hpp
When including `ql/quantib.hpp`, the latest VC++ compiler doesn't recognized the template argument if used in the class body.  Using a typedef avoids the problem.
Thanks to Benedict Tan for the heads-up.
> Avoid error when using VC++2017 15.7.

- ql/cashflows/conundrumpricer.cpp
- ql/cashflows/lineartsrpricer.cpp
- ql/experimental/coupons/lognormalcmsspreadpricer.cpp
- ql/experimental/finitedifferences/fdmexpextouinnervaluecalculator.hpp
- ql/experimental/finitedifferences/fdmextoujumpmodelinnervalue.hpp
- ql/experimental/finitedifferences/fdmextoujumpop.cpp
- ql/experimental/finitedifferences/fdmspreadpayoffinnervalue.hpp
- ql/experimental/finitedifferences/fdornsteinuhlenbeckvanillaengine.cpp
- ql/experimental/math/piecewiseintegral.hpp
- ql/experimental/models/squarerootclvmodel.cpp
- ql/experimental/volatility/abcdatmvolcurve.hpp
- ql/experimental/volatility/zabrsmilesection.hpp
- ql/math/abcdmathfunction.hpp
- ql/math/interpolations/flatextrapolation2d.hpp
- ql/methods/finitedifferences/operators/fdmbatesop.cpp
- ql/methods/finitedifferences/solvers/fdm1dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm2dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm3dimsolver.cpp
- ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp
- ql/methods/montecarlo/lsmbasissystem.cpp
- ql/patterns/observable.cpp
- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.cpp
- ql/termstructures/volatility/kahalesmilesection.cpp
- ql/termstructures/volatility/optionlet/strippedoptionletadapter.cpp
- ql/termstructures/volatility/swaption/gaussian1dswaptionvolatility.cpp
- ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
- test-suite/barrieroption.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/normalclvmodel.cpp
The point is to use the object as a function, not to invoke the operator explicitly.
> Use operator call idiomatically.

- Docs/Makefile.am
- Examples/Makefile.am
Thanks to UnitedMarsupials.
Closes #501.
> Avoid GNU-specific syntax in Makefiles.

- Examples/BermudanSwaption/BermudanSwaption.cpp
- Examples/Gaussian1dModels/Gaussian1dModels.cpp
- ql/instruments/floatfloatswaption.cpp
- ql/instruments/floatfloatswaption.hpp
- ql/instruments/nonstandardswaption.cpp
- ql/instruments/nonstandardswaption.hpp
- ql/models/calibrationhelper.cpp
- ql/models/calibrationhelper.hpp
- ql/models/equity/hestonmodelhelper.cpp
- ql/models/equity/hestonmodelhelper.hpp
- ql/models/model.cpp
- ql/models/model.hpp
- ql/models/shortrate/calibrationhelpers/caphelper.cpp
- ql/models/shortrate/calibrationhelpers/caphelper.hpp
- ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp
- ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp
- ql/models/shortrate/onefactormodels/gsr.hpp
- ql/models/shortrate/onefactormodels/markovfunctional.hpp
- ql/pricingengines/swaption/basketgeneratingengine.cpp
- ql/pricingengines/swaption/basketgeneratingengine.hpp
- test-suite/batesmodel.cpp
- test-suite/gjrgarchmodel.cpp
- test-suite/hestonmodel.cpp
- test-suite/hybridhestonhullwhiteprocess.cpp
- test-suite/libormarketmodel.cpp
- test-suite/markovfunctional.cpp
- test-suite/shortratemodels.cpp
Ported from the (now outdated) `tenorbasis` branch.
This allows helpers not based on the Black model.
The name `CalibrationHelper` was too generic for the existing Black-based class, and was changed to `BlackCalibrationHelper`; the old name was kept as a deprecated typedef.
In a few releases, we can retire the `CalibrationHelper` name and give it to the new base class.
> Add base class above CalibrationHelper.

- QuantLib.spec.in
Executing rpmbuild -ba QuantLib.spec executes %build and %install successfully but fails %check
> Make QuantLib.spec file pass %check

- ql/indexes/bmaindex.cpp
- ql/indexes/bmaindex.hpp
Current `BMAIndex` implementation hard-codes `UnitedStates::NYSE` fixing calendar, which does not match the SIFMA holiday recommendations, see [https://www.sifma.org/resources/general/holiday-schedule/](https://www.sifma.org/resources/general/holiday-schedule/). The proposed change allows user to specify a holiday calendar, defaulting to the current value of `UnitedStates::NYSE` (note that QuantLib currently has no SIFMA holiday calendar implementation). Existing code will be unaffected by the change.
> allow fixing calendar selection in BMA index

- ql/cashflows/cpicouponpricer.cpp
- ql/cashflows/cpicouponpricer.hpp
- ql/cashflows/inflationcouponpricer.cpp
- ql/cashflows/inflationcouponpricer.hpp
- ql/experimental/inflation/interpolatedyoyoptionletstripper.hpp
- ql/experimental/inflation/yoycapfloortermpricesurface.hpp
- ql/experimental/inflation/yoyoptionlethelpers.cpp
- ql/instruments/makeyoyinflationcapfloor.cpp
- ql/instruments/makeyoyinflationcapfloor.hpp
- ql/pricingengines/inflation/inflationcapfloorengines.cpp
- ql/pricingengines/inflation/inflationcapfloorengines.hpp
- ql/termstructures/inflation/inflationhelpers.cpp
- ql/termstructures/inflation/inflationhelpers.hpp
- test-suite/inflation.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpicapfloor.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/inflationvolatility.cpp
This is a precondition for removing the nominal curve from inflation curves (the fact that their base class stores it is inconsistent with all other curves in the library).
> Don't rely on the inflation curve providing a nominal curve

- test-suite/Makefile.am
- test-suite/quantlibtestsuite.cpp
- test-suite/timegrid.cpp
- test-suite/timegrid.hpp
Basic unit tests for the TimeGrid class. I've run them on Windows 32bit using Visual Studio. If these look good I can run them on my Ubuntu machine to make sure they run on Linux.
Tests cover:
* Basic constructors with mandatory periods only, additional periods via an iterator and evenly spaced periods.
* Edge cases (empty iterator + negative times) in constructor method.
* Public methods; closestIndex, closestTime and mandatoryTimes.
I'm not sure if there are any more tests you would like to have added.
closes #315
> Basic unit tests for TimeGrid class

- .clang-format
the variant using 'Yes' does not work with clang-format 6.0.0, is that an old convention (or a brand new one?)
> fix clang format file

- test-suite/riskneutraldensitycalculator.cpp
The previous value could give slightly different results (depending on the version of libc on Ubuntu) that would get amplified by the local-volatility calculation, causing the test to fail.
> Avoid instabilities in test case.

- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- acinclude.m4
- ql/experimental/math/fireflyalgorithm.cpp
- ql/experimental/math/fireflyalgorithm.hpp
- ql/experimental/math/hybridsimulatedannealingfunctors.hpp
- ql/experimental/math/levyflightdistribution.hpp
- ql/experimental/math/particleswarmoptimization.cpp
- ql/experimental/math/particleswarmoptimization.hpp
- ql/patterns/observable.hpp
- ql/qldefines.hpp
The minimum requirement used to be version 1.43, but parts of the library had to be conditionally disabled when using a version this old.
Boost 1.48 came out in 2011, so it doesn't seem unreasonable to require.
> Require Boost 1.48 or later

- Docs/pages/config.docs
- configure.ac
- ql/termstructures/yield/bootstraptraits.hpp
- ql/termstructures/yield/discountcurve.hpp
- ql/termstructures/yield/forwardcurve.hpp
- ql/termstructures/yield/zerocurve.hpp
- ql/termstructures/yieldtermstructure.cpp
- ql/userconfig.hpp
- test-suite/basismodels.cpp
- test-suite/markovfunctional.cpp
- test-suite/optionletstripper.cpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/piecewiseyieldcurve.hpp
- test-suite/quantlibtestsuite.cpp
It's been the default for a long time, and nowadays I don't see a use case for forcing positive rates that is worth maintaining the switch.
> Remove switch for negative rates.

- test-suite/assetswap.cpp
Closes #605.
this pull request fix assetswap_test, testSpecializedBondVsGenericBondUsingAsw
line 4206, it should be comparing `error15` to `tolerance` instead of `error8`
```cpp
Real error15 = std::fabs(zeroCpnBondAssetSwapPrice2
-zeroCpnSpecializedBondAssetSwapPrice2);
if (error15>tolerance) {
BOOST_FAIL("wrong clean price for zerocpn bond:"
<< std::fixed << std::setprecision(4)
<< "\n  generic zero cpn bond's clean price: "
<< zeroCpnBondAssetSwapPrice2
<< "\n  equivalent specialized bond's price: "
<< zeroCpnSpecializedBondAssetSwapPrice2
<< "\n  error:                 " << error15
<< "\n  tolerance:             " << tolerance);
}
```
> fix testSpecializedBondVsGenericBondUsingAsw

- ql/time/schedule.cpp
- test-suite/schedule.cpp
- test-suite/schedule.hpp
I think we should add the check starting in line 436 in every case (prevents a possible invalid read).
Not 100% sure about the change in line 394, what do you think? The use case on our side is the construction of a schedule for an instrument following certain conventions (1Y tenor, end of month) but in this particular case the overall maturity of the instrument itself is shorter (1W), so the expected result is only the one stub period given by the effective date and the termination date.  The current logic in the schedule building collapses this further to a single date though. In my opinion, this case should be handled similarly as if the tenor was 1W, in which case an end of month adjustment would be skipped in the existing builder as well?
> Fix segfault in short eom schedule generation

- Examples/MarketModels/MarketModels.cpp
- test-suite/basismodels.cpp
- test-suite/catbonds.cpp
- test-suite/piecewisezerospreadedtermstructure.cpp
They might be convenient at first, but once one knows what is required, they're not worth the added compilation time.  I'm not sure whether we should discourage their use, or deprecate them in some way.  But at least we can avoid their usage in the library itself.
> Avoid internal usage of all.hpp headers.

- ql/time/calendar.hpp
- test-suite/calendars.cpp
For calendars, I've found it useful to have the list of added and remove public holidays exposed.
This PR adds the necessary methods to expose them. Not sure if this is the correct implementation and whether the `std::set<Date>` should by returned by value or by reference. This PR currently returns it by value, which probably means the user cannot alter the underlying items in the set (not sure). Please guide me as you think this should be implemented, if at all.
> Publicly expose Calendar::addedHolidays and Calendar::removeHolidays

- ql/experimental/barrieroption/wulinyongdoublebarrierengine.cpp
save `rebateIn` to `results_.additionalResults`
> fix wulinyongdoublebarrierengine not saving rebateIn

- ql/experimental/barrieroption/analyticdoublebarrierengine.hpp
- ql/experimental/barrieroption/wulinyongdoublebarrierengine.cpp
- ql/experimental/barrieroption/wulinyongdoublebarrierengine.hpp
> Prune unused (or even undefined) methods.

- ql/time/calendars/canada.cpp
The following Monday is a business holiday if New Years day falls on either a Saturday or Sunday in Canada. In USA, the following Monday is only a business holiday if New Years day occurs on the Sunday.
For example, in 2022 Jan 3 is a holiday in Canada but not in USA.
See https://www.timeanddate.com/calendar/?year=2022&country=27
> Small fix to Canada Calendar

- Examples/BasketLosses/BasketLosses.cpp
- Examples/BermudanSwaption/BermudanSwaption.cpp
- Examples/Bonds/Bonds.cpp
- Examples/CDS/CDS.cpp
- Examples/CVAIRS/CVAIRS.cpp
- Examples/CallableBonds/CallableBonds.cpp
- Examples/ConvertibleBonds/ConvertibleBonds.cpp
- Examples/DiscreteHedging/DiscreteHedging.cpp
- Examples/EquityOption/EquityOption.cpp
- Examples/FRA/FRA.cpp
- Examples/FittedBondCurve/FittedBondCurve.cpp
- Examples/Gaussian1dModels/Gaussian1dModels.cpp
- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- Examples/LatentModel/LatentModel.cpp
- Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
- Examples/MultidimIntegral/MultidimIntegral.cpp
- Examples/Replication/Replication.cpp
- Examples/Repo/Repo.cpp
Straightforward change as described in #666 , in lieu of complicating the library with the most recent versions of Boost::Timer (which is no longer header-only), I have simply removed this functionality from all of the examples.
> Removed Depreciated Boost::Timer from all examples.

- Examples/BasketLosses/BasketLosses.vcxproj
- Examples/BermudanSwaption/BermudanSwaption.vcxproj
- Examples/Bonds/Bonds.vcxproj
- Examples/CDS/CDS.vcxproj
- Examples/CVAIRS/CVAIRS.vcxproj
- Examples/CallableBonds/CallableBonds.vcxproj
- Examples/ConvertibleBonds/ConvertibleBonds.vcxproj
- Examples/DiscreteHedging/DiscreteHedging.vcxproj
- Examples/EquityOption/EquityOption.vcxproj
- Examples/FRA/FRA.vcxproj
- Examples/FittedBondCurve/FittedBondCurve.vcxproj
- Examples/Gaussian1dModels/Gaussian1dModels.vcxproj
- Examples/GlobalOptimizer/GlobalOptimizer.vcxproj
- Examples/LatentModel/LatentModel.vcxproj
- Examples/MarketModels/MarketModels.vcxproj
- Examples/MulticurveBootstrapping/MulticurveBootstrapping.vcxproj
- Examples/MultidimIntegral/MultidimIntegral.vcxproj
- Examples/Replication/Replication.vcxproj
- Examples/Repo/Repo.vcxproj
- QuantLib.props
- QuantLib.vcxproj
- cmake/quantlib.cmake
- ql/auto_link.hpp
- test-suite/testsuite.vcxproj
This should no longer need to be maintained when new versions of VC++ are released.
> Don't include VC++ toolset into library name

- test-suite/marketmodel.cpp
testPathwiseVega failed with a SE of ~3.553 when compiled with VC142
this commit bumps the threshold value `errorInSE` from 3.5 to 4.0,
leading to a passing test.
closes #335
> Bump errorInSE threshold in test marketmodel

- ql/termstructures/yield/piecewiseyieldcurve.hpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/piecewiseyieldcurve.hpp
When trying to construct a `PiecewiseYieldCurve` with an explicit `Bootstrap` instance, there is a compilation error. The additional test triggers this compilation error and the subsequent commit allows the code to compile.
> Pass explicit bootstrap to PiecewiseYieldCurve

- .gitignore
- ql/pricingengines/blackformula.cpp
- ql/pricingengines/blackformula.hpp
- ql/pricingengines/capfloor/bacheliercapfloorengine.cpp
- ql/pricingengines/capfloor/blackcapfloorengine.cpp
- test-suite/capfloor.cpp
- test-suite/capfloor.hpp
I am working on adding delta coefficients to `additionalResults` of 'CapFloor' instruments.
For the moment I am working with `BlackCapFloorEngine`, but I intend to do similar task at least for  `BachelierCapFloorEngine`.
Since the work involves changes in widely used classes, I started with a small unittest, which was a copy of `CapFloorTest::testCachedValue`.
Initially the test was supposed to be written for `optionletsForwardDelta`, but having experienced strange behavior, I reworked it to something similar to original test.
The added test is `CapFloorTest::testCachedValueFromOptionLets`.
I am calling the test by:
```bash
/home/wojtek/coding/github/QuantLib/build/test-suite/quantlib-test-suite --log_level=test_suite --run_test=*/Cap*
```
The relevant outcome is:
```bash
Testing Black …
```
> Return delta from Black cap/floor engine

- ql/methods/finitedifferences/finitedifferencemodel.hpp
- ql/methods/finitedifferences/meshers/fdmblackscholesmesher.cpp
- ql/methods/finitedifferences/solvers/fdm1dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm2dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdm3dimsolver.cpp
- ql/methods/finitedifferences/solvers/fdmndimsolver.hpp
- ql/pricingengines/vanilla/fdblackscholesvanillaengine.cpp
- ql/pricingengines/vanilla/fddividendamericanengine.hpp
- ql/pricingengines/vanilla/fddividendeuropeanengine.hpp
- test-suite/dividendoption.cpp
- test-suite/dividendoption.hpp
contains Luigi's PR #714. 
behaviour for dividend payments a t=0 is in sync with AnalyticDividendEuropeanEngine.
theta calculation for spot dividend model with a dividend payment at t=0 is disabled.
> Deprecate remaining old-style FD dividend options

- ql/instruments/forwardrateagreement.cpp
- ql/instruments/forwardrateagreement.hpp
- ql/termstructures/yield/ratehelpers.cpp
- ql/termstructures/yield/ratehelpers.hpp
- test-suite/forwardrateagreement.cpp
- test-suite/piecewiseyieldcurve.cpp
This change implements a "par coupon approximation" for FRAs in analogy to swaps or more precisely to the forward rate estimation in `IborCoupon`.
I appreciate that this is a breaking change. Still, there might be reasons to consider doing the change:
- when trying to match zero rates from rate curve stripped in Blooomberg it turns out that this requires the usage of the par coupon approximation for both swaps and FRAs
- a more academic argument is that the current implementation is inconsistent to a certain degree since the forward rate for FRAs is estimated differently from what is done for the floating periods of swaps
As a side note, the FRAs defined in the piecewise yield curve test seem not to match what is usually traded, this is also fixed in the PR (which is actually necessary to …
> par approximation for FRAs

- ql/termstructures/yield/fittedbonddiscountcurve.cpp
- test-suite/Makefile.am
- test-suite/fittedbonddiscountcurve.cpp
- test-suite/fittedbonddiscountcurve.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
> Let a fitted bond curve work correctly as an evaluator.

- ql/handle.hpp
e.g. the following code does not compile without this fix
```
#include <ql/handle.hpp>
std::map<int, QuantLib::Handle<int>> m,n;
bool test = m == n;
```
> comparisons in Handle should be const

- ql/termstructures/yield/bondhelpers.cpp
- ql/termstructures/yield/bondhelpers.hpp
- ql/termstructures/yield/fittedbonddiscountcurve.cpp
This PR builds on the work in #648 . It adds constructors on the `BondHelper` classes to use the new `Bond::Price::Type` values and deprecates the old constructors that rely on `useCleanPrice`.
I didn't add explicit tests, but the existing tests that use `BondHelper`s test this implicitly.
> Add BondHelper constructors to use new Bond::Price::Type parameter

- acinclude.m4
I installed `libboost-test-dev` and `libboost-timer-dev`, but this check still failed for me.  I dug in to `config.log` and found that it was actually the lack of Boost System that was hampering me.  Then I looked at the PR that introduced these dependencies, #692, and noticed that the message was updated with the addition of Timer, but not with the addition of System, so it seemed a simple oversight that I could easily correct to save others from the same trouble.
I also took the liberty of formalizing the library names in the message, since when I was installing these dependencies it wasn't immediately clear to me that "unit-test framework" was a part of Boost Test.  (I initially thought perhaps it was yet another Boost library entirely.)
> Clarify ./configure message for Boost Test search

- test-suite/nthtodefault.cpp
- test-suite/nthtodefault.hpp
There was a typo in the HullWhite spread data table,
also removed duplicated gaussianCopula test and increased
the relative tolerance so that the test will pass as is.
Fixes #262.
> Fix typo in hwData, increase tolerance for studentCopula test

- ql/cashflows/averagebmacoupon.cpp
Trying to set up a `BMACoupon` with startDate = 01-01-2026, endDate = 01-02-2026 results in an exception "2nd leg: first fixing date valid after period start" since the fixing schedule does not cover the required period.
This PR makes sure that the fixing schedule constructed in the coupon satisfies the requirements in the `AverageBMACouponPricer`.
> Fix BMA Coupon Fixing Schedule

- ql/time/calendars/germany.cpp
- ql/time/calendars/germany.hpp
- test-suite/calendars.cpp
Removed 31 st Dec as holiday from German calendar #768
> Fixed German calendar , by removing 31st Dec as holiday

- ql/pricingengines/swaption/blackswaptionengine.hpp
This PR prevents the black swaption engine from throwing an exception "non-positive swap length (0) given" when the underlying length is less than half a month and therefore rounded down to zero in `SwaptionVolatilityStructure::swapLength()`. Instead the volatility and shift are read at a swap length of 1/12 in this case.
> ensure a volatility and shift can be read for given swapLength

- ql/experimental/credit/defaultprobabilitylatentmodel.hpp
- ql/experimental/math/latentmodel.hpp
- ql/experimental/math/multidimintegrator.hpp
- ql/experimental/math/multidimquadrature.hpp
- ql/functional.hpp
- test-suite/linearleastsquaresregression.cpp
- test-suite/riskneutraldensitycalculator.cpp
- test-suite/squarerootclvmodel.cpp
For some combination of configure flags, both the std and the boost version of the `_1`, `_2`... placeholders are imported in some files so the code needs to disambiguate.  This change allows referring to them as `ext::placeholders::_1` regardless of the chosen implementation.
> Import global boost placeholders into ext::placeholders namespace.

- ql/instruments/bond.cpp
- ql/instruments/bond.hpp
This PR extends the previous work on `Bond::Price::Type` and adds the parameter to `Bond::yield()` methods
> Implement Bond::Price::Type parameter in Bond::yield() method

- ql/cashflows/cpicoupon.cpp
- ql/cashflows/cpicouponpricer.cpp
- ql/cashflows/cpicouponpricer.hpp
- ql/cashflows/inflationcouponpricer.cpp
- ql/cashflows/inflationcouponpricer.hpp
- ql/cashflows/yoyinflationcoupon.cpp
- ql/experimental/inflation/cpicapfloortermpricesurface.cpp
- ql/experimental/inflation/cpicapfloortermpricesurface.hpp
- ql/experimental/inflation/yoycapfloortermpricesurface.cpp
- ql/experimental/inflation/yoycapfloortermpricesurface.hpp
- ql/termstructures/inflation/inflationhelpers.cpp
- ql/termstructures/inflation/interpolatedyoyinflationcurve.hpp
- ql/termstructures/inflation/interpolatedzeroinflationcurve.hpp
- ql/termstructures/inflation/piecewiseyoyinflationcurve.hpp
- ql/termstructures/inflation/piecewisezeroinflationcurve.hpp
- ql/termstructures/inflationtermstructure.cpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpicapfloor.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/inflationvolatility.cpp
In some cases, this requires passing the term structure to an instrument through a pricer; for instance,
CPIBond bond(...);
bond.setPricingEngine(ext::make_shared<DiscountingBondEngine>(discountCurve));
now also requires 
setCouponPricer(bond.cashflows(), ext::make_shared<CPICouponPricer>(nominalTS));
since the nominal curve is no longer stored inside the inflation index passed to the bond.
> Deprecate the storage of nominal term structure inside inflation curves.

- Examples/EquityOption/EquityOption.cpp
- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/models/shortrate/onefactormodels/vasicek.hpp
- ql/pricingengines/vanilla/Makefile.am
- ql/pricingengines/vanilla/all.hpp
- ql/pricingengines/vanilla/analyticeuropeanvasicekengine.cpp
- ql/pricingengines/vanilla/analyticeuropeanvasicekengine.hpp
This pull request is to add an analytical pricing engine for vanilla via the Vasicek interest rate model.
Analytical formula is based on the following research paper
http://hsrm-mathematik.de/WS201516/master/option-pricing/Black-Scholes-Vasicek-Model.pdf
Example usage has been added under EquityOption.cpp
> Black vasicek pricing engine

- ql/termstructures/iterativebootstrap.hpp
- test-suite/defaultprobabilitycurves.cpp
- test-suite/defaultprobabilitycurves.hpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/piecewiseyieldcurve.hpp
This pull request proposes two separate features for the `IterativeBootstrap` class:
1. ability to retry on failure at each pillar, up to a maximum number of attempts, with a possible widening of the minimum and maximum on each retry.
2. a flag that allows the bootstrap to not throw and fall back on the _best_ result between the minimum and maximum value at each pillar.
For 1 above, the parameters `maxAttempts`, `maxFactor` and `minFactor` are relevant. If `maxAttempts` is set to `1`, which is its default value, the bootstrap behaves exactly as before and there are no retries at each pillar. If `maxAttempts` is greater than `1`, say `n`, the search for a root at each pillar during the bootstrap can be attempted up to `n` times. On each successive attempt, the search area from minimum to …
> Iterative bootstrap - widen min, max in search and fall back

- ql/functional.hpp
- ql/patterns/observable.cpp
Since version 1.60, bind placeholders (`_1`, `_2` etc.) are defined in the `boost::placeholders` namespace.  This avoid a deprecation note when including the `<boost/bind.hpp>`, which imports them in the global namespace.
> Get bind placeholders from boost::placeholders namespace.

- ql/methods/finitedifferences/americancondition.hpp
- ql/methods/finitedifferences/fdtypedefs.hpp
- ql/methods/finitedifferences/shoutcondition.hpp
- ql/methods/finitedifferences/stepcondition.hpp
Most of it was unused, and it caused a virtual function to be called inside the condition loop.
> Deprecate curve-dependent step condition

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/methods/finitedifferences/operators/Makefile.am
- ql/methods/finitedifferences/operators/all.hpp
- ql/methods/finitedifferences/operators/fdmcirop.cpp
- ql/methods/finitedifferences/operators/fdmcirop.hpp
- ql/methods/finitedifferences/operators/ninepointlinearop.cpp
- ql/methods/finitedifferences/operators/ninepointlinearop.hpp
- ql/methods/finitedifferences/solvers/Makefile.am
- ql/methods/finitedifferences/solvers/all.hpp
- ql/methods/finitedifferences/solvers/fdmcirsolver.cpp
- ql/methods/finitedifferences/solvers/fdmcirsolver.hpp
- ql/pricingengines/vanilla/Makefile.am
- ql/pricingengines/vanilla/all.hpp
- ql/pricingengines/vanilla/fdcirvanillaengine.cpp
- ql/pricingengines/vanilla/fdcirvanillaengine.hpp
- ql/processes/Makefile.am
- ql/processes/all.hpp
- ql/processes/coxingersollrossprocess.cpp
- ql/processes/coxingersollrossprocess.hpp
- test-suite/CMakeLists.txt
- test-suite/Makefile.am
- test-suite/fdcir.cpp
- test-suite/fdcir.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
The short rate for a CoxIngersollRoss process can be described by the following SDE
By following the methodology described here http://scriptiesonline.uba.uva.nl/document/656101, using Ito's Lemma and riskless portfolio, the PDE for an option under CIR short rate can be derived as
By doing a change of variables for X=lnS, the PDE becomes
A test has been added to show that the value converges between multiple evolver schemes.
Also, as the sigma for the underlying black scholes process can only be determined during setTime(t1, t2), I needed a way to update the coefficients in the ninepointlinearop(equivalent to the apxb in triplebandlinearop) so i created a reset method for that but I'm open to better ways of doing that instead.
> Finite Difference Engine for Option under CoxIngersollRoss Short Rate Process

- ql/termstructures/yield/discountcurve.hpp
- ql/termstructures/yield/forwardcurve.hpp
- ql/termstructures/yield/forwardstructure.cpp
- ql/termstructures/yield/forwardstructure.hpp
- ql/termstructures/yield/interpolatedsimplezerocurve.hpp
- ql/termstructures/yield/zerocurve.hpp
- ql/termstructures/yield/zeroyieldstructure.cpp
- ql/termstructures/yield/zeroyieldstructure.hpp
- ql/termstructures/yieldtermstructure.cpp
- ql/termstructures/yieldtermstructure.hpp
When no dates were passed, the jumps were initialized incorrectly.
> Deprecate term-structure constructors taking jumps and no reference date.

- ql/processes/blackscholesprocess.cpp
I noticed this when using `GeneralizedBlackScholesProcess` with an externally given local vol ts: Since `isStrikeIndependent_` was `true` in my case, mc simulation results based on `evolve()` looked wrong.
> init isStrikeIndependent_

- test-suite/calendars.cpp
This PR fixes an out of bound bug in `CalendarTest::testDayLists`.
Basically, no *iterator-end-check* was performed in https://github.com/lballabio/QuantLib/blob/e6e81b23cf3dbf81be5ae86bfe8b3b94ceb0a8ca/test-suite/calendars.cpp#L2203
Therefore, when either `it_holidays` or `it_businessDays` reach `end` iterator, they're still dereferenced to be checked against `d`, hence yielding to undefined behavior.
This was detected by `MSVC` when compiling `test-suite` in debug mode.
> Fix out of bound access in CalendarTest::testDayLists

- ql/time/calendars/germany.cpp
- ql/time/calendars/germany.hpp
- test-suite/calendars.cpp
Fix for #840 after New Years was removed from all German calendars.
> Adding New Years Eve Holiday back for Eurex calendar

- ql/indexes/bmaindex.cpp
- ql/indexes/bmaindex.hpp
- ql/indexes/interestrateindex.cpp
- test-suite/CMakeLists.txt
- test-suite/Makefile.am
- test-suite/indexes.cpp
- test-suite/indexes.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
Previously, adding a fixing to a BMA index would not notify observers.
> Deprecate unused BMA index constructor; fix observability.

- ql/time/date.cpp
- ql/time/date.hpp
- test-suite/dates.cpp
- test-suite/dates.hpp
- test-suite/timeseries.cpp
This PR adds `hash_value` method to `Date`, enabling `boost::hash<Date>`
> Add boost::hash specialization for Date

- Docs/pages/license.docs
- LICENSE.TXT
- ql/time/calendar.cpp
- ql/time/calendar.hpp
This PR fixes #785 by implementing **Scenario 2** improvements (as described in https://github.com/lballabio/QuantLib/issues/785#issuecomment-648910443).
This PR depends on #851
> Improve Calendar performance

- ql/instruments/bonds/fixedratebond.cpp
- ql/instruments/bonds/fixedratebond.hpp
Canadian bonds have a different day count convention on a short first stub for both cashflow generation and accrual. This modification adds support for an additional first coupon day counter in the FixedRateBond class. The only api change is a new optional argument in two of the FixedRateBond constructors.
> Added first coupon dayCounter to FixedRateBond

- ql/math/optimization/linesearchbasedmethod.hpp
- ql/math/optimization/simulatedannealing.hpp
Add basic doc comments just to enable doxygen to generate a complete inheritance diagram for OptimizationMethod.
Resolves issue #675, but only for class OptimizationMethod.
> Add basic doc comments to include all classes inheriting from OptimizationMethod in doxygen

- test-suite/paralleltestrunner.hpp
between
#include <boost/timer/timer.hpp>
and
#include <boost/time.hpp>
for boost version < 1.70.
> fixed name clash in paralleltestrunner.hpp 

- ql/math/interpolations/loginterpolation.hpp
- test-suite/overnightindexedswap.cpp
- test-suite/piecewiseyieldcurve.cpp
Created a few convenience classes for LogCubic and LogMixedLinearCubic interpolators, taking advantage of some sensible parameters set in Quantlib-SWIG.
Fixes #827.
> LogCubic convenience classes

- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- configure.ac
- ql/Makefile.am
- ql/experimental/credit/randomdefaultlatentmodel.hpp
- ql/experimental/credit/saddlepointlossmodel.hpp
- ql/experimental/models/hestonslvfdmmodel.cpp
- ql/methods/finitedifferences/meshers/concentrating1dmesher.cpp
- ql/methods/finitedifferences/meshers/concentrating1dmesher.hpp
- ql/quantlib.hpp
- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.cpp
- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.hpp
- ql/tuple.hpp
- ql/userconfig.hpp
- test-suite/andreasenhugevolatilityinterpl.cpp
- test-suite/fdcir.cpp
- test-suite/fdheston.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/interpolations.cpp
implement #871 
The big change is that the C++ standard intentionally does not support foo.get<1>() syntax so those had to be changed to get<1>(foo) syntax.
Also some std::forwards had to be included
> fix to have option of using std::tuple

- ql/experimental/fx/blackdeltacalculator.cpp
AtmSpot is missing in the BlackDeltaCalculator for FX quote conventions. Currently, requesting atmStrike() with this atm convention returns "invalid atm type"
> Adding AtmSpot calculation to the BlackDeltaCalculator

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/pricingengines/asian/Makefile.am
- ql/pricingengines/asian/all.hpp
- ql/pricingengines/asian/mc_discr_arith_av_price.hpp
- ql/pricingengines/asian/mc_discr_arith_av_strike.hpp
- ql/pricingengines/asian/mc_discr_geom_av_price.hpp
- ql/pricingengines/asian/mcdiscreteasianengine.hpp
- ql/pricingengines/asian/mcdiscreteasianenginebase.hpp
I'd like to add a Heston MC pricer for arithmetic asian options, in order to re-use mcdiscreteasianengine.hpp as a parent class I need to template it to the process type (SingleVariate vs. MultiVariate).
Hopefully this commit change won't change any current behaviour. But subsequent work will be easier.
> Templating asian pricing engines on their process type

- ql/experimental/amortizingbonds/amortizingfixedratebond.cpp
- ql/experimental/amortizingbonds/amortizingfixedratebond.hpp
- test-suite/amortizingbond.cpp
- test-suite/amortizingbond.hpp
1. Added constructor for amortizing fixed-rate bonds taking a generic InterestRate instance (like the change introduced in release 0.9.9)
2. Add a test suite to this constructor based on ISIN BRRISFDBS005 expected cashflows
A separated pull request is being prepared to QuantLib-SWIG as soon as this one is accepted.
> Enhance Amortizing fixed rate bond class to accept InterestRate object

- ql/time/calendars/japan.cpp
Japanese government announced that new Japan calendar has been enacted for Olympics games in 2021. This will cause some national holiday move in 2021 and my change is for taking care of this. Although only in Japanese, you can see the announce in below. 
https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html
> update Japan calender

- ql/pricingengines/forward/mcforwardeuropeanhestonengine.hpp
- ql/pricingengines/forward/mcforwardvanillaengine.hpp
- test-suite/forwardoption.cpp
For well-behaved Heston parameters and nearby reset dates, using a vanilla option with the same expiry date and an analytic Heston pricer can provide a significant improvement in MC convergence.
Shown here is an option starting on 24th Nov 2020 and expiring 1 year later, with MC prices with and without CV for several reset dates. As expected, convergence is significantly improved for nearby reset dates, and not much for far away reset dates. Heston params here are v0: 0.09, kappa: 1.15, theta: 0.348, sigma: 0.39, rho: -0.64, and additionally r=0.5%, q=3%, spot=100, k=1.1.
Variance reduction coming from use of control variates is determined mostly by the correlation of the path prices of the two securities and scales as (1-correlation^2), so when correlation is below ~70% the additional …
> Adding a vanilla control variate to the Heston forward start MC pricer

- ql/instruments/swap.cpp
- ql/instruments/swap.hpp
- test-suite/swap.cpp
> Expose number of swap legs

- ql/pricingengines/asian/mc_discr_arith_av_price_heston.cpp
- ql/pricingengines/asian/mc_discr_arith_av_price_heston.hpp
- ql/pricingengines/asian/mcdiscreteasianenginebase.hpp
- test-suite/asianoptions.cpp
I was investigating the behaviour of the recently-added MC Arithmetic Asian Heston Pricer (https://github.com/lballabio/QuantLib/pull/941), and realised I'd overlooked allowing user to specify number of time steps used in the discretization. By default, it just uses one per fixing, but user might wish to create a more finely grained mesh. For BS it's not important as the propagator distributions are gaussian, but for Heston things are not so straightforward.
I have a proposal here that will fix, but there are a couple of issues to consider:
1) In this adjustment, I've made it compulsory to specify number of steps (for Heston). Perhaps this is too strict, and it should default to the number of fixings, with an option to specify additional steps?
2) This change will break the existing …
> Forcing specification of timeSteps for MC Arithmetic Asian Heston Pricer

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/pricingengines/asian/Makefile.am
- ql/pricingengines/asian/all.hpp
- ql/pricingengines/asian/mc_discr_geom_av_price_heston.cpp
- ql/pricingengines/asian/mc_discr_geom_av_price_heston.hpp
- test-suite/asianoptions.cpp
- test-suite/asianoptions.hpp
This pricer isn't particularly useful by itself as these options don't trade as far as I know, but we'll need it to implement a control variate for the equivalent arithmetic option pricer once the analytical pricer for these geometric options is implemented (coming soon). It also adds some tests that we will re-use for that pricer, and provides a useful sanity check for the analytical results.
> Adding a MC Heston pricer for discrete geometric asian options

- Examples/FittedBondCurve/FittedBondCurve.cpp
- ql/termstructures/yield/nonlinearfittingmethods.cpp
- ql/termstructures/yield/nonlinearfittingmethods.hpp
In practical use it is sometimes easier (& quicker) to use fewer than the standard 9 coefficients, and also to fix Kappa (as the fit is relatively insensitive to this variable). These mods add new default parameters to the existing ExponentialSplinesFitting constructor, and an additional reduced constructor for defining the number of parameters and a fix for Kappa. New member variables have been added to hold the number of coefficients and the value for the fixed Kappa. If a fixed Kappa has been provided (tested as not QL_NULL_REAL) then this value is used in the discountFunction() implementation.
The example/test app FittedBondDiscountCurve has been amended to include this additional fitting method.
If other fitting methods would benefit from fixing parameters that are currently …
> Modified ExponentialSplinesFitting to handle variable coeffs and fixed kappa

- .github/workflows/cmake-win.yml
The `set-env` command has been disabled (at least for the windows workflow) by [GitHub](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). It can explicitly be enabled again by these changes.
> The set-env command is disabled.

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/experimental/asian/Makefile.am
- ql/experimental/asian/all.hpp
- ql/experimental/asian/analytic_cont_geom_av_price_heston.cpp
- ql/experimental/asian/analytic_cont_geom_av_price_heston.hpp
- ql/experimental/asian/analytic_discr_geom_av_price_heston.cpp
- ql/experimental/asian/analytic_discr_geom_av_price_heston.hpp
- test-suite/asianoptions.cpp
- test-suite/asianoptions.hpp
An implementation of the procedure developed in "[A Recursive Method for Discretely Monitored Geometric Asian Option Prices](https://koreauniv.pure.elsevier.com/en/publications/a-recursive-method-for-discretely-monitored-geometric-asian-optio)", B. Kim, J. Kim, J. Kim & I. S. Wee, Bull. Korean Math. Soc. 53, 733-749 (2016) to price discrete geometric asians.
The results are tested against the results presented in the paper.
This pricer will later be used as a control variate for discrete arithmetic asians when priced under Heston.
> Initial commit for Analytic Discrete Geometric Average Asian pricer

- ql/experimental/asian/analytic_discr_geom_av_price_heston.cpp
- ql/experimental/asian/analytic_discr_geom_av_price_heston.hpp
- ql/pricingengines/asian/mc_discr_arith_av_price_heston.hpp
- test-suite/asianoptions.cpp
Adding the geometric analytic and MC pricers to the MC arithmetic pricer as a control variate - using a geometric asian as a control variate for the arithmetic asian is a classic and powerful example of the technique, given the very high correlation in the path prices of the two instruments (see below).
To make this work I have had to disable the check for geometric average type in the analytic pricer (similar to the BS geometric pricer which also had this disabled). I've also added additional test cases to the test suite.
I have tested for a variety of Heston parameters and the path prices are always highly correlated, as shown for two examples here:
Convergence is greatly speeded up, MC errors are typically reduced by a factor of over thirty (ie. sqrt(1-rho^2) ). Some examples are shown …
> Adding a control variate to the arithmetic asian MC heston pricer

- ql/CMakeLists.txt
Quite an unpretentious PR, but when I installed QuantLib 1.20 via CMake, I noticed that two `all.hpp` includes were missing.
This would, for example, be noticed when this installation target were used as `QL_DIR` during the build of Python bindings using `QuantLib-SWIG`.
> Added experimental/[asian|forward]/all.hpp to CMakeLists

- .clang-format
At the moment there is no clear indent policy for the preprocessor directives. I find it hard to read unindent preprocessors like
```cpp
#if FOO
#if BAR
#include <foo>
#endif
#endif
```
`.clang-format` supports automatic indent using `IndentPPDirectives: AfterHash`
```cpp
#if FOO
#endif
```
or `IndentPPDirectives: BeforeHash`
```cpp
#if FOO
#if BAR
#include <foo>
#endif
#endif
```
Personally I prefer `IndentPPDirectives: AfterHash` but the later is okay for me as well.
> Automatic indent of preprocessor directives

- ql/termstructures/yield/fittedbonddiscountcurve.cpp
- ql/termstructures/yield/fittedbonddiscountcurve.hpp
- test-suite/fittedbonddiscountcurve.cpp
Another member variable preferred to result struct, since FittingMethod basically serves the purpose of a result struct.
> Add errorCode_ member variable to FittingMethod.

- .github/workflows/linux.yml
- configure.ac
- ql/math/array.hpp
- ql/math/matrix.hpp
- ql/methods/finitedifferences/operators/ninepointlinearop.cpp
- ql/methods/finitedifferences/operators/ninepointlinearop.hpp
- ql/methods/finitedifferences/operators/triplebandlinearop.cpp
- ql/methods/finitedifferences/operators/triplebandlinearop.hpp
- ql/methods/finitedifferences/tridiagonaloperator.hpp
- ql/userconfig.hpp
- ql/utilities/disposable.hpp
- test-suite/array.cpp
It is now superseded by move constructors, and it gets in the way of RVO and NRVO.
It is still available as a configuration option (in case the change breaks client code), but the default is to alias it to its underlying type.
> Disable Disposable class template

- ql/cashflows/inflationcoupon.cpp
Make accrual negative during the ex-coupon trading period of an inflation coupon.
Template for handling ex-coupon trading matches accruedAmount  method found in  [fixedratecoupon.cpp](https://github.com/lballabio/QuantLib/blob/master/ql/cashflows/fixedratecoupon.cpp) and [floatingratecoupon.cpp](https://github.com/lballabio/QuantLib/blob/master/ql/cashflows/floatingratecoupon.cpp)
Issue reference: #1006
> Negative Accrual when trading ex-coupon for inflation coupon

- ql/instruments/makevanillaswap.cpp
Within our test framework we test against `MakeVanillaSwap(...).withNominal(0.00);`.
When we want to create a fair `VanillaSwap` we get `fairRate() == NaN` here
https://github.com/lballabio/QuantLib/blob/d237af5c6b81da618244ae550ce97a56050fe333/ql/instruments/makevanillaswap.cpp#L178
which goes back to
https://github.com/lballabio/QuantLib/blob/d237af5c6b81da618244ae550ce97a56050fe333/ql/instruments/vanillaswap.cpp#L199
where obviously `legBPS_[0] == 0.0` and the division by zero leads to `NaN`. I think `NaN` is VS C++, other compiler might treat `DivByZero` differently.
Therefore I have added `QL_REQUIRE(nominal_ != 0.0, "Cannot determine fair rate for zero nominal.");` before starting calculating the fair rate.
> Required nominal != 0.0 within MakeVanillaSwap when calculating the fair rate.

- ql/index.hpp
- ql/indexes/indexmanager.cpp
- ql/indexes/indexmanager.hpp
- test-suite/indexes.cpp
- test-suite/indexes.hpp
I have added to `ql/cashflows/floatingratecoupon.hpp`
```cpp
//! whether or not the coupon is already fixed
virtual bool isFixed() const;
```
to check if the coupon is fixed or not. Before and after the fixing date it is obvious and at the fixing date I am using the approach for the `InterestRateIndex::fixing(...)` here
https://github.com/lballabio/QuantLib/blob/a44b404a3361b625c068173a5c8e0bb9981ea374/ql/indexes/interestrateindex.cpp#L85
I was conservative by not using `c++11` features within the implementation:
```cpp
bool FloatingRateCoupon::isFixed() const {
Date fixingDate = this->fixingDate();
Date today = Settings::instance().evaluationDate();
/* We compare serialNumber() here in case QL_HIGH_RESOLUTION_DATE is defined
* to avoid comparing dateTimes(). */
if (today.serialNumber() …
```
> Index::hasHistoricalFixing(fixingDate)

- QuantLib.natvis
- QuantLib.vcxproj
- QuantLib.vcxproj.filters
As discussed in https://sourceforge.net/p/quantlib/mailman/message/37162962/ 
I see the embedded images were removed in the mailing list. That's a pity.
Anyway, the added Quantlib.natvis file enables better visualisation of QuantLib types in Visual Studio.
> Add visualization for a couple of QuantLib types in Visual Studio debugger

- .github/workflows/test-times.yml
- test-suite/americanoption.cpp
- test-suite/americanoption.hpp
- test-suite/asianoptions.cpp
- test-suite/asianoptions.hpp
- test-suite/brownianbridge.cpp
- test-suite/distributions.cpp
- test-suite/doublebarrieroption.cpp
- test-suite/doublebarrieroption.hpp
- test-suite/fdmlinearop.cpp
- test-suite/fdmlinearop.hpp
- test-suite/fdsabr.cpp
- test-suite/forwardoption.cpp
- test-suite/forwardoption.hpp
- test-suite/hestonmodel.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/lookbackoptions.cpp
- test-suite/lookbackoptions.hpp
- test-suite/marketmodel.cpp
- test-suite/markovfunctional.cpp
- test-suite/mclongstaffschwartzengine.cpp
- test-suite/mclongstaffschwartzengine.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/swaption.cpp
- test-suite/swaption.hpp
- tools/check_test_times.py
Part of #1015.
This also adds an automated check that monitors the execution times of test cases in the "Faster", "Fast" and "Slow" sections and advises if any should be moved.
> Reduce run time for longest-running test cases.

- acinclude.m4
- test-suite/CMakeLists.txt
- test-suite/paralleltestrunner.hpp
- test-suite/quantlibbenchmark.cpp
- test-suite/quantlibtestsuite.cpp
This removes a library dependency on Boost.Timer, Boost.System and Boost.Chrono
> C++11 modernization - replace Boost.Timer with std::chrono

- ql/instruments/asianoption.cpp
- ql/instruments/asianoption.hpp
- test-suite/asianoptions.cpp
Provide all fixings as an array (with default empty array for unseasoned options).
Two useful things:
1. Checks that the pastFixings and runningAccumulator arguments make sense (discussed in linked issue)
2. Provides a way of creating an asian by passing all past fixings in, and the pastFixings/runningAccumulator is calculated correctly for the averaging type. Passing in no variable here defaults to unseasoned (so you can create an unseasoned asian this way without having to pass in 0 and 1.0/0.0 as currently)
Closes #968
Closes #241
> New interface for seasoned Asian options

- ql/config.msvc.hpp
- ql/qldefines.hpp
VS 2019 produces a lot of warnings about unscoped enums.
As they will remain unscoped this avoids the warning.
> Suppress C++ code analysis warning C26812 in VS 2019 - Prefer enum class

- ql/cashflows/cpicouponpricer.cpp
- ql/cashflows/inflationcouponpricer.cpp
- ql/errors.hpp
- ql/experimental/credit/onefactoraffinesurvival.hpp
- ql/experimental/variancegamma/analyticvariancegammaengine.cpp
- ql/instruments/vanillaswingoption.cpp
- ql/math/optimization/constraint.hpp
- ql/math/randomnumbers/randomizedlds.hpp
- ql/methods/finitedifferences/operators/fdmbatesop.cpp
- ql/models/marketmodels/marketmodel.cpp
- ql/termstructures/iterativebootstrap.hpp
- ql/termstructures/volatility/smilesectionutils.cpp
At times, the old version of the macros could cause a misleading-intentation warning.
Also, switching to the new version helped find out a number of places in which the semicolon after the macro was missing. Luckily, this resulted in the same effective behavior.
> Avoid dangling else in error macros

- ql/termstructures/yield/ratehelpers.cpp
This is just to fix a typo in the `FuturesRateHelper` that came up on [this](https://quant.stackexchange.com/a/63695/50869) quant.stackexchange post.
I was going to add the logic in this constructor to a private method because it is identical to that of the `FuturesRateHelper(const Handle<Quote>& price, const Date& iborStartDate, const Date& iborEndDate, const DayCounter& dayCounter, Handle<Quote> convexityAdjustment = Handle<Quote>(), Futures::Type type = Futures::IMM);` constructor and could be shared. The same could be done for the other 2 constructor pairs i.e. giving 3 private methods. Not sure if it would be desirable though so left it as is for now.
> Fix typo in FuturesRateHelper.

- Examples/CDS/CDS.cpp
- Examples/ConvertibleBonds/ConvertibleBonds.cpp
- Examples/Gaussian1dModels/Gaussian1dModels.cpp
- ql/cashflows/cpicoupon.cpp
- ql/instruments/makeyoyinflationcapfloor.cpp
- ql/time/daycounters/simpledaycounter.cpp
- ql/time/daycounters/thirty360.cpp
- ql/time/daycounters/thirty360.hpp
- test-suite/assetswap.cpp
- test-suite/basismodels.cpp
- test-suite/bermudanswaption.cpp
- test-suite/bonds.cpp
- test-suite/callablebonds.cpp
- test-suite/capflooredcoupon.cpp
- test-suite/creditdefaultswap.cpp
- test-suite/defaultprobabilitycurves.cpp
- test-suite/inflation.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/markovfunctional.cpp
- test-suite/overnightindexedswap.cpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/rangeaccrual.cpp
- test-suite/shortratemodels.cpp
- test-suite/swap.cpp
- test-suite/swaption.cpp
- test-suite/termstructures.cpp
- test-suite/variancegamma.cpp
- Added ISMA convention (similar to NASD but doesn't adjust to next month);
- `BondBasis` is now, correctly, an alias to ISMA;
- `German` is now also called ISDA;
- reordered code to model logic more closely;
- deprecated default constructor; a convention should always be passed explicitly.
> A few changes to 30/360 day count convention

- ql/experimental/catbonds/catrisk.cpp
- ql/time/daycounters/actualactual.hpp
- test-suite/batesmodel.cpp
- test-suite/cdo.cpp
- test-suite/daycounters.cpp
- test-suite/gjrgarchmodel.cpp
- test-suite/hestonmodel.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpicapfloor.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/libormarketmodelprocess.cpp
- test-suite/normalclvmodel.cpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/quotes.cpp
- test-suite/squarerootclvmodel.cpp
- test-suite/swingoption.cpp
- test-suite/vpp.cpp
One should pass a convention explicitly.
> Deprecate default constructor for Actual/Actual day count convention

- ql/time/daycounters/thirty360.cpp
- ql/time/daycounters/thirty360.hpp
- test-suite/daycounters.cpp
- test-suite/daycounters.hpp
- Added constructor taking termination date used by ISDA convention;
- Fixed US convention; the old one is still available as NASD.
> More changes for 30/360 day count convention

- ql/pricingengines/credit/isdacdsengine.cpp
> Ensure curve bootstrap before implied hazard-rate calculation

- .github/workflows/linux-full-tests.yml
- .github/workflows/linux-nondefault.yml
- .github/workflows/linux.yml
- .github/workflows/macos-nondefault.yml
- .github/workflows/macos.yml
- acinclude.m4
- configure.ac
- quantlib-config.in
Fixes #1090.
It can be superseded by adding the desired `-std=` flag to `CXXFLAGS`.
> Add `-std=c++11` flag to autotools build when required

- ql/models/shortrate/onefactormodels/coxingersollross.hpp
- ql/models/shortrate/onefactormodels/extendedcoxingersollross.cpp
- ql/models/shortrate/onefactormodels/extendedcoxingersollross.hpp
- ql/processes/coxingersollrossprocess.hpp
Using the Quadratic Exponential scheme of Leif Andersen to avoid "explosions" in the short-rate when the square root process gets close to zero.
I have made a small program to showcase the issue. I have attached a plot of the terminal distribution of the discretized processes compared to the true distribution in the Cox-Ingersoll-Ross model. The plot on the left is of the approach that is in QuantLib today and the plot on the right is of my suggested code.
Run-time is given below:
`Simulate Square Root: Run time = 592.542 ms`
`Quadratic Exponential: Run time = 713.863 ms`
**Code**
```cpp
//
//  main.cpp
//  ImproveCir
//
//  Created by Magnus Mencke on 10/06/2021.
//  Copyright © 2021 Magnus Mencke. All rights reserved.
//
#include <iostream>
#include <fstream>
#include <ql/quantlib.hpp> …
```
> Improve CIR Discretization

- ql/time/calendars/unitedstates.cpp
- ql/time/calendars/unitedstates.hpp
Newly instituted in 2021 — exchanges will start observing it in 2022.
> Add Juneteenth to US calendars

- ql/models/shortrate/twofactormodels/g2.cpp
Related to issue #1087.
There has been some issues the lower bound becomes minus infinity as y=-100 is a very low value.
Instead of having the interval, where we solve for y-bar, hard-coded, it is now set to plus/minus 10 standard deviations.
> Fix Calibration Errors in G2

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/ibor/Makefile.am
- ql/indexes/ibor/all.hpp
- ql/indexes/ibor/estr.cpp
- ql/indexes/ibor/estr.hpp
Related to #868.
An ESTR index is created as a copy of Eonia. 
One thing I noticed was that the business day convention was hard-coded in `OvernightIndex` as `Following`, while according to [this link](https://www.ecb.europa.eu/pub/pdf/other/ecb.consultation_publication_compounded_term_rates_ESTR202007~0567eaeb98.en.pdf), the business day convention for ESTR is "modified previous". I am however not sure whether this makes any difference.
> Add ESTR Index

- ql/models/shortrate/twofactormodels/g2.cpp
The previous bounds (introduced in #1122) caused the Bermudan-swaption Python example to fail.
> Reintroduce wider search bounds for G2 calibration.

- ql/experimental/models/hestonslvfdmmodel.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/hestonslvmodel.hpp
This is a three-part pull request to fix a calibration issue for the HestonSLVFDMModel when a mixing factor other than 1.0 is used in the calibration.
1.  I've written a slow-running test and added to test-suite/hestonslvmodel.cpp that will fail in the current build, which I'll push first (it is expected to fail)
2. I'll push the fix, which will build and cause the test to pass
3. Unfortunately the test takes about 210s to run, so I will 'comment out' the test in the final push and add it to the other three commented-out very slow running tests in that test group
Here is how the leverage functions for the MC and FDM look during the current run (the FDM calibration is even getting vanillas wrong here):
And here is how they look once the fix is applied (note that prices match much more …
> Fixing calibration issue with HestonSLVFDMModel and adding a (slow!) test

- quantlib.pc.in
Now, for those using `pkg-config`, the commands
pkg-config quantlib --cflags
pkg-config quantlib --libs
give the same outputs as
quantlib-config --cflags
quantlib-config --libs
> Update `pkg-config` output

- ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
The parameter types and names do not match between declaration and definition.
Probably there is no test case so that the template is actually used and compiled.
Found this more by change working on [Avoids current warnings on MSVC ](https://github.com/lballabio/QuantLib-SWIG/pull/402)
> Fixed parameter types

- ql/instruments/swap.hpp
- ql/instruments/zerocouponinflationswap.hpp
- ql/instruments/zerocouponswap.hpp
As
https://github.com/lballabio/QuantLib/blob/9daedddf7c8aeca5d2b271039b9d8d4894a2364b/ql/instruments/swap.hpp#L79-L80
are overwritten in
https://github.com/lballabio/QuantLib/blob/9daedddf7c8aeca5d2b271039b9d8d4894a2364b/ql/instruments/zerocouponswap.hpp#L99-L100
and
https://github.com/lballabio/QuantLib/blob/9daedddf7c8aeca5d2b271039b9d8d4894a2364b/ql/instruments/zerocouponinflationswap.hpp#L112-L113
they should become `virtual`.
> Swaps startDate() and maturityDate() should be virtual

- LICENSE.TXT
- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/time/calendars/Makefile.am
- ql/time/calendars/all.hpp
- ql/time/calendars/chile.cpp
- ql/time/calendars/chile.hpp
- Added Chilean list of holidays based on issue #1102 
- Used the list of holidays for 2018-2024 available on [Chile Public Holidays](https://publicholidays.cl/)
- Most holidays were at the same date across years, except for 3-4 holidays
- There is no roll-over of holidays to the next working day if it falls on a weekend
This is my first PR. Let me know if you have any feedback!
> Add Chilean Calendar

- ql/time/dategenerationrule.cpp
- ql/time/dategenerationrule.hpp
- ql/time/schedule.cpp
- test-suite/swap.cpp
- test-suite/swap.hpp
Adjust start and end dates to ThirdWednesday as well to follow market practice.
Related Issue: MakeVanillaSwap should adjust the default dates for ThirdWednesday
#833
> Adjust effective and termination dates for ThirdWednesday Rule

- Examples/CDS/CDS.cpp
- ql/cashflows/iborcoupon.cpp
- ql/cashflows/iborcoupon.hpp
- ql/money.cpp
- ql/money.hpp
- ql/patterns/singleton.hpp
- ql/pricingengines/credit/isdacdsengine.hpp
- ql/userconfig.hpp
- test-suite/assetswap.cpp
- test-suite/basismodels.cpp
- test-suite/bermudanswaption.cpp
- test-suite/bonds.cpp
- test-suite/capfloor.cpp
- test-suite/cashflows.cpp
- test-suite/catbonds.cpp
- test-suite/creditdefaultswap.cpp
- test-suite/exchangerate.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/libormarketmodel.cpp
- test-suite/money.cpp
- test-suite/optionletstripper.cpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/shortratemodels.cpp
- test-suite/swap.cpp
- test-suite/swaption.cpp
Here's a fix for #1146.  I added both `IborCoupon::Settings` and `Money::Settings` as nested classes per @ralfkonrad's  suggestion.   I deprecated the original static methods -- which still work -- they simply use the new singletons.   The test suite and example code changes are simply to use the new apis.   The `Money` class unfortunately did not use static methods, but static vars instead (ouch), so I did the best that I could with that.
I tested locally with `QL_USE_INDEXED_COUPON` off and then on. 
Phil
> Fix IborCoupon and Money data races

- ql/experimental/exoticoptions/analyticholderextensibleoptionengine.cpp
- ql/math/matrixutilities/svd.cpp
- ql/pricingengines/asian/mc_discr_geom_av_price.cpp
- ql/pricingengines/asian/mc_discr_geom_av_price_heston.cpp
- ql/qldefines.hpp
- ql/qldefines.hpp.cfg
- ql/termstructures/volatility/equityfx/hestonblackvolsurface.cpp
- test-suite/array.cpp
- test-suite/cmsspread.cpp
- test-suite/interpolations.cpp
- test-suite/numericaldifferentiation.cpp
- test-suite/ode.cpp
`constexpr` is not supported in Visual Studio 2013, hence the need for a macro.
> Add `QL_CONSTEXPR` macro and avoid some MSVC warnings

- .gitignore
- CMakeLists.txt
Closes #1225 
* Only depend on `thread` when not bulding test suite or benchmarks
* Require version 1.75.0 or higher of boost when building with C++20 (otherwise ublas will be incompatible)
* Allow overriding the boost version and the required components via a CMake property
* Added `Boost_NO_WARN_NEW_VERSIONS` to avoid warnings about newer Boost versions
* Fix typo in `.gitignore`
> Remove dependency on Boost Test when not needed

- ql/experimental/inflation/cpicapfloortermpricesurface.cpp
- ql/experimental/inflation/cpicapfloortermpricesurface.hpp
- ql/experimental/inflation/yoycapfloortermpricesurface.cpp
- ql/experimental/inflation/yoycapfloortermpricesurface.hpp
- ql/indexes/inflationindex.cpp
- ql/indexes/inflationindex.hpp
- ql/termstructures/inflation/inflationtraits.hpp
- ql/termstructures/inflation/interpolatedzeroinflationcurve.hpp
- ql/termstructures/inflation/piecewisezeroinflationcurve.hpp
- ql/termstructures/inflation/seasonality.cpp
- ql/termstructures/inflationtermstructure.cpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpicapfloor.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/inflationzciisinterpolation.cpp
Part of the road to #1050.
After this change, the interpolation of future index fixings is performed in `ZeroInflationIndex` itself and no longer delegated to the inflation curve.
In turn, this allows simplification of the curve code, since now calls to its methods done through the index only ask for rates at the start of inflation periods; this effectively reduces the curve behavior to the case in which `indexIsInterpolated` is false, allowing to remove the other branch.  Furthermore, the `indexIsInterpolated` method and constructor parameter were deprecated.
For coupons that already took care of interpolation (as in the case of `CPICoupon` and `ZeroInflationCashFlow` when `observationInterpolation` was `Flat` or `Linear`) this should not change the results.  In other cases, figures will …
> Do not rely on inflation curves for index interpolation

- CMakeLists.txt
- Makefile.am
- cmake/QuantLibConfig.cmake.in
- ql/CMakeLists.txt
- tools/check_filelists.sh
Closes #1221 
Added CMake scripts to make QuantLib a config-file package[1].
I followed the documentation in [1] as closely as possible to provide a basic implementation of this feature, but I still found it quite complicated so there may be some small details that could be implemented better.
The change to `ql/CMakeLists.txt` line 2331 is required to fix the issue described in [2], but I wonder, why do we need to add both `${CMAKE_BINARY_DIR}` and `${CMAKE_SOURCE_DIR}` to the include directories? Shouldn't it be one or the other? 
Also, minor note that I set the version compatibility to `AnyNewerVersion`, which basically means that QuantLib will be either backwards compatible or that users are on the hook to fix compilation errors (e.g. due to removed deprecated code) when the version of …
> Add CMake config scripts

- Examples/FRA/FRA.cpp
- ql/instruments/forwardrateagreement.cpp
- ql/instruments/forwardrateagreement.hpp
As a starter for issue #1216 , I have removed the inheritance of Forward class by ForwardRateAgreement to inherit from Instrument class directly. I have also duplicated all the non-overriden methods in Forward class for now, until we figure out which methods can be removed/depercated.
> Remove Forward inheritance by ForwardRateAgreement

- ql/termstructures/yield/overnightindexfutureratehelper.cpp
- ql/termstructures/yield/overnightindexfutureratehelper.hpp
- test-suite/sofrfutures.cpp
Futures with monthly frequency use averaging rate, while with quarterly frequency use compouding. The constructor taking the averaging method explicitly can be deprecated.
> Remove redundant arguments from `SofrFutureRateHelper` constructor

- ql/instruments/overnightindexedswap.hpp
There are three inspectors on OvernightIndexedSwap which are not const, and which i think could be:
```
Frequency paymentFrequency() { return paymentFrequency_; }
const DayCounter& fixedDayCount() { return fixedDC_; }
const ext::shared_ptr<OvernightIndex>& overnightIndex() { return overnightIndex_; }
```
This trivial PR does that.
> Make some inspectors on OvernightIndexedSwap const

- test-suite/dividendoption.cpp
The Hull example this test replicates uses t=0.5. Since this test uses the Act/360 calendar with beginning date today, we need to increment time by days, rather than months, because today+n*Months gives a different value of duration depending on what day the test is run. And this difference is often large enough to break our error tolerance.
> Fix testEuropeanKnownValue test

- ql/instruments/overnightindexfuture.hpp
It's useful to be able to read these off an individual future, and i don't know of any reason they should be private.
> Add inspectors for some basic properties of overnight-idex futures

- ql/models/marketmodels/historicalforwardratesanalysis.hpp
The deprecated PiecewiseYieldCurve constructor that accepted the accuracy was recently removed. This instantiation has to be fixed.
Unfortunately I don't know much about this class so cannot contribute a test case.
> Update obsolete call to `PiecewiseYieldCurve` constructor

- ql/termstructures/yield/oisratehelper.cpp
`deepUpdate` would work by chance because it would cause a notification to reach the instrument. Instead, `recalculate` is the one that expresses the intent directly.
> Use correct method to recalculate swap in OIS helper

- .github/workflows/linux-full-tests.yml
- .github/workflows/sanitizer.yml
- ql/pricingengines/lookback/analyticcontinuouspartialfloatinglookback.cpp
- test-suite/inflationzciisinterpolation.cpp
Closes #1251
- Compile with AddressSanitizer enabled in `linux-full-tests.yml`
- Fix indirect leaks in `inflationzciisinterpolation.cpp`
- Fix minor compiler warning in `analyticcontinuouspartialfloatinglookback.cpp`
> Indirect leaks with AddressSanitizer

- ql/cashflows/cpicoupon.cpp
this is the draft of the code change
> Return `CPICashFlow` base date if available

- ql/indexes/ibor/thbfix.hpp
The THBFIX rate observes only the Thailand calendar (they are published also on LIBOR holidays) from the BoT [historical data](https://www.bot.or.th/App/BTWS_STAT/statistics/BOTWEBSTAT.aspx?reportID=909&language=eng). e.g. there were fixing on 27&28 Dec 2021.
Believe it should be changed accordingly in order that derivatives based on it correctly impute their fixing days.
> change THBFIX fixing calendar

- ql/cashflows/cpicouponpricer.hpp
This allows passing a vol surface without a discount curve (which is only needed for `Price()` methods).
> Rework defaults for `CPICoupon` constructors.

- CMakeLists.txt
As discussed on the [quantlib-users](https://sourceforge.net/p/quantlib/mailman/message/37593432/) mailing list, in the default configuration no pre-compiled Boost libraries are needed, so updating the required components for the CMake build accordingly.
> Set QL_BOOST_COMPONENTS to empty string by default

- cmake/Platform.cmake
- ql/experimental/finitedifferences/fdmhestonfwdop.cpp
- ql/models/shortrate/onefactormodels/gaussian1dmodel.hpp
- ql/patterns/observable.hpp
- ql/time/date.hpp
- test-suite/dates.cpp
Closes #1270 
- Replace `boost::unordered_map` and `boost::unordered_set` with the `std` equivalents.
- Deprecate unused (within QuantLib) public typedefs.
- Remove unnecessary warning suppression on Linux.
- Add harmless warning suppression on Windows.
> Replace boost::unordered_{map,set} with std::unordered_{map,set}

- ql/experimental/volatility/sabrvolsurface.cpp
- ql/experimental/volatility/sabrvolsurface.hpp
`boost::array` is another type that can be replaced by the C++11 standard library.
It is not used in public scope anywhere, and only once in protected scope. What is the policy on making breaking changes to protected scope - is it allowed? If not, then what are the options for making this change?
If we are going to replace more boost types with the standard library, then I suppose at some point we will need to introduce a macro such as `QL_USE_STD` defaulted to `false` to specify whether to use the boost type or the std type. That way we can deprecate the boost types while allowing people to opt in early to the std types. What do you think?
> Replace boost::array with std::array

- ql/money.cpp
- ql/termstructures/credit/piecewisedefaultcurve.hpp
we are using `-Werror=suggest-override` which fails with current QuantLib because
- boost/format.hpp seems to be incorrectly implemented (this is with boost 1.76)
- we need to suppress this warning in piecewisedefaultcurve.hpp for clang and gcc (already done for "inconsistent override" and clang)
> allow to build with -Wsuggest-override (clang, gcc)

- ql/CMakeLists.txt
- test-suite/CMakeLists.txt
In ORE we build QuantLib as a cmake subproject. This is no longer possible after the overhaul of the cmake build because of wrong path references. As far as I can see this can be fixed without affecting the "normal" build by replacing
```
CMAKE_SOURCE_DIR -> PROJECT_SOURCE_DIR
CMAKE_BINARY_DIR -> PROJECT_BINARY_DIR 
```
In addition I gave the test suite a more specific name for a similar reason, i.e. to make it recognisable when running under `ctest` together with a bunch of other tests.
> allow to include QuantLib as cmake subproject

- ql/cashflows/cmscoupon.cpp
- ql/cashflows/floatingratecoupon.cpp
- ql/cashflows/iborcoupon.cpp
- ql/cashflows/indexedcashflow.cpp
- ql/cashflows/indexedcashflow.hpp
- ql/cashflows/overnightindexedcoupon.cpp
- ql/cashflows/subperiodcoupon.cpp
- ql/experimental/coupons/cmsspreadcoupon.cpp
- ql/experimental/processes/extouwithjumpsprocess.cpp
- ql/experimental/processes/klugeextouprocess.cpp
- ql/instruments/compositeinstrument.cpp
- ql/pricingengines/swaption/fdg2swaptionengine.cpp
- ql/pricingengines/swaption/fdhullwhiteswaptionengine.cpp
- ql/pricingengines/swaption/g2swaptionengine.hpp
- ql/pricingengines/swaption/jamshidianswaptionengine.cpp
- ql/pricingengines/vanilla/analyticbsmhullwhiteengine.cpp
- ql/processes/stochasticprocessarray.cpp
This allows to return error messages a bit more useful than "assertion failed: px != 0".  When using `std::shared_ptr`, it avoids null-pointer access.
Many more are needed.
> Add some null-pointer checks

- ql/time/period.cpp
It used to be fancy and print "1 years 4 months" for a period of 16 months.  Now it displays transparently what the units and length are.
> Simpler output for periods.

- ql/time/period.cpp
- ql/time/period.hpp
- test-suite/period.cpp
- test-suite/period.hpp
This is needed so that periods comparing as equal can be given (through the normalized string representation) the same hash when used as dictionary keys in languages such as Python or C#.
> Normalize equal periods to the same value.

- .clang-tidy
* Split each check into a separate line to improve readability
* Add `-readability-simplify-boolean-expr` and `-readability-use-anyofallof`
* Remove `AnalyzeTemporaryDtors`, unused since clang-tidy 6
I think a lot of the suppressed checks should eventually be removed from .clang-tidy and either fixed in the code or suppressed in the code on a case by case basis using `// NOLINT`. This can be done in a future merge request - for now I have just keep the existing lists of checks (and added two new ones that I observed when building locally).
> Reformat .clang-tidy

- ql/math/functional.hpp
This fixes the compilation error mentioned in #1339. I will submit a separate pull request later with more changes to deprecate obsolete types and typedefs after this is merged. 
The _MSVC_LANG is needed because __cplusplus does not resolve correctly with MSVC without a special compiler option. See [here](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) for more details.
> Fix C++20 compilation error

- ql/experimental/volatility/svismilesection.cpp
- ql/experimental/volatility/svismilesection.hpp
Hi!
I recently added some docstrings to the `SviSmileSection` ctors, mostly for my own understanding, but I thought they might help others too. I also noticed that the error message incorrectly included a 6th argument (the 's') and that the return type in the definition of `volImpl()` didn't entirely match it's declaration, both of which I adjusted. 
Best,
Fredrik
SEB
> Documenting the SviSmileSection

- .clang-tidy
This macro should no longer be used in clang-tidy.
> Don't use the deprecated `QL_NOEXCEPT` macro when tidying

- ql/experimental/math/fireflyalgorithm.hpp
- ql/experimental/math/hybridsimulatedannealingfunctors.hpp
- ql/experimental/math/particleswarmoptimization.hpp
- test-suite/overnightindexedswap.cpp
- test-suite/riskstats.cpp
Currently these typedefs are in the global namespace, which may conflict with other libraries, so I have either moved them into the QuantLib namespace or removed them if they were only used in one place.
Since all the modified classes are in `ql/experimental` or `test-suite`, I believe that the typedefs do not need to be deprecated before being moved.
> Move global typedefs into namespace

- ql/experimental/credit/integralntdengine.cpp
- ql/qldefines.hpp
- ql/timeseries.hpp
- ql/utilities/dataformatters.hpp
- ql/utilities/null.hpp
Also, use a couple of C++11 std headers instead of Boost and deprecate a couple of unnecessary macros.
> Add `constexpr` constructor and conversion operator for nulls

- ql/experimental/catbonds/catrisk.cpp
- ql/experimental/catbonds/catrisk.hpp
- ql/experimental/math/fireflyalgorithm.cpp
- ql/experimental/math/fireflyalgorithm.hpp
- ql/experimental/math/hybridsimulatedannealingfunctors.hpp
- ql/experimental/math/isotropicrandomwalk.hpp
- ql/experimental/math/levyflightdistribution.hpp
- ql/experimental/math/particleswarmoptimization.cpp
- ql/experimental/math/particleswarmoptimization.hpp
- test-suite/catbonds.cpp
As discussed in [issue 1305](https://github.com/lballabio/QuantLib/issues/1305#issuecomment-1057757137) with @pcaspers, it would be good to try and replace Boost.Random with the C++11 standard library equivalents, in the spirit of leveraging the standard library wherever possible.
For the most part it was a straightforward replacement, with the following caveats:
* `boost::variate_generator` didn't make it into the standard so I have replaced instances of it with the underlying engine and generator. This actually made the code cleaner because it allowed for removing some redundant copy constructors.
* `test-suite/catbonds.cpp` fails with libc++ (i.e. on MacOS or with linking against libc++ on Linux) so I have increased the tolerance for now. This deserves more investigation.
* I have …
> Replace Boost.Random with std `<random>`

- ql/patterns/singleton.hpp
We use thread-local singletons in "worker" threads whose lifetime ends before the "master" threads ends. We want to be able to remove the associated singletons before such a thread ends.
> Add `remove` method to thread-local singleton

- ql/time/calendars/australia.cpp
> update australia calendar

- CMakeLists.txt
- Examples/BasketLosses/CMakeLists.txt
- Examples/BermudanSwaption/CMakeLists.txt
- Examples/Bonds/CMakeLists.txt
- Examples/CDS/CMakeLists.txt
- Examples/CMakeLists.txt
- Examples/CVAIRS/CMakeLists.txt
- Examples/CallableBonds/CMakeLists.txt
- Examples/ConvertibleBonds/CMakeLists.txt
- Examples/DiscreteHedging/CMakeLists.txt
- Examples/EquityOption/CMakeLists.txt
- Examples/FRA/CMakeLists.txt
- Examples/FittedBondCurve/CMakeLists.txt
- Examples/Gaussian1dModels/CMakeLists.txt
- Examples/GlobalOptimizer/CMakeLists.txt
- Examples/LatentModel/CMakeLists.txt
- Examples/MarketModels/CMakeLists.txt
- Examples/MulticurveBootstrapping/CMakeLists.txt
- Examples/MultidimIntegral/CMakeLists.txt
- Examples/Replication/CMakeLists.txt
- Examples/Repo/CMakeLists.txt
- acinclude.m4
- configure.ac
- test-suite/CMakeLists.txt
- test-suite/paralleltestrunner.hpp
- Use `std::thread` instead of `boost::thread` in `paralleltestrunner.hpp`.
- Replace `QL_EXAMPLES_LIBRARIES`, `QL_BENCHMARK_LIBRARIES`, and `QL_TEST_SUITE_LIBRARIES` with `QL_THREAD_LIBRARIES` and remove some redundant CMake option checks.
- Add direct dependency on underlying threading library (`pthread` on Linux and `Threads` with CMake) instead of inheriting it through Boost.Thread.
One thing I'm not sure about is whether the parallel test runner was used on Windows outside of CMake. If so, that will need to be updated as well, but I'm not sure how.
Also I plan to migrate the rest of Boost.Thread to std `<thread>` in a future pull request.
> Use std `<thread>` for parallel test runner

- .clang-tidy
- CMakePresets.json
- ql/termstructures/credit/piecewisedefaultcurve.hpp
- tools/run_tidy.sh
Continuation of #1338 
- Move checks with fixes to new `.clang-tidy-fixes` file and use that file in the CI job.
- Add new `linux-gcc-debug-with-clang-tidy` to illustrate how to develop with all clang-tidy checks enabled.
- Add new checks from `clang-analyzer` and `cppcoreguidelines` and disable ones that currently fail - most of these can and should be addressed in a separate merge request.
- Remove unused `run_tidy.sh` script.
> Split `.clang-tidy` into one for fixes and one for checks

- ql/experimental/volatility/sviinterpolation.hpp
- ql/experimental/volatility/svismilesection.cpp
- ql/experimental/volatility/svismilesection.hpp
- test-suite/CMakeLists.txt
- test-suite/Makefile.am
- test-suite/quantlibtestsuite.cpp
- test-suite/svivolatility.cpp
- test-suite/svivolatility.hpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
Hi all,
When running SVI data through the `SviSmileSection` class, I came across an issue with the last condition in `checkSviParameters()`. Looking at the original reference, [Gatheral (2004)](http://faculty.baruch.cuny.edu/jgatheral/madrid2004.pdf), I believe the condition should indeed be `b* (1 + |rho|) <= 4.0 / T`, not `... < 4.0`. 
I added an initial test case for the construction of the class using a set of simplified parameters. This to help ensure that the variance returned is as expected and that the parameter check doesn't incorrectly fail "legal" parameters.
Best,
Fredrik
> Correct SVI parameter check to account for expiry

- .clang-tidy
- ql/experimental/volatility/noarbsabrinterpolation.hpp
- ql/experimental/volatility/sviinterpolation.hpp
- ql/experimental/volatility/zabrinterpolation.hpp
- ql/math/interpolations/abcdinterpolation.hpp
- ql/math/interpolations/cubicinterpolation.hpp
- ql/math/interpolations/sabrinterpolation.hpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/piecewiseyieldcurve.hpp
I understand from the following two mail threads that slicing of interpolators is a known issue, and not really a problem in terms of application behavior, but suppressing `cppcoreguidelines-slicing` for the entire project (like any other project-wide suppression) might hide genuine issues.
https://sourceforge.net/p/quantlib/mailman/message/18673477/
https://sourceforge.net/p/quantlib/mailman/message/23586410/
The solution I've come up with is to remove the subclass member variables and just dynamically cast the `impl_` object whenever required.
Of course this approach is much slower than casting only once in the constructor, but I believe that following the core guidelines outweighs the performance implications in this case.
Plus, this is what …
> Remove suppression for cppcoreguidelines-slicing

- ql/experimental/models/hestonslvfdmmodel.cpp
- ql/math/array.hpp
- ql/math/integrals/filonintegral.cpp
- ql/math/sampledcurve.hpp
- ql/math/transformedgrid.hpp
- ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp
- test-suite/gaussianquadratures.cpp
- test-suite/integrals.cpp
- test-suite/numericaldifferentiation.cpp
- test-suite/swingoption.cpp
Various places in the code use `static_cast<Real(*)(Real)>(std::exp)` and similar code to create a function object. This PR replaces this with lambdas, which has the following advantages:
- more readable / natural / modern
- more generic, as overload resolution and template / inline functions can be captured as well
> Using lambdas instead of function pointers

- ql/math/array.hpp
- ql/prices.hpp
- ql/time/date.hpp
- ql/utilities/null.hpp
The approach of using a `Null<T>` class relies on implicit conversion operators to make expressions work as 
```c++
Real x = Null<Real>();
```
It creates a an object of class `Null<Real>` and immediately converts it back to `Real` using the implicit conversion operator. Relying on implicit conversions is not considered good practice, and it creates problems if `Real` itself is a class with its own implicit conversion operators, as double-implicit conversions are not allowed. 
This PR uses a different approach which is more generic and does not have the above problems. A template function is used instead (with the same name as the previous class to ensure no change for the user):
```c++
template <class T>
T Null() { ...}
Real x = Null<Real>();
```
This function template can be specialised …
> Refactored Null<T> class to a template function

- ql/termstructures/volatility/capfloor/capfloortermvolcurve.hpp
- ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp
This code appears to predate C++11 and so can be modernized using the `delete` keyword.
Types inheriting from `boost::noncopyable` are also non-movable so the move operators should be deleted as well, and the default destructor should be added to conform with the Rule of Five.
> Replace boost::noncopyable with deleted special member functions

- ql/time/calendars/australia.cpp
- ql/time/calendars/australia.hpp
Hi,
This was mentioned as an issue in #1374 and #1365. See the comments there for references on the change.
Best,
Fredrik
> Correct New Year's Day holiday for Australia

- ql/experimental/barrieroption/analyticdoublebarrierengine.cpp
- ql/experimental/barrieroption/mcdoublebarrierengine.hpp
- ql/experimental/barrieroption/suowangdoublebarrierengine.cpp
- ql/experimental/exoticoptions/analyticcompoundoptionengine.cpp
- ql/experimental/exoticoptions/analyticpartialtimebarrieroptionengine.cpp
- ql/experimental/exoticoptions/analytictwoassetbarrierengine.cpp
- ql/experimental/exoticoptions/analytictwoassetcorrelationengine.cpp
- ql/instruments/dividendbarrieroption.cpp
- ql/instruments/dividendbarrieroption.hpp
- ql/pricingengines/barrier/analyticbarrierengine.cpp
- ql/pricingengines/barrier/binomialbarrierengine.hpp
- ql/pricingengines/barrier/fdblackscholesbarrierengine.cpp
- ql/pricingengines/barrier/mcbarrierengine.hpp
- ql/pricingengines/forward/forwardengine.hpp
- ql/pricingengines/lookback/mclookbackengine.hpp
- test-suite/barrieroption.cpp
Closes #1411 
- Validate that the barrier option is not already triggered at the start of calculating in `BinomialBarrierEngine` and `FdBlackScholesBarrierEngine`.
- Add missing validation for European exercise in `AnalyticBarrierEngine` (I confirmed that the unit test fails with American exercise as mentioned in the comments).
- Make validation on spot level consistently greater than zero across all pricing engines (it was already the case for most pricing engines).
- Add test cases for zero spot price and already triggered barriers to the barrier option unit test suite.
While making this change I noticed that the `triggered` function is copy-and-pasted in a few different places, and should probably be centralized in one place in a future pull request.
> Add more validations to barrier options

- ql/pricingengines/asian/turnbullwakemanasianengine.cpp
- test-suite/asianoptions.cpp
Following a mailing list request for spot delta and gamma to be enabled for the Turnbull-Wakeman asian engines within SWIG.
Once enabled in QL, these will be enabled by default in SWIG too (eg. see snapshot below).
Tested by comparing numerical bump greeks to the analytical greeks for all current tests.
> Add spot delta and gamma for Turnbull-Wakeman engine

- .clang-tidy
- .github/workflows/linux-full-tests.yml
- .github/workflows/linux-nondefault.yml
- .github/workflows/linux.yml
- CMakeLists.txt
- acinclude.m4
- configure.ac
- quantlib-config.in
- quantlib.pc.in
Closes #1306 
- Removed C++11 builds
- Removed GCC 4.8 that predates C++14
- Added `-modernize-avoid-bind` to .clang-tidy to prevent compilation error after automatic fix was applied (this can be removed from .clang-tidy once the code in question is refactored in a more C++14 friendly way)
Note that I did not yet update the minimum Visual Studio version from 2013 to 2015. I can do that as part of this pull request, or as a separate one.
I may have missed a few places that are still implicitly relying on C++11, so a full review would be most welcome.
> Make minimum language version C++14

- .github/workflows/sanitizer.yml
- ql/cashflows/cmscoupon.cpp
- ql/models/marketmodels/products/multistep/callspecifiedmultiproduct.cpp
- ql/models/marketmodels/products/pathwise/pathwiseproductcallspecified.cpp
Add [UndefinedBehaviorSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) (a.k.a. UBSan) to the Linux CI job in addition to AddressSanitizer, which has already been added.
Also fix a couple uninitialized member variables that UBSan flagged. I am not sure if these are the correct default values to use, but they are at least better than uninitialized values. Even better would be if the classes could be refactored to always take in the value to initialize the variables with, but I will leave that to a future refactoring.
In case you're curious, `-fno-sanitize-recover=all` is required because some UBSan checks are recoverable and do not terminate the process, but we want any violations to result in the CI failing.
> Add UndefinedBehaviorSanitizer to Linux CI

- ql/math/randomnumbers/sobolrsg.hpp
- ql/time/date.hpp
- test-suite/lowdiscrepancysequences.cpp
From [the Boost docs](https://www.boost.org/doc/libs/1_79_0/libs/config/doc/html/boost_config/cstdint.html), apparently last updated in 2007:
> Should some future C++ standard include <stdint.h> and <cstdint>, then <boost/cstdint.hpp> will continue to function, but will become redundant and may be safely deprecated.
Indeed [`<cstdint>`](https://en.cppreference.com/w/cpp/header/cstdint) was introduced in C++11 so these Boost versions are no longer necessary.
Both `boost::uint_least32_t` and `std::uint_least32_t` are typedefs for `unsigned int` on my platform, and while I haven't checked other platforms, the boost docs above suggest that these should always be typedef'd to the same underlying type. So even though this affects a public interface, it should be transparent to users.
> Replace boost/cstdint.hpp with cstdint

- test-suite/callablebonds.cpp
- test-suite/fdcev.cpp
- test-suite/fdsabr.cpp
`<boost/make_shared.hpp>` should not be included directly, but rather through `<ql/shared_ptr.hpp>`.
> Use ql/shared_ptr.hpp header

- ql/math/interpolations/mixedinterpolation.hpp
solves the linker issue is with references to "static consts" without creating a cpp file, by creating refs locally
For detailed description, see https://stackoverflow.com/questions/16957458/static-const-in-c-class-undefined-reference for details
> Fixed link error due to using refs to static const

- .clang-tidy
- ql/experimental/math/multidimintegrator.hpp
- ql/math/optimization/levenbergmarquardt.cpp
- ql/termstructures/volatility/equityfx/gridmodellocalvolsurface.cpp
- test-suite/linearleastsquaresregression.cpp
This suppression was temporarily added back in #1324 and is now being removed.
A few things to note:
* I have also removed `ext::cref` from a few places because capturing the variables by reference into the lambda should be sufficient. These can be added back if I'm missing some subtle reason why they need to be there.
* I have removed `ext::bind` and `ext::placeholders` instead of deprecating them because they were not part of any public interface.
* I needed to add `this->` inside the lambdas because GCC 5 and 6 complained without it.
> Remove suppression for modernize-avoid-bind

- ql/termstructures/credit/hazardratestructure.cpp
- ql/termstructures/credit/hazardratestructure.hpp
- ql/termstructures/credit/piecewisedefaultcurve.hpp
- ql/termstructures/defaulttermstructure.hpp
There is this awkward situation that `PiecewiseDefaultCurve::hazardRateImpl()` only makes sense when `base_curve` derives from `HazardRateStructure`. This is cleaned up here by moving this method to the base class `DefaultTermStructure`. Everything should be backwards compatible.
This way we can get rid of the messy diagnostic pragmas in `PiecewiseDefaultCurve` too - which more or less already indicated that the design was skewed here.
> move `HazardRateStructure::hazardRateImpl()` to base class

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/time/daycounters/Makefile.am
- ql/time/daycounters/actual36525.hpp
- ql/time/daycounters/actual366.hpp
- ql/time/daycounters/all.hpp
- test-suite/daycounters.cpp
- test-suite/daycounters.hpp
Hi, 
This is my first contribution to QuantLib . I have been seeing recently some products with some day count convention that QuantLib does not currently have. I need to be able to price these products so I thought it would be also useful for other users of this library to have these day counters available. 
These conventions are ACT/366 and ACT/365.25, since they are very similar to the already existing ACT/364 I have used that  implementation as a base for these two new day counters.
I have added tests as well to the test suite for these two new day counters, compile it and test it without any issues.
> Adding ACT/366 & ACT/365.25

- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
The ISDA curves published by Markit published by Markit do not use end of month=true (see parameters [here](https://rfr.ihsmarkit.com/isda/document/RFR%20Interest%20Rate%20Curve%20Specification%20-%206%20Currencies%20(April%207,%202021).pdf).) Therefore we can't match CDS upfront calculations unless we can override the default.
>  allow to specify endOfMonth for OISRateHelper

- ql/pricingengines/vanilla/coshestonengine.cpp
- test-suite/hestonmodel.cpp
- test-suite/hestonmodel.hpp
Hi,
This PR is for fixing the issue #1468 . The COS method works weird when the options (specially puts) are OTM with a short expiry.
This is due to the fact that the resulting x log(Strike/forward) gets too big for the truncation, thus yielding incorrect results. There are three main ways to solve that:
* The first one is to return the upper/lower bound of the option if the x exceeds the truncation bounds,which the following paper recommends to be: a/2 and b/2. Doc: https://arxiv.org/pdf/2005.13248.pdf
* The second possible alternative is to raise an exception when something like this happens and ask the user to change the value of L.
* The third alternative is to change the pricing formula and implement the one that the previous document includes.
Since we already have a working formula …
> Fixing outside truncation calculation

- ql/experimental/inflation/cpicapfloorengines.cpp
- ql/instruments/cpicapfloor.cpp
- ql/instruments/cpicapfloor.hpp
- test-suite/inflationcpicapfloor.cpp
It doesn't make sense to change the index once the instrument is defined.
> Avoid passing `Handle<ZeroInflationIndex>` to CPI cap/floor

- ql/methods/finitedifferences/utilities/localvolrndcalculator.cpp
Computing cdf boundaries was wrong. In case xl is positive, while loop lowers xl but only to 0, if it is negative xl (through while loop) rise towards 0. In case xr is positive previous code is good as it tends towards +infinity. However, if xr is negative it tends towards -infinity.
xl should always tends towards -infinity and xr towards +infinity (up to a tolerance)
Maybe this can be done in better way, however this should work
> Computation of cdf in LocalVolRNDCalculator

- ql/experimental/callablebonds/blackcallablebondengine.cpp
- ql/experimental/callablebonds/callablebond.cpp
- ql/experimental/callablebonds/callablebond.hpp
- ql/experimental/callablebonds/discretizedcallablefixedratebond.cpp
- test-suite/callablebonds.cpp
- test-suite/callablebonds.hpp
- neither the tree nor the Black engine rescaled the callability premia to the face amount of the bond.  The calculation worked when the face amount was 100, but was incorrect otherwise.  This is now fixed.
- the `impliedVolatility` method was taking a target NPV, not a price, which means that the passed target needed to be scaled according to the face amount.  This implementation is now deprecated, and a new overload was added always taking a price in base 100.
These changes are possibly breaking: the public interface of the bond is still the same (plus the new overload) but the protected constructor had to change and a few protected data members were removed, so if you inherited from this class you might have to make corresponding changes.
> A few fixes for callable bonds

- ql/instruments/bonds/cmsratebond.hpp
- ql/instruments/bonds/fixedratebond.hpp
- ql/instruments/bonds/floatingratebond.hpp
- test-suite/bonds.cpp
The idea is to have a single, most used constructor for each kind of bond and to use the generic constructors in the Bond class for special cases.  This makes it a lot more convenient to use the constructors in languages (like Python or C#) that support some kind of syntax for keyword arguments.
> Deprecate a few bond constructors.

- CMakeLists.txt
- Examples/Makefile.am
- acinclude.m4
- configure.ac
- ql/CMakeLists.txt
- ql/auto_link.hpp
- ql/patterns/observable.cpp
- ql/patterns/observable.hpp
- ql/patterns/singleton.hpp
- quantlib-config.in
- quantlib.pc.in
- test-suite/Makefile.am
- test-suite/observable.cpp
- This removes the last Boost link-time dependency and so I have removed the `--with-boost-lib` flag. If you prefer, we can add it back and print a warning that it has no effect.
- There will be conflicts with #1377 but those conflicts can be easily resolved.
- `std::shared_timed_mutex` is the correct replacement for `boost::shared_mutex` because it was renamed at the last minute. See [this post](https://stackoverflow.com/a/40207246) for more info. Perhaps `std::shared_timed_mutex` can be replaced with `std::shared_mutex` in QuantLib once the language version changes to C++17.
> Replace boost::thread with std::thread

- ql/instruments/creditdefaultswap.cpp
- ql/instruments/makecds.cpp
- ql/instruments/makecds.hpp
- ql/pricingengines/credit/isdacdsengine.cpp
- test-suite/creditdefaultswap.cpp
- test-suite/creditdefaultswap.hpp
The fair upfront was calculated with the correct amount but the wrong sign when buying protection — or at least, a sign inconsistent with the behavior of the existing instrument and engines, which treat the upfront as positive when paid by the buyer of the protection.  Because of this, a CDS created with the returned fair upfront would not have null NPV.  This is now fixed.
Also, the `MakeCreditDefaultSwap` class can now take the trade date (instead of always assuming the current evaluation date, which remains the default) and the calculation of the accrual rebate was refactored for clarity.
> Fix sign of fair upfront in ISDA engine for CDS

- ql/termstructures/volatility/sabrsmilesection.cpp
- ql/termstructures/volatility/sabrsmilesection.hpp
This prevents the resulting object from recalculating when the evaluation date changes.
> Add `SabrSmileSection` constructor taking a fixed reference date.

- ql/math/comparison.hpp
This optimises the execution times of close() and close_enough() by
- avoiding to pass 42 to close() to evaluate close_enough()
- avoid multiplication to check if one input is zero
As for the second point see the generated code here https://godbolt.org/z/1a8xKvnfs, the multiplication in check() is relatively expensive. I double-checked this with the following test program
```
#include <boost/timer/timer.hpp>
#include <iostream>
bool check(double x, double y) {
if (x * y == 0.0)
return true;
return false;
}
bool check2(double x, double y) {
if (x == 0.0 || y == 0.0)
return true;
return false;
}
int main() {
boost::timer::cpu_timer timer;
std::size_t t = 0;
for (std::size_t n = 0; n < 1E7; ++n) {
if (check(n, n + 1)) {
++t;
}
}
std::cout << "t=" << t << " mult timer " << …
```
> optimize close(), close_enough() functions

- ql/math/comparison.hpp
- ql/termstructures/defaulttermstructure.hpp
- ql/termstructures/inflation/inflationtraits.hpp
- test-suite/creditdefaultswap.cpp
This PR fixes consistency issues with the use of `Real` and consistent use of the test comparison macros.
> Consistent use of Real and Testing Macros

- ql/time/calendars/argentina.cpp
This is quite possibly the most inconsequential PR I ever made but hey -- so CRAN sent me a note to please update two packages re-using some of the QuantLib calendaring sources because `clang++-15` complains (as reported by R analysing the compiler messages)
```
Found the following significant warnings:
ql/time/calendars/argentina.cpp:52:36: warning: invalid UTF-8 in comment [-Winvalid-utf8]
ql/time/calendars/argentina.cpp:52:49: warning: invalid UTF-8 in comment [-Winvalid-utf8]
```
The `file` command concurs (Ubuntu 22.04) here:
```
edd@rob:~/git/quantlib/ql/time/calendars(master)$ file argentina.*           # before
argentina.cpp: C++ source, ISO-8859 text
argentina.hpp: C++ source, Unicode text, UTF-8 text
edd@rob:~/git/quantlib/ql/time/calendars(master)$ file argentina.*           # …
```
> Convert argentina.cpp to utf-8 to appease clang-15

- ql/indexes/inflationindex.cpp
- ql/instruments/zerocouponinflationswap.cpp
In the long run, this should make it unnecessary to load fixings on all days of the month, as `addFixing` does now.
> Check and retrieve inflation fixings on first day of inflation period

- ql/time/calendars/australia.cpp
- ql/time/calendars/australia.hpp
Hi,
This was announced sometime in September. ASX also confirmed being closed on the day. See notice here: https://asxonline.com/content/asxonline/public/notices/2022/september/0987.22.09.html
Best,
Fredrik
> Add holiday for National Day of Mourning to Australian calendar

- ql/time/calendars/unitedkingdom.cpp
- ql/time/calendars/unitedkingdom.hpp
Hi,
This bank holiday was announced Nov 6th, see press release: https://www.gov.uk/government/news/bank-holiday-proclaimed-in-honour-of-the-coronation-of-his-majesty-king-charles-iii.
Side note: These one-off holidays aren't in the docstring yet - maybe they should be added to a special listing?
Best,
Fredrik
> Add King Charles III coronation holiday to UK calendar

- ql/option.hpp
I guess `payoff()` and `exercise()` should be `const`.
Or is there a use case where we want to change them after setup of the `Option`?
> Make Option::payoff() and Option::exercise() const

- ql/instruments/makeswaption.cpp
- ql/instruments/makeswaption.hpp
Makes it easier e.g. to create test cases for both coupon types.
> Added `MakeSwaption::withIndexedCoupons(...)` and `MakeSwaption::withAtParCoupons(...)`

- Examples/README.txt
Added Basket losses, CVAIRS, Gaussian1dModels, Latent Models, and Market Models in the example Readme file.
> Updated Readme

- test-suite/amortizingbond.cpp
Fixes stray usage of `double` in the newly added test
(Flagged by https://github.com/xcelerit/qlxad/actions/runs/3529448372)
> Use Real instead of double in amortizingbond test

- ql/pricingengines/vanilla/qdplusamericanengine.cpp
Adds casts to `Real` for the ternary operator operands to maintain compatibility with expression-template based AAD tools.
This fixes the build issue in qlxad flagged here: https://github.com/xcelerit/qlxad/actions/runs/3636090574/jobs/6135760056
> Casts to Real to maintain AAD compatibility

- ql/cashflows/cpicoupon.cpp
- ql/cashflows/cpicoupon.hpp
- ql/cashflows/indexedcashflow.cpp
- ql/cashflows/indexedcashflow.hpp
Override the method for CPI Cashflows and take the interpolation and lagging into account
> Add indexFixing method to indexed cashflows

- ql/termstructures/inflation/inflationhelpers.cpp
Dont need to interpolate the cpi rate if the maturity of the rate helper falls the on the first date of the inflation period
> Bugfix ZeroCouponInflationSwapHelper

- ql/time/calendars/southafrica.cpp
- ql/time/calendars/southafrica.hpp
Good day, 
An additional public holiday was declared in lieu of Christmas Day falling on a Sunday in 2022.
Here is the announcement by the South Africa government dated 2022-12-08: 
[https://www.gov.za/speeches/president-cyril-ramaphosa-declares-27-december-public-holiday-8-dec-2022-0000](https://www.gov.za/speeches/president-cyril-ramaphosa-declares-27-december-public-holiday-8-dec-2022-0000)
I have also added a note about one-off holidays to the docstring (c.f. #1516).
---Josh
> Adds public holiday in lieu of Christmas 2022 to South Africa calendar

- ql/instruments/barrieroption.cpp
- ql/instruments/vanillaoption.cpp
- ql/instruments/vanillaoption.hpp
- test-suite/barrieroption.cpp
- test-suite/barrieroption.hpp
- test-suite/europeanoption.cpp
- test-suite/europeanoption.hpp
This works around #1540.  The use case doesn't make a lot of sense — either the underlying has announced dividends or it doesn't — but there might be reasons, I guess.
In the long term, dividend options should be folded into their non-dividend counterpart and the dividends should go in the engine, together with the rest of the market info.
> Allow sharing engines between dividend and non-dividend options

- CMakeLists.txt
This pulls in the required CMake package in order to use Intel's new compiler based on their [instructions](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-setup/use-the-command-line/use-cmake-with-the-intel-oneapi-dpc-c-compiler.html).
Note that the [default](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/floating-point-options/fp-model-fp.html) floating point mode of `-fp-model=fast=1` is too imprecise for the current test thresholds. In order to get all the unit tests passing, `-fp-model=precise` must be added to `CMAKE_CXX_FLAGS`, but I'm not sure where is the best place to document this for users.
Incidentally, …
> Add required packages for icpx compiler

- ql/currencies/europe.hpp
The alphabetical order was restored, and the entrance of Croatia into Eurozone in 2023 was documented.
> Reorder header for European currencies.

- ql/processes/merton76process.cpp
- ql/processes/merton76process.hpp
The passed `discretization` instance would not be copied into the process' own data member, resulting in a null pointer access if some of the methods were called.
> Avoid null-pointer access

- ql/time/calendars/newzealand.cpp
- ql/time/calendars/newzealand.hpp
Updated the header file with Doxygen tags and with the link to the NZ government website. Updated the implementation with the Matariki dates. Instead of blindly adding 31 dates I tried to optimize the code as much as possible. Since I am a newbie I am not sure if the coding logic can be optimized further. Thanks in advance for your comments/review.
[Matariki_NZ.ods](https://github.com/lballabio/QuantLib/files/10420359/Matariki_NZ.ods)
> New Zealand calendar missing Matariki holiday #1562

- ql/experimental/barrieroption/vannavolgabarrierengine.hpp
- ql/instruments/barrieroption.cpp
- ql/instruments/barrieroption.hpp
- ql/instruments/dividendbarrieroption.cpp
- ql/instruments/dividendbarrieroption.hpp
- ql/methods/finitedifferences/stepconditions/fdmstepconditioncomposite.cpp
- ql/pricingengines/barrier/fdblackscholesbarrierengine.cpp
- ql/pricingengines/barrier/fdblackscholesbarrierengine.hpp
- ql/pricingengines/barrier/fdblackscholesrebateengine.cpp
- ql/pricingengines/barrier/fdblackscholesrebateengine.hpp
- ql/pricingengines/barrier/fdhestonbarrierengine.cpp
- ql/pricingengines/barrier/fdhestonbarrierengine.hpp
- ql/pricingengines/barrier/fdhestonrebateengine.cpp
- ql/pricingengines/barrier/fdhestonrebateengine.hpp
- test-suite/barrieroption.cpp
- test-suite/barrieroption.hpp
Being market data and not part of the contract, dividends should be passed to pricing engines and not to instruments.
Doing that allows us to use `BarrierOption` for calculations with or without dividends.  `DividendBarrierOption` and its inner `arguments` and `engine` classes are now deprecated; you can use `BarrierOption` instead.  If you have written an engine for dividend barrier options, implement it in terms of `BarrierOption::arguments` and `BarrierOption::engine` instead and pass the dividends in its constructor.
> Unify barrier options and dividend barrier options

- ql/termstructures/inflationtermstructure.cpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
- test-suite/inflation.hpp
Previously, the curves would notify their observers but wouldn't necessarily recalculate, resulting in a curve that wouldn't reprice the passed quotes rates.
> Ensure that inflation curves are re-bootstrapped when seasonality is added

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/inflation/Makefile.am
- ql/indexes/inflation/ukhicp.hpp
- test-suite/inflation.cpp
This adds the UKHICP index along with a basic test. Seeing as other HICP constructors taking the `interpolated` argument have all been deprecated, I've removed that entirely from our additions. Let me know if anything looks fishy.
Best,
Fredrik
> Add UKHICP inflation index

- ql/time/calendars/austria.hpp
- ql/time/calendars/denmark.cpp
- ql/time/calendars/denmark.hpp
- ql/time/calendars/turkey.cpp
- ql/time/calendars/turkey.hpp
- test-suite/calendars.cpp
- test-suite/calendars.hpp
Changes:
- Updates bad link in Turkey's calendar impl
- Corrects specific Turkish holidays between 2019 and 2023. Feel free to help verify this. (many date ranges were off-by-one, presumably also the >2024 holidays)
- Adds three missing holidays to the Denmark calendar. Also adds a test for 2022-2022 holidays vs Bloomberg
- Fixes a comment in the Austrian calendar
> Corrections to Turkish, Danish, and Austrian calendars

- ql/experimental/barrieroption/suowangdoublebarrierengine.cpp
- ql/experimental/barrieroption/vannavolgabarrierengine.cpp
- ql/experimental/barrieroption/vannavolgadoublebarrierengine.hpp
- ql/experimental/credit/integralcdoengine.cpp
- ql/experimental/credit/integralntdengine.cpp
- ql/experimental/credit/midpointcdoengine.cpp
- ql/pricingengines/swaption/blackswaptionengine.hpp
- ql/pricingengines/vanilla/analyticeuropeanengine.cpp
- ql/pricingengines/vanilla/bjerksundstenslandengine.cpp
This fixes consistent `Real` usage on left an right operands of the `?` operator (required when using expression templates).
It also ensures that all the `additionalResults` fields, which are stored as `boost::any`, capture the `Real` type as intended (and just `double` or an expression).
It fixes the build errors detected here: https://github.com/xcelerit/qlxad/actions/runs/4071447311
> Fixing consistent Real usage

- ql/pricingengines/barrier/analyticbarrierengine.cpp
- test-suite/barrieroption.cpp
- test-suite/barrieroption.hpp
This was forcing calls to `impliedVolatility` to fail if the default min volatility was used.
> Avoid NaNs in analytic barrier engine for low volatility values

- ql/currencies/africa.cpp
- ql/currencies/africa.hpp
Hi,
Small addition to the African currencies. Reference: https://en.wikipedia.org/wiki/Botswana_pula
Best,
Fredrik
> Add Botswanan pula currency (BWP)

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/Makefile.am
- ql/indexes/all.hpp
- ql/indexes/equityindex.cpp
- ql/indexes/equityindex.hpp
- test-suite/CMakeLists.txt
- test-suite/Makefile.am
- test-suite/equityindex.cpp
- test-suite/equityindex.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
In this PR I would like to suggest introducing a base equity index class which is used to retrieve historical fixings as well as default logic for forecasting future ones. It could be extended to facilitate e.g. quanto-ed or compo-ed index projections.
If this PR is approved, next step would be to introduce an equity total return swap instrument which would utilize the index class.
Looking forward to your feedback.
This may also be useful for #1195
> Equity index

- .clang-tidy
- ql/cashflows/capflooredinflationcoupon.cpp
- ql/cashflows/capflooredinflationcoupon.hpp
- ql/experimental/averageois/arithmeticoisratehelper.cpp
- ql/experimental/lattices/extendedbinomialtree.cpp
- ql/experimental/termstructures/basisswapratehelpers.cpp
- ql/experimental/termstructures/crosscurrencyratehelpers.cpp
- ql/experimental/variancegamma/variancegammamodel.cpp
- ql/indexes/inflationindex.cpp
- ql/legacy/libormarketmodels/lmexpcorrmodel.cpp
- ql/legacy/libormarketmodels/lmlinexpcorrmodel.cpp
- ql/math/interpolations/bicubicsplineinterpolation.hpp
- ql/math/interpolations/bilinearinterpolation.hpp
- ql/math/interpolations/flatextrapolation2d.hpp
- ql/models/equity/gjrgarchmodel.cpp
- ql/models/shortrate/onefactormodels/extendedcoxingersollross.cpp
- ql/models/shortrate/onefactormodels/hullwhite.cpp
- ql/models/shortrate/twofactormodels/g2.cpp
- ql/pricingengines/vanilla/analytichestonhullwhiteengine.cpp
- ql/pricingengines/vanilla/analytichestonhullwhiteengine.hpp
- ql/processes/hestonslvprocess.cpp
- ql/processes/hestonslvprocess.hpp
- ql/termstructures/inflation/seasonality.cpp
- ql/termstructures/volatility/equityfx/gridmodellocalvolsurface.cpp
- ql/termstructures/volatility/kahalesmilesection.cpp
- ql/termstructures/volatility/smilesection.cpp
- ql/termstructures/volatility/swaption/cmsmarket.cpp
- ql/termstructures/yield/nonlinearfittingmethods.cpp
- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/ratehelpers.cpp
Ideally there should be no need to suppress this check, because no virtual functions should be called in any constructors or destructors as a general design rule. However, user code probably depends on the current behavior, so I have left the current behavior as is and have simply moved the suppression to comments so that at least any new code can be flagged before it is released.
> Move clang-analyzer-optin.cplusplus.VirtualCall suppressions to comments

- ql/pricingengines/barrier/analyticbarrierengine.cpp
Similarly to previous PRs of the same kind, this makes sure that both sides of the ternary operator evaluate to Real for compatibility with AAD packages.
It fixes this [failing CI build](https://github.com/xcelerit/qlxad/actions/runs/4141036895)
> Fixing consistent Real type usage for AAD compatibility

- ql/methods/finitedifferences/operators/fdmlinearopiterator.hpp
This enables `FdmLinearOpIterator` to be used in a modern range-bound for loop, like so:
```c++
for (const auto& iter : *layout) {
setValue(*f_, iter.coordinates(), rhs[iter.index()]);
}
```
Instead of the less modern style currently found in the codebase:
```c++
const FdmLinearOpIterator endIter = layout->end();
for (FdmLinearOpIterator iter = layout->begin(); iter != endIter; ++iter) {
setValue(*f_, iter.coordinates(), rhs[iter.index()]);
}
```
As mentioned in the code comment I added, this overloaded dereference operator does not really dereference the iterator, but rather returns a reference to the iterator itself. It seems that `FdmLinearOpIterator` wasn't designed to be a lightweight iterator - it even copies a vector in its constructor! - so it's a bit confusing to call it an …
> Add operator*() to FdmLinearOpIterator

- ql/methods/finitedifferences/operators/fdmlinearopiterator.hpp
This is already the case for the other constructor that takes `dim`, `coordinates`, and `index`.
> Change FdmLinearOpIterator to pass by value and move

- ql/math/array.hpp
- test-suite/array.cpp
- test-suite/array.hpp
These new operator and function overloads accept an `Array` by rvalue reference in order to avoid a copy on temporaries.
A couple things to note:
- I changed the implementation of `Array::Pow` to use `std::transform` for consistency with all of the other operators and functions.
- If people like this change then I will do the same for `Matrix` in a separate pull request.
> Add move semantics for `Array` operators and functions

- ql/indexes/indexmanager.cpp
- ql/indexes/indexmanager.hpp
- ql/utilities/observablevalue.hpp
Currently `ObservableValue` has only copy constructors and copy assignment operators defined, but it would be nice to support move semantics as well, specifically to avoid the mandatory copy in `IndexManager::setHistory`.
I initialize `observable_` with `new Observable`, same as in the copy constructors and copy assignment operators. However `new` can throw, so I've had to suppress the `performance-noexcept-move-constructor` check, which isn't great. Can `observable_` simply be moved from instead? If so, why isn't its value copied from in the existing methods?
If making `ObservableValue` is not desirable for whatever reason, then we should at least explicitly delete the move constructors and move assignment operators to make the intention clear.
> Allow moving value into `ObservableValue`

- ql/math/interpolations/convexmonotoneinterpolation.hpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/piecewiseyieldcurve.hpp
Fixes #1614.
`ConvexMonotone` had an explicit default constructor and could not be used with the `= {}` syntax, forcing callers of `PiecewiseYieldCurve` to pass the parameter to the constructor explicitly.  The `explicit` is now gone.
> Avoid compilation error using `PiecewiseYieldCurve<ConvexMonotone>`

- ql/time/calendars/unitedstates.cpp
https://www.sifma.org/resources/general/holiday-schedule/
_Early Close Only (12:00 p.m. Eastern Time): Friday, April 7, 2023 - Early Close is recommended rather than a full close to accommodate the release of US employment data_
> Make Gov USA bond 2023 Good Friday working day

- ql/indexes/indexmanager.cpp
- ql/indexes/indexmanager.hpp
- test-suite/indexes.cpp
I've replaced the key lookup in `IndexManager` with an implementation that does not copy the key while preserving the case-insensitivity.
The `CaseInsensitiveCompare` class might be useful in other places as well, so I'll be happy to take suggestions for a better home for it if anyone has any ideas.
> Remove copy on key compare

- ql/math/matrix.hpp
- test-suite/array.cpp
- test-suite/matrices.cpp
- test-suite/matrices.hpp
Continuation of #1606
- For now I have only added overloads for rvalue reference where the return value has the same dimensions as the function argument(s). We can try to support moving matrices with different dimensions, but it will be more tricky.
- I added a defaulted destructor for consistency with the Rule of Five and also fixed a stray typo in the array test.
> Add operators taking Matrix by rvalue reference

- ql/math/array.hpp
- ql/math/interpolations/multicubicspline.hpp
- ql/math/matrix.hpp
- ql/math/sampledcurve.hpp
- ql/methods/finitedifferences/operators/fdmlinearopiterator.hpp
- ql/methods/finitedifferences/operators/ninepointlinearop.cpp
- ql/methods/finitedifferences/operators/ninepointlinearop.hpp
- ql/methods/finitedifferences/operators/triplebandlinearop.cpp
- ql/methods/finitedifferences/operators/triplebandlinearop.hpp
- ql/methods/finitedifferences/tridiagonaloperator.hpp
- ql/utilities/clone.hpp
Following C++ Core Guideline [F.6](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-noexcept), swap functions should be made `noexcept`.
Most of these functions were already implicitly `noexcept` because they are called from move constructors or move assignment operators that are marked `noexcept`, and now that has been made explicit.
> Make swap functions noexcept

- .clang-tidy
- ql/cashflows/cashflows.hpp
- ql/experimental/callablebonds/callablebond.cpp
- ql/math/array.hpp
- ql/math/matrix.hpp
- ql/methods/finitedifferences/operators/ninepointlinearop.hpp
- ql/methods/finitedifferences/operators/triplebandlinearop.hpp
- ql/methods/finitedifferences/tridiagonaloperator.hpp
- ql/patterns/observable.hpp
- ql/patterns/singleton.hpp
- ql/settings.hpp
- ql/termstructures/interpolatedcurve.hpp
- ql/termstructures/volatility/swaption/sabrswaptionvolatilitycube.hpp
- ql/time/date.cpp
- ql/utilities/clone.hpp
- ql/utilities/observablevalue.hpp
- test-suite/inflationcpibond.cpp
- test-suite/observable.cpp
- test-suite/tracing.cpp
- test-suite/utilities.hpp
I added the missing special member function(s) wherever it was straightforward, but for less clear-cut cases I moved the suppression to a comment. It would be good to at some point review the cases that are still suppressed through comments to see if the code can be refactored to follow the guideline.
> Unsuppress cppcoreguidelines-special-member-functions

- ql/models/shortrate/onefactormodels/gaussian1dmodel.hpp
- ql/patterns/observable.hpp
- ql/time/date.cpp
Follow up to https://github.com/lballabio/QuantLib/pull/1287#discussion_r780647564
- Added some includes that must have been previously pulled in through `boost/unordered_set.hpp`.
- Added a specialization for `std::hash` based on [the implemention in Boost](https://github.com/boostorg/smart_ptr/blob/bcb2566e744a0467a980c3648d9e92b7c8ccb2bf/include/boost/smart_ptr/shared_ptr.hpp#L1230-L1236).
> Change boost::unordered_set to std::unordered_set

- ql/instruments/asianoption.cpp
In some constellations the include in `ql/instruments/asianoption.cpp` does not work properly.
https://github.com/ralfkonrad/QuantLib/actions/runs/4841614333/jobs/8627997949#step:5:920
https://github.com/ralfkonrad/QuantLib/actions/runs/4830441525/jobs/8606675127#step:5:172
> Added missing `#include <algorithm>` in `asianoption.cpp`

- ql/time/date.cpp
1. Use `std::hash` instead of `boost::hash` on the underlying serial type.
2. Replace duped `boost/functional/hash.hpp` header with the one for `std::hash`.
3. Only pull in headers for `boost::hash_combine` when `QL_HIGH_RESOLUTION_DATE` is defined.
> Replace boost::hash with std::hash

- cmake/GenerateHeaders.cmake
This is a temporary workaround for #1651.
Better having all needed headers included and getting warnings rather than having an inconsistent `all.hpp` with missing headers in `quantlib.hpp`.
> Workaround for #1651

- test-suite/daycounters.cpp
This replaces `BOOST_CHECK_SMALL` with `QL_CHECK_SMALL`, for compatibility in case `Real` is not `double`. 
It fixes the qlxad build, [as demonstrated here](https://github.com/xcelerit/qlxad/actions/runs/4880374907).
> Fixing test macros for compatibility

- ql/timeseries.hpp
No other usages of Boost MPL that I could find.
> Replace boost::mpl with standard library

- .github/workflows/test-times.yml
- test-suite/andreasenhugevolatilityinterpl.cpp
- test-suite/bermudanswaption.cpp
- test-suite/distributions.cpp
- test-suite/doublebarrieroption.cpp
- test-suite/fdheston.cpp
- test-suite/hestonslvmodel.cpp
- test-suite/shortratemodels.cpp
- tools/check_test_times.py
- more tolerant of occasional slow tests;
- now also points out fast tests incorrectly classified as slow
> Rework check on test times

- CMakeLists.txt
Fix for https://github.com/lballabio/QuantLib/pull/1658
This should now cover all the compilers used in the QuantLib CI.
Here's the [reference](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html) for the full list of compiler IDs.
> Add compile options for AppleClang too

- .github/workflows/sanitizer.yml
ThreadSanitizer cannot be combined with AddressSanitizer, so the two jobs have to be built separately.
I have enabled sessions and the thread-safe observer pattern for this new CI job, and we can add other options too if they are relevant for ThreadSanitizer.
I see that there are some test cases for the thread-safe observer pattern, but nothing specifically for sessions. Probably we should add some unit tests for this one day.
> Add ThreadSanitizer to CI

- ql/cashflows/conundrumpricer.cpp
- ql/cashflows/conundrumpricer.hpp
- ql/experimental/swaptions/haganirregularswaptionengine.cpp
- test-suite/CMakeLists.txt
- test-suite/Makefile.am
- test-suite/cms.cpp
- test-suite/cms_normal.cpp
- test-suite/cms_normal.hpp
- test-suite/quantlibtestsuite.cpp
- test-suite/testsuite.vcxproj
- test-suite/testsuite.vcxproj.filters
Extended functionality, such that cms pricing can cope with the normal model as well. Renamed the class BlackVanillaOptionPricer into MarketQuotedOptionPricer and changed the method  NumericHaganPricer::resetUpperLimit accordingly. In line 97 the YTM struchture used for discounting was changed from the forwardingTermStructure to the discountingTermStructure.
> Enable normal volatilities in Hagan pricer for CMS coupons

- ql/cashflows/cpicoupon.cpp
- ql/cashflows/cpicoupon.hpp
- ql/cashflows/cpicouponpricer.cpp
- ql/cashflows/cpicouponpricer.hpp
- test-suite/inflationcpibond.cpp
The accrued amount for CPI coupons is now based on the index ratio at settlement date.
Also:
- added inspector to retrieve the index ratio at a given date;
- deprecated the use of a spread, which doesn't really make sense for CPI coupons;
- additional `accruedRate` interface for `CPICouponPricer` and deprecation of `adjustedFixing`.
> Add correct accrual calculation for CPI coupons

- ql/time/calendars/finland.cpp
- ql/time/calendars/finland.hpp
- ql/time/calendars/singapore.cpp
- ql/time/calendars/singapore.hpp
- ql/time/calendars/unitedstates.cpp
Hi,
Fixes: 
- The range for Midsummer's Eve in the Finnish calendar was off by one. Should match up with what the Swedish calendar has instead. This resulted in incorrect holidays for 2027, for example
- Singapore's Chinese New Year was off by some days for 2019
- Link was broken in US calendar implementation
Best,
Fredrik
> Fix Finland, Singapore calendars and broken link

- ql/models/volatility/garch.hpp
- ql/timeseries.hpp
- test-suite/timeseries.cpp
I want to remove `boost::transform_iterator` because it pulls in a ton of boost headers into user code, so as a first step I have deprecated all usages of it.
Besides, I don't think the QuantLib library needs to provide these transform iterators - the basic iterators can be used instead and then dereferenced by user code if required.
There is a small chance that the change to `to_r2` and `costFunction` may break user code if users are calling them directly and not through `calibrate`, but I don't think these functions should have ever been made public in the first place.
> Deprecate transform iterators

- test-suite/schedule.cpp
- test-suite/schedule.hpp
Additional test case for schedule test suite. This is the original test case that originated issue #895 which has been recently solved by PR #1509.
> additional test case for schedule

- ql/utilities/steppingiterator.hpp
- test-suite/matrices.cpp
C++20 makes it easy to implement iterators without `boost::iterator_adaptor` because the requirements are checked at compile-time based on the relevant iterator concept, which in this case is [`std::random_access_iterator`](https://en.cppreference.com/w/cpp/iterator/random_access_iterator). The change is backwards-compatible for older compilers as well.
In addition the same concept can be used to constrain the type of underlying iterator used with `step_iterator`, which I have done for compilers that support concepts.
Lastly, I added a few `QL_REQUIRE` to check for operations on incompatible iterators but I'm not sure whether we should add more checks in other places as well.
> Implement iterator_adaptor with standard library

- Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
Fix typo in MulticurveBootstrapping.cpp, comment should read 0.90% not 0.009%, the code is OK.
> Fix typo in MulticurveBootstrapping.cpp

- test-suite/assetswap.cpp
- test-suite/cashflows.cpp
- test-suite/cmsspread.cpp
- test-suite/equitycashflow.cpp
- test-suite/equityindex.cpp
- test-suite/equitytotalreturnswap.cpp
- test-suite/indexes.cpp
- test-suite/inflation.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/overnightindexedcoupon.cpp
- test-suite/piecewiseyieldcurve.cpp
- test-suite/shortratemodels.cpp
- test-suite/utilities.cpp
- test-suite/utilities.hpp
Centralize cleaning of fixings in quantlib_test_case instead of having each test do this manually.
Fixes #1687
> Clear all fixings between tests

- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
We save and/or register with a clone of the passed index, so that the helper doesn't receive notifications from any curves that the index might contain (but that are not used during bootstrapping).
> Avoid spurious notifications in OIS helpers

- ql/time/calendars/bespokecalendar.cpp
- ql/time/calendars/bespokecalendar.hpp
Replace std::set with a bitmask, which is more efficient.
> Use bitmask in BespokeCalendar

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/ibor/Makefile.am
- ql/indexes/ibor/all.hpp
- ql/indexes/ibor/corra.cpp
- ql/indexes/ibor/corra.hpp
Add CORRA Index to QuantLib. 
Closes #1685.
> Add Canadian Overnight Repo Rate Average (CORRA)

- ql/time/calendars/hongkong.cpp
Data from https://www.hkex.com.hk/-/media/HKEX-Market/Services/Circulars-and-Notices/Participant-and-Members-Circulars/SEHK/2023/ce_SEHK_CT_079_2023.pdf .
> Add Hong Kong Securities Market Holidays in 2024

- ql/currencies/exchangeratemanager.cpp
- ql/experimental/credit/basket.cpp
- ql/termstructures/volatility/smilesectionutils.cpp
There are few places where `std::find()` and `std::find_if()` are used, but `<algorithm>` are not `#include`-ed.
> Fix compile error on GCC 12

- ql/time/calendar.cpp
Use only one loop and make fewer isBusinessDay() calls.
> Simplify Calendar::businessDaysBetween

- ql/indexes/interestrateindex.cpp
- test-suite/indexes.cpp
- test-suite/indexes.hpp
Fixes the effects of #1696 on interest-rate indexes.
> Don't normalize days to weeks in interest-rate index

- ql/indexes/ibor/sofr.cpp
- ql/time/calendars/unitedstates.cpp
- ql/time/calendars/unitedstates.hpp
- test-suite/calendars.cpp
- test-suite/calendars.hpp
Not always the same as the Government Bond / SIFMA calendar, see the discussion in #1635.
> Add separate calendar for SOFR fixing dates

- .lsan.txt
- test-suite/lazyobject.cpp
> Break ring of shared_ptr<Stock> dependencies

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/Makefile.am
- ql/instrument.cpp
- ql/instrument.hpp
This makes sense in general (if the evaluation date changes, you probably want to recalculate) and can also help avoid some (not all) edge cases when lazy objects only forward their first notification.
> Register instruments with evaluation date

- ql/instruments/overnightindexedswap.cpp
- ql/instruments/overnightindexedswap.hpp
This addresses  #1666.
I haven't split the schedule in two yet, but if this looks okay, i will do that. In doing that i will delete the schedule accessor i defined here. I think that should not be a backwards compatibility concern as it will never have appeared in a release.
> Expose ois schedule

- ql/timeseries.hpp
This addresses #1726.
For the const operator[], this simply uses the iterator returned by find.
For the non-const operator[], which can insert a null, this changes to using [map::insert](https://en.cppreference.com/w/cpp/container/map/insert), which has exactly the behaviour we want - "returns a reference to the value that is mapped to a key equivalent to key, performing an insertion if such key does not already exist".
> Save a historical fixing map access

- .github/workflows/cmake.yml
- .github/workflows/tidy.yml
- CMakePresets.json
This PR modernises the `CMakePresets.json` to make it more useful and less repetitive for developers (not just for CI/CD). 
It defines a set of hidden, base configurations, and uses `inherit` to combine them into user-accessible configure presets for each Windows/Linux with MSVC/Clang/GCC. This makes the dropdown with the Visual Studio "Open Folder" feature look like this for a Windows target:
When selecting a remote or WSL Linux target machine, the drop-down looks like this:
For Linux, both Unix Makefiles (default) and Ninja generator presets are there.
The same configuration presets are of course also available on the command-line with `cmake --preset xxxx`. 
The build directory is set to `${sourceDir}/build/${presetName}`, so all presets can live side-by-side. The corresponding CI/CD …
> Modernised CMakePresets.json to make it more useful for developers

- ql/termstructures/yield/oisratehelper.cpp
- test-suite/overnightindexedswap.cpp
- test-suite/overnightindexedswap.hpp
See e.g. the added regression test case.
> Avoid possible segfault when bootstrapping over OIS rates

- CMakePresets.json
Unfortunately, I had only a brief look at the changes @eltoder suggested in #1723. The idea of _Modernised CMakePresets.json to make it more useful for developers_ is absolutely right.
However, the new, but hidden presets `debug`, `release` and `relwithdebinfo` conflict with our existing ones in `CMakeUserPresets.json` and also with the default preset names  `CLion` uses.
@eltoder: Any objections to rename them by adding a starting underscore: `_debug` etc.? They are hidden anyhow.
We like the easy to remember calls across all platforms:
```bash
> cmake --preset release
> cmake --build --preset release -j 12 -v
```
I guess it is worth not "burning" these often used preset names?!
Perhaps later on we can rename all presets to start with `ql_` which would be in line e.g. the naming …
> Renamed conflicting preset names `debug`, `release` and `relwithdebinfo`

- ql/patterns/observable.cpp
- ql/patterns/observable.hpp
Background: when we instantiate an `Observable` in a child-thread of the main thread and the child-thread is terminated but the observable instance happens to be still alive, this causes a segfault because the reference to the child-thread's `ObservableSettings` is dangling now.
After the change the observable instance would always use the observable settings of the thread in which it is currently operated on. We should be aware that this potentially changes the behaviour of observables when different threads have different observable settings and the observable is operated on in the different threads. 
My main intend here is to avoid undefined behaviour in situations as described above.  If someone really depends on the current behaviour, this change might break their code. I think this …
> remove reference to observable settings

- ql/patterns/observable.hpp
- ql/termstructures/globalbootstrap.hpp
- ql/termstructures/iterativebootstrap.hpp
- ql/termstructures/localbootstrap.hpp
often the set of helpers will share common observables which we only need to register with once
addresses #1730
> register with observables of bootstrap helpers instead of the helpers themselves

- ql/patterns/observable.hpp
> use `std::set` everywhere to store observers, observables

- Examples/BasketLosses/BasketLosses.cpp
- Examples/BermudanSwaption/BermudanSwaption.cpp
- Examples/Bonds/Bonds.cpp
- Examples/CDS/CDS.cpp
- Examples/CVAIRS/CVAIRS.cpp
- Examples/CallableBonds/CallableBonds.cpp
- Examples/ConvertibleBonds/ConvertibleBonds.cpp
- Examples/DiscreteHedging/DiscreteHedging.cpp
- Examples/EquityOption/EquityOption.cpp
- Examples/FRA/FRA.cpp
- Examples/FittedBondCurve/FittedBondCurve.cpp
- Examples/Gaussian1dModels/Gaussian1dModels.cpp
- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- Examples/LatentModel/LatentModel.cpp
- Examples/MarketModels/MarketModels.cpp
- Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
- Examples/MultidimIntegral/MultidimIntegral.cpp
- Examples/Replication/Replication.cpp
- Examples/Repo/Repo.cpp
As discussed in https://github.com/lballabio/QuantLib/pull/1758#issuecomment-1664025486, here is a first pass at modernizing the examples by introducing `auto` and `ext::make_shared`. I also removed spaces between angle brackets for a more modern feel.
I tried to preserve the existing formatting as much as possible, but feel free to reformat the changed lines if you prefer.
We can add `auto` in a lot more places, both in the examples and the main library, just let me know if you think now is the time.
> Modernize Examples

- .clang-tidy
- ql/currencies/exchangeratemanager.cpp
- ql/experimental/commodities/commodity.cpp
- ql/methods/montecarlo/lsmbasissystem.cpp
- ql/pricingengines/forward/replicatingvarianceswapengine.hpp
- ql/termstructures/volatility/equityfx/andreasenhugevolatilityinterpl.cpp
- ql/termstructures/volatility/optionlet/strippedoptionlet.cpp
- test-suite/andreasenhugevolatilityinterpl.cpp
- test-suite/catbonds.cpp
- test-suite/swingoption.cpp
The `modernize-use-emplace` check offers a fix, so this will show up in the weekly clang-tidy fixes job from now on.
> Unsuppress modernize-use-emplace

- ql/instruments/overnightindexedswap.cpp
- ql/instruments/overnightindexedswap.hpp
- test-suite/overnightindexedswap.cpp
- test-suite/overnightindexedswap.hpp
> An OIS needs different notionals for different schedules

- ql/termstructures/yieldtermstructure.cpp
- test-suite/termstructures.cpp
- test-suite/termstructures.hpp
We need to detect and manage the case in which a date is not the same as the reference date of the curve, but the time between them is null according to the chosen day-count convention.
Fixes #1797.
> Detect null time-to-reference when calculating zero rates

- ql/termstructures/volatility/swaption/swaptionvolcube.cpp
- ql/termstructures/volatility/swaption/swaptionvoldiscrete.cpp
- ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp
For times before the first option date `optionDateFromTime()` can return a date < evaluation date. I would suggest to include the evaluation date and t = 0 into the linear interpolation used to do the time to date conversion.
> Include time zero / evaluation date in option date interpolation

- test-suite/libormarketmodel.cpp
- test-suite/xoshiro256starstar.cpp
This fixes consistent usage of `Real` with the new xoshiro256 random generator.
It fixes the build issues with XAD seen here: https://github.com/auto-differentiation/quantlib-xad/actions/runs/6414891338 
This is the fixed build: https://github.com/auto-differentiation/quantlib-xad/actions/runs/6417063131
> Fix double/Real consistency for maintaining AAD compatibility

- ql/instruments/overnightindexedswap.cpp
Since the big refactor #1789 which made OvernightIndexedSwap derive from FixedVsFloatingSwap, the payment lag and payment calendar were not applied to the fixed leg.
> apply the paymentLag and paymentCalendar to the fixed leg

- ql/instruments/bond.hpp
Sorry, very trivial change, but just to align the interface and implementation function definitions.
> Fix parameter name

- ql/time/calendars/southafrica.cpp
Ad hoc public holiday declare for 15 December 2023 for South Africa. https://www.gov.za/about-sa/public-holidays#2023
> Add 2023-12-15 as South African public holiday

- CMakePresets.json
Closes #1824 .
The first commit fixes the original issue.
The second commit cleans some presets up by making use of previously defined presets.
> CMake presets: Obey ordering rule

- test-suite/optimizers.cpp
This addresses issue #1822.
The issue has been using a vector where the underlying value type has only been forward declared and defined later on, e.g.
```c++
struct NamedOptimizationMethod;
std::vector<std::vector<NamedOptimizationMethod> > optimizationMethods_;
struct NamedOptimizationMethod {
ext::shared_ptr<OptimizationMethod> optimizationMethod;
std::string name;
};
```
Minimal (non-)working example: [godbolt](https://godbolt.org/z/P7jGPWvEo)
> fixing compilation issue: value usage of fwd declared struct

- ql/instruments/makeois.cpp
- ql/instruments/makeois.hpp
- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
Allow setting different payment frequencies for fixed and overnight legs.
> Allow different frequencies in MakeOIS and OISRateHelper

- ql/math/solver1d.hpp
Resolves compilation failure in https://github.com/lballabio/QuantLib/actions/runs/7073435454/job/19253354984.
It doesn't look like the uninitialized value would ever be used in the code, so it could be a false positive, but anyway it's best practice to always initialize member variables.
> Initialize bounds in Solver1D

- ql/currency.cpp
- ql/currency.hpp
- ql/money.cpp
- test-suite/currency.cpp
Closes #1801 
Let me know if there are any other arguments to the constructors of `Currency` or `Currency::Data` that you think should be deprecated at the same time.
> Deprecate Currency::format

- ql/time/calendars/taiwan.cpp
- ql/time/calendars/taiwan.hpp
Hi,
Small additions sourced from the link in the docstring.
Not sure whether to also add 2023-08-03 as a past holiday, when the markets closed in the afternoon due to a typhoon. Reference: https://www.reuters.com/world/asia-pacific/typhoon-khanun-shuts-markets-grounds-flights-taiwan-2023-08-03/. 
/Fredrik
> Add TWSE holidays for 2024 to Taiwan calendar

- ql/time/calendars/thailand.cpp
- ql/time/calendars/thailand.hpp
Hi,
Building on @mgroncki's work (cherry-picked for attribution) from their [fork](https://github.com/OpenSourceRisk/QuantLib/blob/master/ql/time/calendars/thailand.cpp), I've extended the Thai holidays until 2024. The calendar now matches our expectations for 2019 through 2024. 
Updated based on a few references:
- [Holidays 2019](https://www.bot.or.th/content/dam/bot/fipcs/documents/FPG/2561/EngPDF/25610226.pdf)
- [Holidays 2020](https://www.bot.or.th/content/dam/bot/fipcs/documents/FPG/2562/EngPDF/25620179.pdf)
- [Holidays 2021](https://www.bot.or.th/content/dam/bot/fipcs/documents/FPG/2563/EngPDF/25630233.pdf)
- [Substitutions 2023](https://www.bot.or.th/en/news-and-media/news/news-20231102.html)
- And: https://www.bot.or.th/en/financial-institutions-holiday.html
> Correct Thailand calendar for 2019-2024

- ql/time/calendars/unitedstates.cpp
- ql/time/calendars/unitedstates.hpp
- test-suite/calendars.cpp
Hi,
These two links suggest the moving of Juneteenth to Fridays is incorrect for the Federal Reserve implementation: 
- https://www.federalreserve.gov/aboutthefed/k8.htm
- https://www.frbservices.org/about/holiday-schedules
This currently leads to issues during 2027, 2032, etc. I've added a boolean to `isJuneteenth` to preserve the behavior for other calendar implementations.
> Stop moving Juneteenth to Friday if Saturday for US-Fed calendar

- ql/time/ecb.cpp
- test-suite/dates.cpp
The known maintenance dates were updated for 2018..2024.
The implementation of ECB functions were simplified (e.g. large switch blocks replaced) and optimized for memory allocations (e.g. temporary strings were replaced by string_views).
The test coverage is also completed for ECB functions.
> ECB: updated hard-coded known dates; simplified/improved implementation; completed test coverage

- ql/models/parameter.hpp
> Binary search in times

- ql/time/calendars/chile.cpp
- ql/time/calendars/chile.hpp
> Added Dec. 31 NYE holiday to Chilean calendar in chile.cpp

- ql/math/integrals/exponentialintegrals.cpp
- ql/pricingengines/vanilla/analytichestonengine.cpp
- test-suite/americanoption.cpp
- test-suite/functions.cpp
- test-suite/hestonmodel.cpp
- test-suite/integrals.cpp
- test-suite/utilities.hpp
This fixes consistent usage of `Real` and the QL test macros, in order to allow defining `Real` as an AAD type. 
The fixed version has been tested against [XAD](https://auto-differentiation.github.io).
> Fixes to maintain AAD compatibility

- ql/time/calendars/brazil.cpp
- ql/time/calendars/brazil.hpp
- test-suite/amortizingbond.cpp
Closes #1870.
This adds the newly introduced "Black Awareness Day" holiday on 20th November starting in 2024.
The data for the unit test had to be modified to incorporate the holiday, even though it is not currently included in the data source.
> New Brazilian holiday

- ql/time/calendars/mexico.cpp
- ql/time/calendars/mexico.hpp
- test-suite/calendars.cpp
Hi,
This new holiday is mentioned in this article (https://bnnbreaking.com/world/mexico/mexicos-new-holiday-a-day-of-celebration-and-reflection/) and also listed on the website of BMV from the current docstring. Includes a minimal test to verify the logic.
> Add Inauguration Day to Mexican calendar

- test-suite/quantlibtestsuite.cpp
We are missing #include of the config option to select parallel test runner, so we always end up with the standard one.
> Fix building parallel test runner

- test-suite/CMakeLists.txt
Since we are using header only parts using BOOST_ALL_NO_LIB.
This fixes a linking error on windows.
> Remove use of BOOST_ALL_DYN_LINK

- ql/experimental/inflation/cpicapfloortermpricesurface.cpp
- ql/experimental/inflation/cpicapfloortermpricesurface.hpp
- ql/experimental/inflation/yoycapfloortermpricesurface.cpp
- ql/experimental/inflation/yoycapfloortermpricesurface.hpp
- ql/indexes/inflationindex.cpp
- ql/indexes/inflationindex.hpp
- ql/termstructures/inflation/inflationtraits.hpp
- ql/termstructures/inflation/interpolatedyoyinflationcurve.hpp
- ql/termstructures/inflation/interpolatedzeroinflationcurve.hpp
- ql/termstructures/inflation/piecewiseyoyinflationcurve.hpp
- ql/termstructures/inflation/piecewisezeroinflationcurve.hpp
- ql/termstructures/inflationtermstructure.cpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/inflationcpibond.cpp
- test-suite/inflationcpicapfloor.cpp
- test-suite/inflationcpiswap.cpp
- test-suite/inflationvolatility.cpp
The base date of an inflation curve should correspond to the latest published inflation fixing, because that's the boundary between what we already know and what we need to forecast.
This is awkward to specify by means of an observation lag, which is probably the wrong concept anyway—it's tied to instruments T&Cs.  With these changes, it's possible to pass the base date directly.  Constructors taking the observation lag are now deprecated.
> Pass an explicit base date to inflation curves instead of an observation lag

- ql/time/calendars/unitedstates.cpp
- test-suite/calendars.cpp
Closes #1886.
Add Good Friday as holiday for SOFR calendar. 
Unit test checks years from 2017 through 2031.
> Good Friday holiday for SOFR

- ql/pricingengines/bond/bondfunctions.cpp
- test-suite/bonds.cpp
Most `BondFunctions` methods are overloaded, with one version converting its arguments and chaining to a different overload where defaults are handled and then a call made to static [CashFlows](https://www.quantlib.org/reference/class_quant_lib_1_1_cash_flows.html) methods to do the actual calculations -- e.g. [`BondFunctions::duration()`](https://github.com/lballabio/QuantLib/blob/9b052b1fe3a1455aa56cc89d34d70e4732eb1191/ql/pricingengines/bond/bondfunctions.cpp#L377) and [`BondFunctions::duration()`](https://github.com/lballabio/QuantLib/blob/9b052b1fe3a1455aa56cc89d34d70e4732eb1191/ql/pricingengines/bond/bondfunctions.cpp#L393) (v1.33).
[`basisPointValue()`](https://github.com/lballabio/QuantLib/blob/9b052b1fe3a1455aa56cc89d34d70e4732eb1191/ql/pricingengines/bond/bondfunctions.cpp#L428) …
> Make BondFunctions BPV and YVBP consistent

- ql/time/calendars/brazil.cpp
- ql/time/calendars/brazil.hpp
Fix - São Paulo city holiday just for years before 2022 for Brazilian exchange holidays. 
Official statement:
[B3 News](https://www.b3.com.br/pt_br/noticias/b3-tera-pregao-nos-feriados-municipais-de-sao-paulo-em-2023.htm)
Current rule for holidays:
[B3 trading calendar](https://www.b3.com.br/en_us/solutions/platforms/puma-trading-system/for-members-and-traders/trading-calendar/holidays/)
> Fix - São Paulo city holiday just for years before 2022 

- ql/math/integrals/discreteintegrals.cpp
Reduce space usage of discrete integrals, no need to allocate extra space.
> Reduce space usage of Discrete Integrals

- ql/time/schedule.cpp
push_back new dates/regular flags and reverse at the end instead of inserting at the front
> generate schedules with DateGeneration::Backward in linear time

- ql/cashflows/iborcoupon.cpp
- ql/cashflows/iborcoupon.hpp
Return the cached date from fixingDate() method since it is used internally in indexFixing().
> Return cached fixingDate in IborCoupon

- ql/instruments/futures.cpp
- ql/instruments/futures.hpp
- ql/termstructures/yield/ratehelpers.cpp
This allows passing custom future dates. Closes #1855
> Add Futures::Type Custom

- ql/time/calendar.cpp
- test-suite/businessdayconventions.cpp
- test-suite/cashflows.cpp
This PR resolves https://github.com/lballabio/QuantLib/issues/1910
In Calendar::advance(), the return date will be moved to end of business day if endOfMonth && isEndOfMonth(d) is True. However, isEndOfMonth(d) is True when d is on or after the end of business day, which introduces a discrepancy between d and the return date.
This PR fixes this behavior by returning the end of calendar date when convention is Unadjusted.
I added a unit test to ensure this behaves correctly for a US treasury bond. The ref start date should be end of calendar date and the cashflow should match the real-world cashflow.
> Fix calendar advance for unadjusted convention

- ql/time/calendars/india.cpp
Hi,
Quite a few of these holidays moved around...
Some sources (main page is already linked in the docstring):
* 2024: https://www.nseindia.com/resources/exchange-communication-holidays
* 2023: https://www.nseindia.com/products/content/equities/slbs/mrkt_timing_holidays.htm
* Moving of the Eid-e-Milad holiday 2023: https://www.5paisa.com/news/is-stock-market-closed-on-29th-september-2023-eid-e-milad
Regards,
Fredrik
> Update 2023-2024 holidays in Indian calendar

- test-suite/cashflows.cpp
- test-suite/period.cpp
- test-suite/prices.cpp
I appears that comparison tolerances set with the `boost::test_tools::tolerance` template are ignored if their data type is different to the type of the expression. This PR explicitly sets the type to `Real`, which avoids this problem.
An illustration of this problem can be seen in the [QuantLib build with AAD here](https://github.com/auto-differentiation/quantlib-xad/actions/runs/8106892201/job/22157556873#step:9:249), where `Real` is different from `double`.
> Fixes data type used for test tolerances in boost

- ql/time/calendars/singapore.cpp
- ql/time/calendars/singapore.hpp
- ql/time/calendars/southafrica.cpp
- ql/time/calendars/thailand.cpp
Hello,
Minor additions with new data.
Singapore:
* https://www.kensington-trust.com/public-holiday-on-polling-day-1-september-2023/
* https://api2.sgx.com/sites/default/files/2024-01/SGX%20Calendar%202024_2.pdf
Thailand:
* https://www.bot.or.th/en/news-and-media/news/news-20240221.html
South Africa:
* https://www.gov.za/news/media-statements/president-cyril-ramaphosa-announces-2024-general-elections-date-20-feb-2024
> Fix Thailand, Singapore, South African calendars for 2023, 2024

- Examples/Bonds/Bonds.cpp
- Examples/FittedBondCurve/FittedBondCurve.cpp
- Examples/Repo/Repo.cpp
- ql/instruments/bond.cpp
- ql/instruments/bond.hpp
- ql/instruments/bonds/btp.cpp
- ql/pricingengines/bond/bondfunctions.cpp
- ql/pricingengines/bond/bondfunctions.hpp
- ql/termstructures/yield/fittedbonddiscountcurve.cpp
- test-suite/bonds.cpp
- test-suite/fittedbonddiscountcurve.cpp
I noticed some more bond functions that currently accept only a clean price. This PR extends them to accept either dirty or clean price and adds the relevant priceType parameter.
Previous attempt at #939
> More functions to support both clean and dirty prices as input parameter

- ql/experimental/termstructures/crosscurrencyratehelpers.cpp
- test-suite/crosscurrencyratehelpers.cpp
This bug was identified thanks to Aleksis Ali Raza, who reported it on the QuantLib mailing list.
When bootstrapping an FX term structure using cross currency basis swaps, the initial (settlement date) notional exchange has to be included. Depending on the settlement date settings of the curve, the corresponding discount factor may be equal to 1 (if instrument settlement and curve settlement dates coincide) or may slightly deviate from 1 (if those are different). 
Initially, an implicit (and unintentional) assumption was made that the instrument settlement date is the same as the one in the curve. This PR removes this assumption, allowing both settlement dates to be set freely.
> Bug fix - cross currency basis swap rate helpers settlement date payment

- ql/experimental/math/laplaceinterpolation.cpp
This consistently uses `Real` for all numeric types - fixing an [issue discovered with automatic differentiation](https://github.com/auto-differentiation/quantlib-xad/actions/runs/8385741661). [This build](https://github.com/auto-differentiation/quantlib-xad/actions/runs/8387289798) includes this change and shows that it fixes the issue.
> Add conversions to Real in Laplace Interpolation file for consistency

- Examples/BermudanSwaption/BermudanSwaption.cpp
- ql/cashflows/overnightindexedcoupon.cpp
- ql/cashflows/overnightindexedcoupon.hpp
- ql/experimental/basismodels/swaptioncfs.cpp
- ql/experimental/basismodels/swaptioncfs.hpp
- ql/experimental/basismodels/tenorswaptionvts.cpp
- ql/instruments/makeswaption.cpp
- ql/instruments/makeswaption.hpp
- ql/instruments/nonstandardswap.cpp
- ql/instruments/nonstandardswap.hpp
- ql/instruments/swaption.cpp
- ql/instruments/swaption.hpp
- ql/legacy/libormarketmodels/lfmswaptionengine.cpp
- ql/methods/finitedifferences/utilities/fdmaffinemodelswapinnervalue.hpp
- ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp
- ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp
- ql/pricingengines/swaption/blackswaptionengine.hpp
- ql/pricingengines/swaption/g2swaptionengine.hpp
- ql/pricingengines/swaption/gaussian1dswaptionengine.cpp
- test-suite/basismodels.cpp
- test-suite/libormarketmodel.cpp
- test-suite/swaption.cpp
closes #1588 I don't want to take any credit this for this code. This is cherry picked from https://github.com/OpenSourceRisk/QuantLib. @pcaspers mentionned before that he would be willing to contribute this to QuantLib, see https://github.com/lballabio/QuantLib/pull/1379#issuecomment-1123571248
> allow swaptions to take OvernightIndexedSwap

- ql/cashflows/indexedcashflow.hpp
- ql/cashflows/zeroinflationcashflow.cpp
- ql/cashflows/zeroinflationcashflow.hpp
- test-suite/inflation.cpp
> Make `ZeroInflationCashFlow` properly lazy

- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
I added it recently, but this was a mistake: forwardStart has no effect when both start and end dates are specified.
> Remove forwardStart from DatedOISRateHelper

- ql/models/marketmodels/driftcomputation/smmdriftcalculator.cpp
Pre-computation of Annuities: The updated code introduces a pre-computation of annuities for all rates and stores them in a vector. This avoids repeated calls to `cs.coterminalSwapAnnuity()` within the nested loops, potentially reducing computational overhead and improving performance.
Corresponding unit test runs ~30% faster on a single processor (standard build, g++ 11.4.0)
> Precompute annuities

- ql/indexes/ibor/bibor.hpp
- ql/indexes/ibor/euribor.hpp
- ql/indexes/ibor/eurlibor.hpp
They can be still instantiated by means of a generic constructor anyway.
> Deprecate a few specific indexes no longer fixed.

- ql/handle.hpp
I'm getting `'QuantLib::Handle<T>::Handle': no overloaded function could convert all the argument types` when trying to use the constructor of `RelinkableHandle` that takes a raw pointer. Not sure if I'm doing it right, but even if it does work, I believe that this constructor should be deprecated for the following reasons:
* `Handle` does not provide a constructor taking a raw pointer and it's unclear why `RelinkableHandle` needs to.
* `shared_ptr` takes ownership of the raw pointer, which may not be obvious from the constructor declaration, and can lead to double delete bugs.
Also I changed a couple of places to pass by value and move.
> Deprecate RelinkableHandle constructor taking a raw pointer

- ql/cashflows/overnightindexedcoupon.cpp
- ql/cashflows/overnightindexedcoupon.hpp
- ql/instruments/makeois.cpp
- ql/instruments/makeois.hpp
- ql/instruments/overnightindexedswap.cpp
- ql/instruments/overnightindexedswap.hpp
- test-suite/overnightindexedcoupon.cpp
In this PR I would like to add new functionality allowing to handle lookbacks, with and without observation shifts, and lockouts in the overnight indexed coupon.
The methodology for lookbacks and lockouts is outlined in a document by [NY FED](https://www.newyorkfed.org/medialibrary/Microsites/arrc/files/2021/users-guide-to-sofr2021-update.pdf) (pages 16-22).
Excel examples, based on which the unit tests were created, can also be found on the NY FED [website](https://www.newyorkfed.org/medialibrary/Microsites/arrc/files/2020/ARRC-BWLG-Examples-Other-Lookback-Options.xlsx).
Lookback days do not need to define a separate member in the `OvernightIndexedCoupon` class, instead utilize the `fixingDays_` member, because it already serves that purpose. It should be noted however that applying a …
> Add lookback and lockout to the overnight coupon

- ql/termstructures/yield/overnightindexfutureratehelper.cpp
- test-suite/sofrfutures.cpp
> Account for possible date adjustments (e.g. on Juneteenth) in SOFR rate helper

- ql/cashflows/iborcoupon.cpp
- ql/cashflows/iborcoupon.hpp
- test-suite/cashflows.cpp
It is sometimes useful to look at an IBOR coupon and know whether it is based on a historical fixing or a forecast. This change exposes that decision, and also - IMHO! - cleans up the code to get a fixing a little.
This change does mean that for fixings today, we now call Index::pastFixing twice. Personally i don't think that's a big deal (especially since  #1731). Otherwise, i think the functional and non-functional behaviour is the same.
I think this method would probably make sense in FloatingRateCoupon, using the same logic. I could pull it up if you think that would be useful. However, in that case, we should think about what OvernightIndexedCoupon.
> Expose an IBOR coupon's decision about whether it has fixed or not

- ql/time/calendar.cpp
- ql/time/calendars/chile.cpp
- ql/time/calendars/chile.hpp
* Day of Aboriginal People is on the day of the Winter Solstice, which is not always June 21th. (Except for 2021, when it was on June 21th even though the solstice was on the 20th.)
* Add 2022-09-16, which was a day in lieu of Independence Day.
* Add 2018-01-16, which was a regional holiday for the Papal visit.
* Add 2017-04-19, which was a Census Day.
> Fix Chile holidays

- ql/time/calendars/unitedstates.cpp
Use a general NFP/SIFMA rule for Good Friday instead of hard-coding 3 specific years.
> Improve US GovernmentBond calendar

- ql/time/calendars/india.cpp
- ql/time/calendars/india.hpp
Hi,
Long overdue but here are at least the slimmed down corrections as suggested in #1929. 
I didn't add a separate implementation for RBI, but perhaps we can do so in the future if they appear to diverge.
> Correct holidays of 2024 for Indian NSE calendar

- ql/time/calendars/brazil.cpp
- ql/time/calendars/brazil.hpp
Hi all,
São Paulo city holidays became trading days in Brazil since 2022. 
There are 3 city holidays: January 25th, July 9th, and November 20th. However, only one of them (January 25th) was correctly handled in the code. I noticed this issue yesterday, on July 9th.
November 20th was considered a trading day in 2022-23, but in 2024, it became a national holiday.
[News (Portuguese)](https://www.cnnbrasil.com.br/economia/financas/b3-tera-pregao-em-feriados-municipais-de-sp-a-partir-de-2022/)
[B3 trading calendar](https://www.b3.com.br/en_us/solutions/platforms/puma-trading-system/for-members-and-traders/trading-calendar/holidays/)
First PR, please advise if further testing is needed. Best,
> Fix Brazilian holidays (São Paulo city holidays)

- test-suite/quantlibbenchmark.cpp
Validation run has very different characteristics from benchmarking
run.  This produced unintuitive scaling results as number of threads
was kept fixed and problem size increased.
This patch separates validation from benchmarking and ensures that
validation time does not affect the benchmark results.  Benchmark now
reports consistent throughput for --nProc=1 as --size increases from 1
to 2 to 3 etc.  When nProc>1, throughput stabilises as soon as the tail
effect ratio is high enough.
> Separate validation from benchmarking run

- ql/instruments/swaption.cpp
- ql/instruments/swaption.hpp
- ql/pricingengines/swaption/blackswaptionengine.hpp
- test-suite/swaption.cpp
For European swaption, sometimes the price is quoted as a forward price to be paid at exercise time.
This PR allows to use such a quoted price for implied-volatility calculation.  The forward price is also returned by the Black and Bachelier swaption engines as an additional result.
> Optionally allow using forward price for swaption implied-volatility calculation

- ql/pricingengines/swaption/blackswaptionengine.hpp
This fixes an error occurring when expression templates are used for the `Real` datatype operations. Since `additionalResults` is using `boost::any` as storage type, expressions get stored directly and not their evaluated version. The causes runtime failures like the one seen in [this build](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/actions/runs/9985832697).
This PR adds an explicit conversion which avoids this error, as proven in [this pipline](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/actions/runs/9987486375).
> Explicit type conversion in `additionalResults`

- ql/index.hpp
- ql/indexes/equityindex.cpp
- ql/indexes/equityindex.hpp
- ql/indexes/inflationindex.cpp
- ql/indexes/inflationindex.hpp
- ql/indexes/interestrateindex.hpp
As most of the derived indices already 
- derive from `public Observer` and
- implement their own `Real pastFixing(const Date& fixingDate) const`
I have added them to the `Index` interface as they seems to be a natural and useful extension of the interface.
The basic implementation
```c++
inline Real Index::pastFixing(const Date& fixingDate) const {
QL_REQUIRE(isValidFixingDate(fixingDate), fixingDate << " is not a valid fixing date");
return timeSeries()[fixingDate];
}
```
is overwritten for the inflation indices as their fixing is a bit more elaborated.
> Extend `Index` interface

- ql/CMakeLists.txt
This makes the `cxx_std_17` a compile feature of the library, meaning that it will be propagated to client code with CMake, that uses `find_package(QuantLib)`. Any code linking to `QuantLib` after that will get the C++ standard flags (can be overridden).
This avoids that client code needs to be modified when QuantLib changes its default C++ standard.
> Set C++ standard also for client code using CMake

- Examples/GlobalOptimizer/GlobalOptimizer.cpp
- Examples/MultidimIntegral/MultidimIntegral.cpp
- test-suite/fdheston.cpp
- test-suite/fdmlinearop.cpp
- test-suite/fdsabr.cpp
- test-suite/interpolations.cpp
- test-suite/linearleastsquaresregression.cpp
- test-suite/normalclvmodel.cpp
- test-suite/utilities.hpp
That is, `<tuple>` and `<functional>` instead of `<ql/tuple.hpp>` and `<ql/functional.hpp>`.  The latter are obsolete, so we avoid them in examples and tests, which are the source files people would use as models for their own coding.
> Use std headers in examples and tests

- cmake/Platform.cmake
- ql/math/integrals/exponentialintegrals.cpp
- ql/pricingengines/vanilla/analytichestonengine.cpp
- ql/time/ecb.cpp
These two warnings are not enabled by default at the W3 level, but they are nice to have in the CI so I have added them.
> Add more warnings to W3

- ql/experimental/credit/spotlosslatentmodel.hpp
- ql/pricingengines/blackformula.cpp
This PR fixes instances where `Real` is instantiated as `double`. These issues were discovered in [QuantLib-Risks-Cpp](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/). The changes are:
- boost::math::normal_distribution<~double~ -> Real> in [blackformula.cpp](https://github.com/lballabio/QuantLib/blob/master/ql/pricingengines/blackformula.cpp)
- All meaningful instantiations of `Real` as `0.` (or variations) changed to `Real(0.)` for consistency in [spotlosslatentmodel.hpp](https://github.com/lballabio/QuantLib/blob/master/ql/experimental/credit/spotlosslatentmodel.hpp)
> Small fixes for AAD

- ql/termstructures/yield/nonlinearfittingmethods.hpp
Inconsistency was found between:
- Svensson implementation here https://github.com/lballabio/QuantLib/blob/c0fac242125283ac78984a21dd577e23823d23d6/ql/termstructures/yield/nonlinearfittingmethods.cpp#L170-L174 and the 
- Svensson documentation here: 
https://github.com/lballabio/QuantLib/blob/c0fac242125283ac78984a21dd577e23823d23d6/ql/termstructures/yield/nonlinearfittingmethods.hpp#L115-L120
Corrected the documentation to follow the implementation.
> Correct documentation error in Svensson zero rate formula

- ql/experimental/math/hybridsimulatedannealing.hpp
The current code changes the local variable `localOptimizer` which was already used to initialize the member variable `localOptimizer_` and is no longer used. Also, `localOptimizer` was already used to initialize `optimizeScheme_`.
> Fix defaulting of localOptimizer in HybridSimulatedAnnealing

- ql/indexes/ibor/wibor.hpp
- ql/time/calendars/poland.cpp
- ql/time/calendars/poland.hpp
Hi Luigi, hi all,
I'm here since v1.23 and up until now I have been building my own version of library which has additional polish calendar which is in line with Warsaw Stock Exchange calendar (https://www.gpw.pl/session-details -> click tab Exchange holidays) which consists two more holidays than standard polish calendar that is: 24 December and 31 December. These are days without market session in Poland. It is not a big deal, but I thought that why not make PR in upstream repo.
I believe adding to library such WSE calendar would be small attraction for users calculating dates according to stock exchange calendar in Poland. 
Instead one Poland calendar I offered two: _Poland Settlement_ and _Warsaw stock exchange_. _Poland Settlement_ would be default one to keep backward compatibility, …
> Added Warsaw Stock Exchange Calendar (Poland)

- ql/qldefines.hpp
- ql/qldefines.hpp.cfg
The definition should be turned around as `clang` defines `__GNUC__` itself (in my case for `clang++18` to `__GNUC__ == 4`, probably to be underneath a valid `gcc` version).
More an esthetic PR as `clang` is able to handle the `_Pragma("GCC ...")` too.
> Change the order of `QL_DEPRECATED_...` macro definition

- ql/math/optimization/endcriteria.cpp
- ql/math/optimization/endcriteria.hpp
- ql/math/optimization/levenbergmarquardt.cpp
- ql/math/optimization/levenbergmarquardt.hpp
- ql/termstructures/globalbootstrap.hpp
- ql/termstructures/localbootstrap.hpp
Currently global bootstrap uses "accuracy" in several different ways:
* For all parameters passed to LevenbergMarquardt.
* For all epsilon parameters passed to EndCriteria.
* As the upper bound on the final value of the cost function.
This overloading makes it quite inflexible. Instead:
* Allow passing optimizer and EndCriteria to the constructor, which allows full control over all parameters.
* Instead of checking the final value of the cost function, check the result type from the optimizer.
Also, cleanup LevenbergMarquardt optimizer: remove commented out code, fix parameters passed to MINPACK.
> Improve global bootstrap optimizer configuration

- ql/time/calendars/southkorea.cpp
- test-suite/calendars.cpp
I have added a recent temporary holiday for the calendar SouthKorea.
Please refer to https://www.koreatimes.co.kr/www/biz/2024/10/602_382094.html (Though I couldn't find official information written in English, however it seems enough).
> added a recent temporary holiday

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/ibor/Makefile.am
- ql/indexes/ibor/all.hpp
- ql/indexes/ibor/kofr.cpp
- ql/indexes/ibor/kofr.hpp
Korea Overnight Financing Repo Rate (KOFR) published by Korea Securities Depository (KSD)
Please refer to
(1) https://www.bok.or.kr/eng/main/contents.do?menuNo=400399 (Overview)
(2) https://www.kofr.kr/main.jsp (Detailed information)
> Add the KOFR index

- ql/experimental/commodities/commodityindex.cpp
- ql/experimental/commodities/commodityindex.hpp
- ql/experimental/commodities/energybasisswap.cpp
- ql/experimental/commodities/energyfuture.cpp
- ql/experimental/commodities/energyvanillaswap.cpp
The whole commodities folder should be examined, but for the time being I'm ensuring the index doesn't get in the way of #2085.
> Inherit CommodityIndex from Index

- ql/cashflows/digitalcoupon.cpp
- ql/cashflows/overnightindexedcouponpricer.cpp
- ql/experimental/commodities/commodityindex.cpp
- ql/index.cpp
- ql/index.hpp
- ql/indexes/equityindex.cpp
- ql/indexes/indexmanager.cpp
- ql/indexes/indexmanager.hpp
- ql/indexes/inflationindex.cpp
- ql/indexes/interestrateindex.cpp
- ql/instruments/overnightindexfuture.cpp
- test-suite/indexes.cpp
- test-suite/shortratemodels.cpp
It will not be removed, but moved to the private section for use by `Index`.  Client code will go through indexes.
> Deprecate most of the `IndexManager` public interface.

- ql/experimental/inflation/yoycapfloortermpricesurface.hpp
- ql/termstructures/inflation/inflationtraits.hpp
- ql/termstructures/inflation/interpolatedyoyinflationcurve.hpp
- ql/termstructures/inflation/piecewiseyoyinflationcurve.hpp
- ql/termstructures/inflationtermstructure.cpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
- test-suite/inflationcapfloor.cpp
- test-suite/inflationcapflooredcoupon.cpp
- test-suite/inflationvolatility.cpp
Follows the changes in #1896 and #2073.  After those PRs the base date is passed explicitly, and the YoY indexes should now be asked for fixings only at the start of the month.  This makes `indexIsInterpolated` obsolete.  The old code still using it was deprecated in those two PRs and will be removed before `indexIsInterpolated` is.
> Deprecate `indexIsInterpolated` parameter in YoY inflation curves

- Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
- ql/instruments/makeois.cpp
- ql/termstructures/bootstraphelper.hpp
- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
- test-suite/overnightindexedswap.cpp
Add a second constructor overload to OISRateHelper which works like
DatedOISRateHelper. Deprecate DatedOISRateHelper.
This removes a lot of code duplication and also adds support for custom
pillar dates to DatedOISRateHelper's equivalent.
> Merge DatedOISRateHelper with OISRateHelper

- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
At the moment OISRateHelpers at construction call MakeOIS using a hardcoded Backward date generating rule.
The purpose of this pull request is to allow bootstrapping a curve such that the ois instruments are flexible to use either Forward or Backward DateGeneration rule, so that one can reprice consistently the OIS swaps that were used in building the curve (and with the correct dates such as SOFR swaps for example).  Defaults to Backward (i.e as it currently is)
> Add date generation rule to OISRateHelper constructor

- ql/termstructures/yield/fittedbonddiscountcurve.cpp
- ql/termstructures/yield/fittedbonddiscountcurve.hpp
- test-suite/fittedbonddiscountcurve.cpp
> Don't require helpers when passing fixed parameters to fitted bond curve

- ql/math/matrixutilities/choleskydecomposition.cpp
- ql/math/randomnumbers/zigguratgaussianrng.hpp
- ql/pricingengines/basket/choibasketengine.cpp
- ql/pricingengines/basket/denglizhoubasketengine.cpp
- ql/pricingengines/basket/singlefactorbsmbasketengine.cpp
- test-suite/basketoption.cpp
- test-suite/callablebonds.cpp
- test-suite/matrices.cpp
This PR makes the use of `Real` explicit throughout recently changed lines in QuantLib, to keep it compatible with AD tools which replace `Real` with another type.
> Fix datatypes for consistent Real usage, keeping AD compatibility

- ql/math/optimization/costfunction.hpp
- ql/termstructures/globalbootstrap.hpp
It allows to turn any functor, usually a lambda, into a CostFunction. This makes it simpler to define optimization problems.
> Add SimpleCostFunction

- ql/instruments/assetswap.cpp
- ql/instruments/assetswap.hpp
- test-suite/assetswap.cpp
> Allow use of risk-free rates in asset swaps

- ql/termstructures/globalbootstrap.hpp
- ql/termstructures/yield/bootstraptraits.hpp
Currently global bootstrap uses minValueAfter/maxValueAfter methods from Traits to come up with lower/upper bounds. This is problematic. These methods depend on the previous point in the curve. In the iterative bootstrap these methods are called after the previous point is already known exactly. However, in the global bootstrap all points are still filled with Traits::initialValue. This makes the bounds too tight and leads to bad results for curves with higher interest rates.
Instead add separate minValueGlobal/maxValueGlobal methods that do not rely on previous data.
> Fix lower/upper bounds for global bootstrap

- ql/termstructures/globalbootstrap.hpp
- ql/termstructures/yield/bootstraptraits.hpp
Also, use exp instead of atan transformation for discount factors. This is an improvement on #2120 based on these observations:
* Rates-based traits don't need any constraints in the optimization, so we don't need any transformation with them. This removes unnecessary computations.
* Discount factors are only bounded on one side (have to be positive), so instead of estimating a max value to use atan, we can simply use exp. This is faster and uses fewer magic numbers.
Another issue with atan is that it changes the gradients too much when the value is far from the middle of the range. This pushes optimization away from the correct solution when rates are low. This makes it hard to find value of maxDF that works for both very low and very high rates.
> Move transformation used in GlobalBootstrap into Traits

- ql/termstructures/inflation/piecewiseyoyinflationcurve.hpp
- ql/termstructures/inflation/piecewisezeroinflationcurve.hpp
- test-suite/inflation.cpp
So far the inflation bootstrap was done as a side effect of calling `checkRange`, but that would be skipped if extrapolation was enabled and the base date was fixed.
> Ensure that inflation curves are bootstrapped before access

- ql/termstructures/bootstraphelper.hpp
- ql/termstructures/yield/ratehelpers.cpp
- ql/termstructures/yield/ratehelpers.hpp
- test-suite/piecewiseyieldcurve.cpp
This is useful for non-standard conventions and to avoid dependency on evaluation date.
> Add DepositRateHelper and FraRateHelper constructors with fixed dates

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/termstructures/Makefile.am
- ql/termstructures/all.hpp
- ql/termstructures/globalbootstrap.hpp
- ql/termstructures/globalbootstrapvars.cpp
- ql/termstructures/globalbootstrapvars.hpp
- test-suite/piecewiseyieldcurve.cpp
This is useful to find model parameters used by rate helpers, for example, convexity adjustments for futures.
This change adds a generic interface (AdditionalBootstrapVariables) and a specific implementation for variables implemented as SimpleQuotes (SimpleQuoteVariables).
> Allow optimizing additional variables during global bootstrap

- ql/handle.hpp
So it does not have to be added in SWIG[1].
[1] https://github.com/lballabio/QuantLib-SWIG/blob/7d8d4c6c3bc71c195719a4df81b0650e60578da1/SWIG/common.i#L128
> Add RelinkableHandle::reset()

- LICENSE.TXT
- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/ibor/Makefile.am
- ql/indexes/ibor/all.hpp
- ql/indexes/ibor/saron.cpp
- ql/indexes/ibor/saron.hpp
Added the `SARON` ([Swiss Average Rate Overnight](https://www.snb.ch/en/the-snb/mandates-goals/statistics/statistics-pub/current_interest_exchange_rates#t00)) index to the QuantLib library.
> Add the SARON index

- ql/math/linearleastsquaresregression.hpp
- test-suite/linearleastsquaresregression.cpp
View `test-suite/linearleastsquaresregression.cpp::226`:
```c++
boost::circular_buffer<Real> cx(x.begin(), x.end()), cy(y.begin(), y.end());
LinearRegression m1(cx, cy); // here
for (Size i=0; i < 2; ++i) {
// ...
```
Which calls this constructor:
```c++
template <class xContainer, class yContainer> inline
LinearRegression::LinearRegression(const xContainer& x, 
const yContainer& y, Real intercept) 
: GeneralLinearLeastSquares(x, y,
details::LinearFcts<xContainer, 
std::is_arithmetic<typename xContainer::value_type>::value>
(x, intercept).fcts()) {
}
```
The unary type trait resolves which constructor be used for `LinearFcts`, 1d or multi-dimensional.
The idea is to modernise the logic by applying some C++17 best practices. We join the constructors into one, and differentiate 1d and …
> Modernising Tag-Dispatch template with C++17 constexpr if for LinearRegression

- ql/pricingengines/barrier/analyticpartialtimebarrieroptionengine.cpp
I don't know why, but **only** the debug build on Windows complains about:
```
[2/25] Building CXX object ql\CMakeFiles\ql_library.dir\pricingengines\barrier\analyticpartialtimebarrieroptionengine.cpp.obj
FAILED: ql/CMakeFiles/ql_library.dir/pricingengines/barrier/analyticpartialtimebarrieroptionengine.cpp.obj
ccache.exe C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1443~1.348\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DNOMINMAX -DQL_COMPILATION -D_CRT_SECURE_NO_WARNINGS -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -IE:\Users\rke\cpp\QuantLib.rke.master\build\debug -IE:\Users\rke\cpp\QuantLib.rke.master -external:IE:\Tools\boost_1_88_0 -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -std:c++17 -MTd -W3 /wd4267 /wd4819 /wd26812 /w34127 /w34702 /w35262 -WX …
```
> `analyticpartialtimebarrieroptionengine.cpp(108) : warning C4702: unreachable code`

- ql/currencies/america.cpp
Fixed #2209 issue: assigns the `mxvData` shared pointer to the `data_` member variable in the `MXVCurrency` constructor.
> Added missing assignment in MXVCurrency constructor

- ql/termstructures/yield/oisratehelper.cpp
- ql/termstructures/yield/oisratehelper.hpp
- test-suite/overnightindexedswap.cpp
Replaced the `Spread` type with `Handle<Quote>` for the `overnightSpread` parameter as requested in https://github.com/lballabio/QuantLib/issues/1681.
What did you mean in this line? What can be improved? Because I've taken inspiration from this code to write `impliedQuote` in `OISRateHelper`
https://github.com/lballabio/QuantLib/blob/4655f19ca2816c3c5f7b43fca4daf947719baf56/ql/termstructures/yield/ratehelpers.cpp#L745
> Added `Handle<Quote>` for spread in `OISRateHelper`

- ql/methods/finitedifferences/stepconditions/fdmsimplestoragecondition.cpp
AD tools use lazy evaluation to optimise large expressions. For example:
```c++
xad::AReal<double> = 1.0 * 2.0;
```
is first of `BinaryExpr` type before becoming `AReal`. This works fine but causes issues for initializer lists. Here:
```c++
xad::AReal x = 1.0, y = 2.0, z = 3.0;
auto vec = max({x, y + z});
```
breaks because `x` is of type `AReal` and `y + z` is of type `BinaryExpr` and so the compiler can't resolve an overload for `max`. This PR fixes this by casting `y + z` (equivalent) to `Real` such that the compiler doesn't struggle with this resolve.
> AD Initializer List Fix

- ql/experimental/finitedifferences/fdmvppstepconditionfactory.cpp
- ql/experimental/processes/extendedblackscholesprocess.cpp
- ql/experimental/processes/extendedornsteinuhlenbeckprocess.cpp
- ql/instruments/overnightindexfuture.cpp
- ql/models/equity/hestonslvfdmmodel.cpp
- ql/pricingengines/barrier/analyticpartialtimebarrieroptionengine.cpp
Greetings, I found these minor code-smells working with static analyzers on the Quantlib.
These changes shouldn't affect functionality, whilst improving a bit of the readability. I have reviewed some of the code and seems like you don't have a defined style for break clauses, so I think these changes might help homogenize the code.
The rationale behind these changes are that there shouldn't be unreachable code:
- MISRA C:2012, 2.1 - A project shall not contain unreachable code
- CWE - [CWE-561 - Dead Code](https://cwe.mitre.org/data/definitions/561)
- [CERT, MSC12-C.](https://wiki.sei.cmu.edu/confluence/x/5dUxBQ) - Detect and remove code that has no effect or is never executed
Thank you for your time and for reviewing this change.
> Remove dangling unreachable break clauses

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/quote.cpp
- ql/utilities/Makefile.am
- ql/utilities/all.hpp
- ql/utilities/variants.hpp
Simplify usage of std::visit using a helper visitor type as shown in https://en.cppreference.com/w/cpp/utility/variant/visit2
This also catches unknown types at compile-time instead of run-time even on older compilers.
> Make unexpected types in quote variant a compile-time error

- QuantLib.vcxproj
- QuantLib.vcxproj.filters
- ql/CMakeLists.txt
- ql/indexes/ibor/Makefile.am
- ql/indexes/ibor/all.hpp
- ql/indexes/ibor/custom.cpp
- ql/indexes/ibor/custom.hpp
- ql/indexes/ibor/eurlibor.cpp
- ql/indexes/ibor/eurlibor.hpp
- ql/indexes/ibor/libor.cpp
- test-suite/indexes.cpp
This is a LIBOR-like index that allows specifying custom calendars for value and maturity dates calculations. This is useful, for example, when using vendor calendars instead of the built-in ones.
Also, add missing EURLibor::clone().
> Add CustomIborIndex

- ql/time/daycounters/thirty360.cpp
- test-suite/daycounters.cpp
The checks should be done in the specific order. Alternatively, the rule
if (dd2 == 31 && dd1 >= 30) dd2 = 30;
can be changed to
if (dd2 == 31 && (dd1 >= 30 || isLastOfFebruary(d1))) dd2 = 30;
> Fix 30/360 USA calculation

- ql/instruments/makeois.cpp
- test-suite/overnightindexedswap.cpp
This change addresses the second portion of #1695 by updating OISRateHelper to mirror the behavior introduced in MakeOIS. When settlementDays is unspecified, index-specific defaults are applied: 0 for SONIA and CORRA, 2 otherwise. This PR adds test coverage to confirm expected start dates under these defaults. It also includes two new assertions in testMakeOISDefaultSettlementDays to verify that manual settlement overrides continue to take precedence.
> Enhance MakeOIS default settlement days test and use settlement days t+1 for CORRA

- ql/instruments/makeois.cpp
- ql/instruments/makeois.hpp
- ql/instruments/makevanillaswap.cpp
- ql/instruments/makevanillaswap.hpp
- ql/utilities/null.hpp
This allows using it as a constant expression and guarantees constant folding.
> Make Null constexpr

- ql/math/rounding.cpp
To allow `Real` to be types other than `double`, including AAD active datatypes, which might not have a `constexpr` constructor, this uses `double` explicitly for the power of 10 lookup table. 
As the table is `constexpr`, this comes at no cost and will also work well with non-double `Real` datatypes.
Note: This fixes the [QuantLib-Risks-Cpp pipeline](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/actions/workflows/ci.yaml) using AAD.
> Use double for constexpr to maintain AAD compatibility

- ql/termstructures/inflation/piecewisezeroinflationcurve.hpp
- ql/termstructures/inflationtermstructure.hpp
- test-suite/inflation.cpp
QuantLib's yield curves can be created before fetching market data, which allows creating complex object graphs ahead of time and setting market data (quotes and fixings) at a later stage. We use this feature extensively in our code.
The new API for PiecewiseZeroInflationCurve does not offer the same flexibility, since it requires baseDate to be set at the curve creation time. BaseDate comes from inflation fixings, which means that the fixings have to be fetched before the curve can be created.
Add another constructor for PiecewiseZeroInflationCurve, which takes a function that returns the baseDate. This function will be called during the curve's bootstrap, and the result will be cached. This allows one to construct PiecewiseZeroInflationCurve first and fetch the fixings at a later stage.
> Allow creating PiecewiseZeroInflationCurve before baseDate is known

- ql/methods/finitedifferences/meshers/uniform1dmesher.hpp
I ran into this while pricing an option in python and thought I could fix. Let me know if this should be done differently, I am not a C++ dev.
> Fix typo in uniform1dmesher

- test-suite/piecewiseyieldcurve.cpp
This uses the `QL_CHECK_CLOSE` macro consistently, which provides compatibility for cases when `Real` is not `double`. 
Fixes the [build with XAD](https://github.com/auto-differentiation/QuantLib-Risks-Cpp/actions/runs/17263209666/job/48989248131).
> Fix consistent test macro usage for AAD compatibility

- ql/pricingengines/futures/discountingperpetualfuturesengine.hpp
- test-suite/perpetualfutures.cpp
Apologies but found a naming error in the last pull request #2315 (`maxT_` → `maxT` in a parameter of a constructor).
> Fixing naming and styles in pull request #2315 (perpetual futures)

- ql/experimental/credit/defaultprobabilitylatentmodel.hpp
1. Improvement to Latent model execution time and the most heavy testGauss test/benchmark: boost::dynamic_bitset (std::vector) memory manipulations moved out of the hot loop. Times, for example:
<pre>
Before the improvement
NthToDefaultTests/testGauss  : 48.7896s
After the improvement
NthToDefaultTests/testGauss  : 27.3736s
</pre>
2. Trailing spaces removed.
> Improvement to Latent model execution time

- ql/pricingengines/futures/discountingperpetualfuturesengine.cpp
This makes the lambda return types explicit, which is required in case `Real` is an expression template type (for example for AAD), as the return type would be inconsistent otherwise.
> Explicit return type for lambdas to work with expression templates
