Examples/FRA/Makefile.am

Migrated from https://github.com/lballabio/quantlib-old/pull/373 by @MattPD

Remove hardcoded dependence from the FRA sample.

---

ql/math/matrixutilities/bicgstab.cpp

Migrated from https://github.com/lballabio/quantlib-old/pull/359 by @pcaspers

Fix error initialization, remove whitespaces

---

ql/time/calendars/saudiarabia.cpp

Migrated from https://github.com/lballabio/quantlib-old/pull/363 by @jrvarma

Improved Saudi Arabia calendar

---

ql/cashflows/lineartsrpricer.cpp
ql/cashflows/lineartsrpricer.hpp
ql/experimental/coupons/lognormalcmsspreadpricer.cpp
ql/experimental/coupons/lognormalcmsspreadpricer.hpp
ql/models/calibrationhelper.cpp
ql/models/calibrationhelper.hpp
ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp
ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp
ql/pricingengines/swaption/basketgeneratingengine.cpp
ql/pricingengines/swaption/blackswaptionengine.cpp
ql/pricingengines/swaption/blackswaptionengine.hpp
ql/termstructures/volatility/flatsmilesection.cpp
ql/termstructures/volatility/flatsmilesection.hpp
ql/termstructures/volatility/interpolatedsmilesection.hpp
ql/termstructures/volatility/swaption/spreadedswaptionvol.hpp
ql/termstructures/volatility/swaption/swaptionconstantvol.cpp
ql/termstructures/volatility/swaption/swaptionconstantvol.hpp
ql/termstructures/volatility/swaption/swaptionvolcube.hpp
ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
ql/termstructures/volatility/swaption/swaptionvolcube2.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp
ql/termstructures/volatility/swaption/swaptionvolstructure.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/264 by @pcaspers

Add normal volatilities for swaptions

---

ql/experimental/math/Makefile.am
ql/experimental/math/all.hpp
ql/experimental/math/laplaceinterpolation.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/367 by @pcaspers

Add Laplace interpolation

---

.gitignore
Makefile.am
configure.ac
quantlib.pc.in

Installs a metadata file for the pkg-config helper tool.

Generate pkg-config File

---

ql/processes/blackscholesprocess.cpp
ql/processes/blackscholesprocess.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/284 by @pcaspers

Exact calculations for Black Scholes process in the case of curves

---

ql/termstructures/volatility/optionlet/optionletstripper1.cpp
ql/termstructures/volatility/optionlet/optionletstripper1.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/328 by @mdriesch

Recompute switchstrike for caplets

---

ql/experimental/math/Makefile.am
ql/experimental/math/all.hpp
ql/experimental/math/piecewisefunction.hpp
ql/experimental/math/piecewiseintegral.cpp
ql/experimental/math/piecewiseintegral.hpp
test-suite/integrals.cpp
test-suite/integrals.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/329 by @pcaspers

Add piecewise integral and function

---

ql/cashflows/lineartsrpricer.cpp
ql/cashflows/lineartsrpricer.hpp
ql/experimental/coupons/lognormalcmsspreadpricer.cpp
ql/experimental/coupons/lognormalcmsspreadpricer.hpp
ql/instruments/swaption.cpp
ql/instruments/swaption.hpp
ql/models/calibrationhelper.cpp
ql/models/calibrationhelper.hpp
ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp
ql/models/shortrate/calibrationhelpers/swaptionhelper.hpp
ql/pricingengines/swaption/basketgeneratingengine.cpp
ql/pricingengines/swaption/blackswaptionengine.cpp
ql/pricingengines/swaption/blackswaptionengine.hpp
ql/termstructures/volatility/flatsmilesection.cpp
ql/termstructures/volatility/flatsmilesection.hpp
ql/termstructures/volatility/interpolatedsmilesection.hpp
ql/termstructures/volatility/swaption/spreadedswaptionvol.hpp
ql/termstructures/volatility/swaption/swaptionconstantvol.cpp
ql/termstructures/volatility/swaption/swaptionconstantvol.hpp
ql/termstructures/volatility/swaption/swaptionvolcube.hpp
ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
ql/termstructures/volatility/swaption/swaptionvolcube2.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp
ql/termstructures/volatility/swaption/swaptionvolstructure.hpp

closes #41, this PR depends on (i.e. contains) #7

add normal implied volatility calculation for swaption instrument

---

ql/settings.hpp
test-suite/asianoptions.cpp
test-suite/chooseroption.cpp
test-suite/compoundoption.cpp
test-suite/digitalcoupon.cpp
test-suite/forwardoption.cpp
test-suite/quantlibtestsuite.cpp

Migrated from https://github.com/lballabio/quantlib-old/pull/313 by @pcaspers

Freeze evaluation date for test suite

---

test-suite/hestonslvmodel.cpp
test-suite/paralleltestrunner.hpp
test-suite/riskneutraldensitycalculator.cpp

increased test tolerance to incorporate the Monte-Carlo noise

 added test suite return value for parallel test runner 

---

test-suite/basketoption.cpp
test-suite/basketoption.hpp
test-suite/cdo.cpp
test-suite/cdo.hpp
test-suite/marketmodel.cpp
test-suite/marketmodel.hpp

to allow faster execution in conjunction with the parallel unit test runner

subdivided long running tests into smaller pieces 

---

ql/math/generallinearleastsquares.hpp

taken from Peter's implementation of Moore-Penrose inverse.

better threshold for pseudo inverse 

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/experimental/math/Makefile.am
ql/experimental/math/fireflyalgorithm.cpp
ql/experimental/math/fireflyalgorithm.hpp
ql/experimental/math/hybridsimulatedannealing.hpp
ql/experimental/math/hybridsimulatedannealingfunctors.hpp
ql/experimental/math/isotropicrandomwalk.hpp
ql/experimental/math/levyflightdistribution.hpp
ql/experimental/math/particleswarmoptimization.cpp
ql/experimental/math/particleswarmoptimization.hpp

4 Different Global Optimizers with various flavours: simulated annealing, particle swarm optimization, firefly algorithm, and differential evolution.
Hybrid Simulated Annealing: a Boltzmann-like simulated annealing optimizer, and which also takes a possible local optimizer to run upon finding a new best solution.
Particle Swarm Optimization (PSO) of different varieties
- Canonical PSO (with constriction factor or inertia factor)
- Three different topologies are provided: global, k-neighbors, and clubs
- Different inertia implementations are provided: trivial constant inertia, simple random inertia, decreasing inertia by iteration, adaptive inertia, and a levy flight inertia.
A hybrid Firefly Algorithm (FA) that mixes FA with a Differential Evolution (DE) optimizer. The population is …

Global Optimizers

---

ql/math/interpolations/loginterpolation.hpp
ql/math/interpolations/mixedinterpolation.hpp

Migrated from https://github.com/lballabio/quantlib-old/pull/372 by @sfondi

LogMixedLinearCubic interpolation added

---

ql/experimental/variancegamma/fftengine.cpp
ql/math/fastfouriertransform.hpp

Fix warnings at bitshifts on x64

---

ql/instruments/floatfloatswap.cpp
ql/instruments/nonstandardswap.cpp
ql/pricingengines/swaption/gaussian1dnonstandardswaptionengine.cpp

a few fixes for the case that intermediate capital exchange is used in the instruments

fix g1d engine and instruments

---

ql/cashflows/cashflows.cpp

it is implicitly assumed that the cashflow vector is sorted, so we ensure this before the calculation

ensure sorted leg for yield based npv calculation

---

ql/math/interpolations/cubicinterpolation.hpp
ql/math/interpolations/loginterpolation.hpp

Added new interpolation technique: Harmonic Cubic Splines.
For details see: Stable Interpolation for the Yield Curve- Fabien Le Floc'h (2013)

Harmonic Spline Interpolation

---

ql/indexes/ibor/usdlibor.hpp
ql/time/calendars/unitedstates.cpp
ql/time/calendars/unitedstates.hpp

There seem to be more changes regarding Libor holidays, which we are analysing currently and hopefully send a PR for them soon too.

Update 4th July handling for US Libor Fixings (thanks to Oleg Kulkov)

---

ql/math/integrals/discreteintegrals.cpp
ql/math/integrals/discreteintegrals.hpp
ql/pricingengines/vanilla/analytichestonengine.cpp
ql/pricingengines/vanilla/analytichestonengine.hpp
test-suite/hestonmodel.cpp
test-suite/hestonmodel.hpp
test-suite/integrals.cpp
test-suite/integrals.hpp

1. changed c_inf max value for Gauss-Lobatto integration
2. added discrete Simpson and Trapezoid integration of the
characteristic function

Small Heston engine improvements

---

ql/time/calendars/unitedkingdom.hpp

Hope you don't mind the small PR to fix a typo :)

Typo: kindgom -> kingdom

---

ql/math/matrixutilities/tqreigendecomposition.cpp

Get rid of a compiler warning.

Fix annoying compiler warning about shadow variable.

---

.travis.yml
ql/cashflows/rangeaccrual.cpp
ql/experimental/averageois/makearithmeticaverageois.cpp
ql/experimental/credit/randomdefaultlatentmodel.hpp
ql/math/randomnumbers/faurersg.cpp
ql/models/marketmodels/pathwisegreeks/ratepseudorootjacobian.cpp
test-suite/marketmodel.cpp
test-suite/swapforwardmappings.cpp

This allows to check the code on a number of Boost and gcc versions.

Use a build matrix in the Travis CI run.

---

ql/pricingengines/swaption/blackswaptionengine.hpp

- remove some comments that are outdated since the deprecated methods
referenced in them are already removed
- more precise assumption about exercise date and swap start date

amend comments

---

ql/time/calendars/hongkong.cpp

Following the discussion here
[http://quantlib.10058.n7.nabble.com/HKD-Calendar-td18387.html](http://quantlib.10058.n7.nabble.com/HKD-Calendar-td18387.html)

Fix hkd calendar

---

ql/time/calendars/hongkong.cpp

source: https://www.gov.hk/en/about/abouthk/holiday/
also checked with Bloomberg.

Hong Kong Calendar updated till 2020

---

ql/time/daycounters/actual365fixed.cpp
ql/time/daycounters/actual365fixed.hpp
ql/time/daycounters/actual365nl.hpp

Add Act/365 (no leap) to Actual365Fixed class.

---

ql/cashflows/cashflowvectors.hpp
ql/cashflows/iborcoupon.cpp
ql/cashflows/iborcoupon.hpp

Changes to allow for Payment Lag, Payment Adjustment and Payment Calendar on FloatingLeg. Similar to PR#295.

Add payment lag to FloatingLeg and IborCoupon

---

ql/time/calendars/unitedstates.cpp

Fix UnitedStates calendar selection.

Fix UnitedStates calendar selection

---

ql/termstructures/iterativebootstrap.hpp
test-suite/piecewiseyieldcurve.cpp
test-suite/piecewiseyieldcurve.hpp

Perform clean bootstrap when using the previous curve as guess fails.

---

ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/oisratehelper.hpp

Fixes #318.
Extended configuration options as allowed by MakeOIS

Updated implementation of OISRateHelper

---

test-suite/inflation.cpp

This pull request closes #229 .
Please review and let me know if something has to be added/changed.

Inflation period test

---

ql/cashflows/couponpricer.cpp
ql/cashflows/couponpricer.hpp
ql/experimental/coupons/lognormalcmsspreadpricer.cpp
ql/experimental/coupons/swapspreadindex.cpp
ql/experimental/coupons/swapspreadindex.hpp

Bug fixes (from branch freeFixingDate)

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/time/calendars/Makefile.am
ql/time/calendars/botswana.cpp
ql/time/calendars/botswana.hpp

Holiday rules documented in http://www.ilo.org/dyn/travail/docs/1766/Public%20Holidays%20Act.pdf

Add Botswana calendar implementation

---

ql/math/distributions/chisquaredistribution.cpp
ql/math/distributions/chisquaredistribution.hpp
ql/methods/finitedifferences/meshers/fdmhestonvariancemesher.cpp
ql/processes/hestonprocess.cpp

Renamed InverseNonCentralChiSquareDistribution

---

ql/time/calendar.cpp
ql/time/calendar.hpp
test-suite/calendars.cpp
test-suite/calendars.hpp

fixed issue 346: Holidays and --enable-intraday

---

ql/currencies/Makefile.am
ql/currencies/all.hpp
ql/currencies/crypto.cpp
ql/currencies/crypto.hpp
ql/pricingengines/vanilla/analytichestonengine.cpp

Add the most popular crypto currencies support.

add crypto currency support

---

ql/instruments/bonds/btp.hpp

Should inherit publicly from Lazy Object

Correct RendistatoCalculator declaration

---

ql/time/calendar.hpp

I took a stab at changing the documentation for #376.
Fixes #376.

Update documentation for Calendar::isEndOfMonth

---

ql/experimental/variancegamma/analyticvariancegammaengine.cpp
ql/experimental/variancegamma/analyticvariancegammaengine.hpp

occasionaly there is a singularity at 0 and the simpson integrtor
couldnt handle it

fixed crash in analytic VarianceGamma engine

---

test-suite/shortratemodels.cpp
test-suite/shortratemodels.hpp

added CIR++ test case

---

ql/experimental/coupons/quantocouponpricer.cpp

If the index is Euribor, the dc used to compute t1 is A360 which is inappropriate if the vol ts has a dc A365F, so I switch to the caplet vol ts's dc. If the FX vol ts has a different dc, this is inconsistent again, but we have to go for one of the dcs and usually vol ts have A365F as per market conventions anyway I believe. However, better read the FX vol by date instead of t1 nevertheless to get the vol on the relevant date in every case.
Furthermore the volatility type was always assumed to be lognormal with zero shift, I added treatment for shifted vols and normal vols.

Fix Quanto Coupon Pricer 

---

ql/math/matrixutilities/svd.cpp

replace bit operator with logical operator in if conditions
Closes #411

fix bit operator

---

ql/cashflows/capflooredcoupon.cpp
ql/cashflows/capflooredcoupon.hpp
ql/cashflows/floatingratecoupon.cpp
ql/cashflows/floatingratecoupon.hpp
ql/event.hpp
ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/ratehelpers.cpp

lazy evaluation for floating rate coupons

---

ql/processes/gsrprocess.cpp

see the referenced ssrn, formula 1.4

fix drift in gsr process (thanks to Seung Beom Bang for the heads up)

---

ql/experimental/credit/interpolatedaffinehazardratecurve.hpp
ql/experimental/credit/onefactoraffinesurvival.hpp

Base constructor not being called.

Base constructor call in  interpolatedaffinehazardratecurve missing

---

ql/pricingengines/vanilla/fddividendengine.hpp

Fix Solaris Studio 12.5 c++11 build

---

.travis.yml
ql/experimental/varianceoption/integralhestonvarianceoptionengine.cpp
ql/models/marketmodels/products/multistep/multistepinversefloater.cpp
ql/models/marketmodels/products/multistep/multistepinversefloater.hpp
ql/models/marketmodels/products/multistep/multistepratchet.cpp
ql/models/marketmodels/products/multistep/multistepratchet.hpp
ql/models/marketmodels/products/multistep/multistepswap.cpp
ql/models/marketmodels/products/multistep/multistepswap.hpp
ql/models/marketmodels/products/onestep/onestepcoterminalswaps.hpp
ql/models/marketmodels/products/pathwise/pathwiseproductinversefloater.cpp
ql/models/marketmodels/products/pathwise/pathwiseproductinversefloater.hpp

This also requires fixing a few new warnings reported by Clang 6.

Update Docker images for Travis CI run.

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/indexes/ibor/all.hpp
ql/indexes/ibor/mosprime.hpp
ql/indexes/ibor/pribor.hpp
ql/indexes/ibor/robor.hpp
ql/indexes/ibor/wibor.hpp

Add Mosprime, Pribor, Robor and Wibor indices.

Add Further indices

---

ql/cashflows/capflooredcoupon.cpp
ql/cashflows/capflooredcoupon.hpp
ql/cashflows/floatingratecoupon.cpp
ql/cashflows/floatingratecoupon.hpp
ql/event.hpp
ql/instruments/bond.cpp
ql/instruments/capfloor.cpp
ql/instruments/swap.cpp
ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/ratehelpers.cpp

Roll back lazy frc

---

ql/experimental/credit/syntheticcdo.cpp

This is a minor fix. 
Fixes #365.

Errors in synthetic CDO implementation

---

ql/math/optimization/differentialevolution.cpp

This allows tests to be reproducible given a seed.
Fixed #413.

Use the provided RNG to randomize candidates.

---

ql/math/interpolation.hpp
ql/math/interpolations/abcdinterpolation.hpp
ql/math/interpolations/backwardflatinterpolation.hpp
ql/math/interpolations/backwardflatlinearinterpolation.hpp
ql/math/interpolations/bicubicsplineinterpolation.hpp
ql/math/interpolations/bilinearinterpolation.hpp
ql/math/interpolations/convexmonotoneinterpolation.hpp
ql/math/interpolations/cubicinterpolation.hpp
ql/math/interpolations/flatextrapolation2d.hpp
ql/math/interpolations/forwardflatinterpolation.hpp
ql/math/interpolations/interpolation2d.hpp
ql/math/interpolations/kernelinterpolation.hpp
ql/math/interpolations/kernelinterpolation2d.hpp
ql/math/interpolations/lagrangeinterpolation.hpp
ql/math/interpolations/linearinterpolation.hpp
ql/math/interpolations/loginterpolation.hpp
ql/math/interpolations/mixedinterpolation.hpp
ql/math/interpolations/sabrinterpolation.hpp
ql/time/daycounters/actualactual.hpp

Documentation fixes

---

test-suite/Makefile.am

Remove color from test suite output

---

test-suite/hestonslvmodel.cpp
test-suite/quantlibbenchmark.cpp
test-suite/solvers.cpp

 fixed test failure in Heston SLV on FreeBSD-11

---

ql/methods/finitedifferences/bsmoperator.cpp
ql/methods/finitedifferences/bsmoperator.hpp
ql/methods/finitedifferences/operatorfactory.hpp
ql/pricingengines/vanilla/fdvanillaengine.cpp
test-suite/europeanoption.cpp
test-suite/europeanoption.hpp
test-suite/operators.cpp

Extract correct constant coefficients from BS process for use in FD engine.

---

ql/time/daycounters/actual365fixed.cpp
test-suite/daycounters.cpp
test-suite/daycounters.hpp

Avoid division by zero.

---

ql/time/daycounters/actual365fixed.cpp

Short-circuit calculation in degenerate case.

---

.lgtm.yml
ql/cashflows/cashflows.hpp
ql/cashflows/conundrumpricer.cpp
ql/experimental/credit/homogeneouspooldef.hpp
ql/experimental/credit/inhomogeneouspooldef.hpp
ql/experimental/credit/riskybond.cpp
ql/experimental/credit/riskybond.hpp
ql/experimental/inflation/yoyinflationoptionletvolatilitystructure2.hpp
ql/experimental/math/hybridsimulatedannealingfunctors.hpp
ql/math/sampledcurve.hpp
ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp
ql/models/volatility/garch.cpp
ql/pricingengines/bond/bondfunctions.hpp
ql/pricingengines/credit/isdacdsengine.cpp
ql/termstructures/iterativebootstrap.hpp
ql/termstructures/volatility/atmadjustedsmilesection.hpp

See https://lgtm.com/projects/g/lballabio/QuantLib/alerts/

Fix a few errors and warnings from LGTM

---

ql/pricingengines/basket/mcamericanbasketengine.hpp

needed for PR https://github.com/lballabio/QuantLib-SWIG/pull/141

added polynom order and polynomType to MCAmerianBasketEngine

---

ql/quotes/compositequote.hpp
ql/quotes/derivedquote.hpp

lets you construct quotes using std::plus<Real> etc. more easily

Add helper functions for derived and composite quotes

---

ql/time/calendars/unitedstates.cpp

Fix for #576 adding the funeral holiday for equity, bond, and related derivatives

Add Day of Mourning for George HW Bush to Special US Holidays

---

test-suite/basismodels.cpp

See <https://travis-ci.org/lballabio/QuantLib/builds/479914804>.

Fix a few test-suite errors when compiling with non-standard flags

---

ql/methods/finitedifferences/operatorfactory.hpp

Avoid deprecation warning in VC++.

---

ql/time/calendars/taiwan.cpp

According to the website of Taiwan Stock Exchange Corporation.

Update the holidays of Taiwan to 2019.

---

Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp

Thanks to Theo Boafo for the heads up.

Fix quotes used in bootstrap example.

---

ql/processes/batesprocess.cpp

fixed Bates process for Broadie-Kaya discretization 

---

QuantLib.props
ql/auto_link.hpp

Support for Visual Studio 2019 (platform toolset 14.2)

Build with Visual Studio 2019 (vc14.2)

---

ql/legacy/libormarketmodels/liborforwardmodel.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.cpp
ql/termstructures/volatility/swaption/swaptionvolmatrix.hpp

Deprecate SwaptionVolatilityMatrix constructor without calendar.

---

ql/experimental/commodities/paymentterm.hpp

implement inspector calendar() in PaymentTerm

fix PaymentTerm.calendar() inspector

---

ql/methods/finitedifferences/utilities/fdminnervaluecalculator.cpp
ql/methods/finitedifferences/utilities/fdminnervaluecalculator.hpp
ql/pricingengines/vanilla/fdcevvanillaengine.cpp
test-suite/fdsabr.cpp

Replace some leftover boost::function types.

---

ql/experimental/models/hestonslvfdmmodel.cpp
test-suite/hestonslvmodel.cpp

Many thanks to Peter for the hint.

avoid uninitialised value read access

---

ql/time/calendars/unitedkingdom.cpp

Thanks to user Vililikku for the heads-up.
Closes #658.

Add a couple of exceptions for UK holidays.

---

ql/time/schedule.cpp
test-suite/schedule.cpp
test-suite/schedule.hpp

Allow stub date to equal maturity.

---

ql/termstructures/yield/oisratehelper.cpp
test-suite/overnightindexedswap.cpp

Take payment date into account to calculate curve node.

---

CMakeLists.txt
acinclude.m4
test-suite/CMakeLists.txt
test-suite/Makefile.am
test-suite/asianoptions.cpp
test-suite/basketoption.cpp
test-suite/digitaloption.cpp
test-suite/europeanoption.cpp
test-suite/extendedtrees.cpp
test-suite/lowdiscrepancysequences.cpp
test-suite/quantlibbenchmark.cpp
test-suite/quantlibtestsuite.cpp
test-suite/utilities.hpp

Use new-style Boost timer

---

ql/cashflows/capflooredcoupon.hpp
ql/cashflows/cashflowvectors.hpp
ql/cashflows/cmscoupon.cpp
ql/cashflows/cmscoupon.hpp
ql/cashflows/floatingratecoupon.cpp
ql/cashflows/floatingratecoupon.hpp
ql/cashflows/iborcoupon.cpp
ql/cashflows/iborcoupon.hpp
ql/experimental/coupons/cmsspreadcoupon.cpp
ql/experimental/coupons/cmsspreadcoupon.hpp
ql/instruments/bonds/floatingratebond.cpp
ql/instruments/bonds/floatingratebond.hpp
test-suite/bonds.cpp

Excoupon functionality for FloatingRateBonds
Let me know if you have any feedback

Ex Coupon functionality for FloatingRateBond

---

Examples/EquityOption/EquityOption.cpp
ql/instruments/dividendvanillaoption.cpp
ql/instruments/vanillaoption.cpp
ql/pricingengines/vanilla/fdamericanengine.hpp
ql/pricingengines/vanilla/fdbermudanengine.hpp
ql/pricingengines/vanilla/fddividendamericanengine.hpp
ql/pricingengines/vanilla/fddividendeuropeanengine.hpp
ql/pricingengines/vanilla/fdeuropeanengine.hpp
test-suite/americanoption.cpp
test-suite/dividendoption.cpp
test-suite/europeanoption.cpp
test-suite/europeanoption.hpp
test-suite/hestonmodel.cpp
test-suite/mclongstaffschwartzengine.cpp
test-suite/quantlibbenchmark.cpp

Deprecate a few old-style FD engines.

---

ql/experimental/coupons/subperiodcoupons.hpp
ql/experimental/credit/basket.cpp
ql/experimental/credit/basket.hpp
ql/experimental/credit/distribution.cpp

Clean up a few undefined methods

---

ql/methods/finitedifferences/meshers/fdmblackscholesmesher.cpp
ql/methods/finitedifferences/meshers/fdmblackscholesmesher.hpp
ql/pricingengines/vanilla/analyticdividendeuropeanengine.cpp
ql/pricingengines/vanilla/fdblackscholesvanillaengine.cpp
ql/pricingengines/vanilla/fdblackscholesvanillaengine.hpp
ql/pricingengines/vanilla/fdhestonvanillaengine.cpp
ql/pricingengines/vanilla/fdhestonvanillaengine.hpp
test-suite/dividendoption.cpp
test-suite/dividendoption.hpp
test-suite/hestonmodel.cpp

and fix for AnalyticDividendEuropeanEngine if cash dividend and dividend yield is given at the same time. Solves https://github.com/lballabio/QuantLib/issues/694

added escrowed dividend model to Black-Scholes-Merton PDE engine

---

ql/time/calendars/sweden.cpp

sweden national holiday issue 676

---

ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/oisratehelper.hpp
test-suite/overnightindexedswap.cpp
test-suite/overnightindexedswap.hpp

Add pillar choice to OIS rate helpers.

---

ql/time/calendar.cpp
ql/time/calendar.hpp
ql/time/daycounter.hpp

This will make it slightly easier for me to track down setup bugs in my code.

Tweak assertion messages to indicate what implementation has not been provided

---

test-suite/andreasenhugevolatilityinterpl.cpp
test-suite/andreasenhugevolatilityinterpl.hpp
test-suite/quantlibbenchmark.cpp

thanks to Peter Caspers for the idea and sharing of code.

added high precision flat vol test case for Andreasen-Huge interpolation

---

.appveyor.yml
.appveyor/Unity.props
.appveyor/VS2013.props
.appveyor/VS2019.props
.gitignore
Examples/BasketLosses/BasketLosses.vcxproj
Examples/BermudanSwaption/BermudanSwaption.vcxproj
Examples/Bonds/Bonds.vcxproj
Examples/CDS/CDS.vcxproj
Examples/CVAIRS/CVAIRS.vcxproj
Examples/CallableBonds/CallableBonds.vcxproj
Examples/ConvertibleBonds/ConvertibleBonds.vcxproj
Examples/DiscreteHedging/DiscreteHedging.vcxproj
Examples/EquityOption/EquityOption.vcxproj
Examples/FRA/FRA.vcxproj
Examples/FittedBondCurve/FittedBondCurve.vcxproj
Examples/Gaussian1dModels/Gaussian1dModels.vcxproj
Examples/GlobalOptimizer/GlobalOptimizer.vcxproj
Examples/GlobalOptimizer/GlobalOptimizer.vcxproj.filters
Examples/LatentModel/LatentModel.vcxproj
Examples/MarketModels/MarketModels.vcxproj
Examples/MulticurveBootstrapping/MulticurveBootstrapping.vcxproj
Examples/MultidimIntegral/MultidimIntegral.vcxproj
Examples/Replication/Replication.vcxproj
Examples/Repo/Repo.vcxproj
QuantLib.vcxproj
test-suite/testsuite.vcxproj

See <https://devblogs.microsoft.com/cppblog/support-for-unity-jumbo-files-in-visual-studio-2017-15-8-experimental/>.

Enable unity build for VC++ 2017 and above.

---

ql/termstructures/credit/piecewisedefaultcurve.hpp
ql/termstructures/iterativebootstrap.hpp
test-suite/piecewiseyieldcurve.cpp
test-suite/piecewiseyieldcurve.hpp

An alternative to #710. 
Fixes #613.
Fixes #632.

Pass min and max value to bootstrap algorithm

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/time/calendars/Makefile.am
ql/time/calendars/all.hpp
ql/time/calendars/austria.cpp
ql/time/calendars/austria.hpp

Added austrian holidays to the calendar (settlement + stock exchange)

Added Austrian calendar

---

ql/time/daycounters/thirty360.cpp
test-suite/daycounters.cpp
test-suite/daycounters.hpp

Fix 30/360 (German) day counter.

---

ql/math/optimization/differentialevolution.cpp
ql/math/optimization/differentialevolution.hpp

- allow to explicitly specify bounds
- allow to specify an initial population explicitly
- evaluate cost function via problem, reset problem initially
- handle non-finite intermediate results

some updates for the DE optimiser

---

ql/models/shortrate/calibrationhelpers/caphelper.cpp
ql/models/shortrate/calibrationhelpers/caphelper.hpp

Enable use of normal volatility in cap helpers.

---

ql/pricingengines/swap/discretizedswap.cpp
ql/pricingengines/swap/discretizedswap.hpp

use Setting includeTodaysCashFlows() In DiscretizedSwap

---

ql/instruments/overnightindexedswap.hpp

Add missing inspector to OvernightIndexedSwap 

---

ql/termstructures/yield/fittedbonddiscountcurve.cpp
ql/termstructures/yield/fittedbonddiscountcurve.hpp
ql/termstructures/yield/nonlinearfittingmethods.cpp
ql/termstructures/yield/nonlinearfittingmethods.hpp
test-suite/fittedbonddiscountcurve.cpp
test-suite/fittedbonddiscountcurve.hpp

the motivation for this is described in the added unit test

introduce flat extrapolation option for fitted bond curves

---

ql/time/calendars/mexico.cpp
ql/time/calendars/mexico.hpp

Add All Souls Day bank holiday to Mexican calendar

---

ql/experimental/math/isotropicrandomwalk.hpp
ql/methods/montecarlo/multipathgenerator.hpp
ql/termstructures/credit/defaultprobabilityhelpers.cpp
ql/termstructures/volatility/swaption/swaptionvoldiscrete.cpp
ql/termstructures/volatility/swaption/swaptionvoldiscrete.hpp

A couple of functions were taking large objects by value.
Some constructors are (or were) calling virtual functions.

Avoid a few LGTM warnings.

---

test-suite/Makefile.am

Avoid functions specific to GNU Make.

---

ql/time/calendars/india.cpp
ql/time/calendars/russia.cpp

this is on behalf of my colleague Alexey Indiryakov

Update Indian and Russian calendars

---

ql/pricingengines/vanilla/fdblackscholesvanillaengine.cpp
test-suite/dividendoption.cpp

disable escrowed dividend model for path dependent options

---

ql/time/calendars/turkey.cpp
ql/time/calendars/turkey.hpp

Closes #860
Add a missing National Holiday of Turkey

Add a missing National Holiday of Turkey (Democracy and National Unity Day)

---

Examples/BasketLosses/BasketLosses.cpp
Examples/BermudanSwaption/BermudanSwaption.cpp
Examples/Bonds/Bonds.cpp
Examples/CDS/CDS.cpp
Examples/CVAIRS/CVAIRS.cpp
Examples/CallableBonds/CallableBonds.cpp
Examples/ConvertibleBonds/ConvertibleBonds.cpp
Examples/DiscreteHedging/DiscreteHedging.cpp
Examples/EquityOption/EquityOption.cpp
Examples/FRA/FRA.cpp
Examples/FittedBondCurve/FittedBondCurve.cpp
Examples/Gaussian1dModels/Gaussian1dModels.cpp
Examples/GlobalOptimizer/GlobalOptimizer.cpp
Examples/LatentModel/LatentModel.cpp
Examples/MarketModels/MarketModels.cpp
Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
Examples/MultidimIntegral/MultidimIntegral.cpp
Examples/Replication/Replication.cpp
Examples/Repo/Repo.cpp
ql/cashflows/couponpricer.hpp
ql/patterns/singleton.hpp
test-suite/quantlibbenchmark.cpp
test-suite/quantlibtestsuite.cpp

This makes it possible to redefine it.

Use custom typedef for session id.

---

ql/time/calendars/hongkong.cpp

Add missing HK public holiday(2015-09-03)

---

ql/pricingengines/blackformula.cpp
ql/pricingengines/blackformula.hpp
ql/pricingengines/swaption/blackswaptionengine.hpp
test-suite/blackformula.cpp
test-suite/blackformula.hpp
test-suite/swaption.cpp
test-suite/swaption.hpp

This pull request adds the following functionality:
* Delta for Black76 model
* Delta for Bachelier model
* Delta (as additional result) in Black swaption engine. 
Looking forward to your feedback.

Swaption delta

---

ql/instruments/makevanillaswap.cpp
ql/termstructures/yield/ratehelpers.cpp
test-suite/piecewiseyieldcurve.cpp
test-suite/piecewiseyieldcurve.hpp

use index.valueDate interface for vanillaswap spot date estimation

---

tools/check_header.py

This makes check_header.py with both python 2/3

make the check_header.py work in both python 2/3

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/CMakeLists.txt
ql/pricingengines/asian/Makefile.am
ql/pricingengines/asian/all.hpp
ql/pricingengines/asian/mc_discr_arith_av_price_heston.cpp
ql/pricingengines/asian/mc_discr_arith_av_price_heston.hpp
test-suite/asianoptions.cpp
test-suite/asianoptions.hpp

MC engine for arithmetic asians, and a test based on a result in the literature.

Adding an MC engine for Arithmetic Asians in Heston model

---

ql/experimental/futures/overnightindexfutureratehelper.cpp
test-suite/sofrfutures.cpp

As mentioned #913 , there is a issue that monthly SOFR future has wrong convention for its reference period and this commit is aim to fix it.

fix monthly SOFR future convention

---

ql/time/calendars/thailand.cpp

Fixes #944.
Thanks to phil-zxx.

Fix holiday in Thailand calendar and update

---

ql/patterns/observable.cpp
ql/patterns/observable.hpp

Observer dtor does not need to disconnect from signal

---

ql/experimental/inflation/kinterpolatedyoyoptionletvolatilitysurface.hpp
ql/termstructures/volatility/inflation/cpivolatilitystructure.cpp
ql/termstructures/volatility/inflation/cpivolatilitystructure.hpp
ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.cpp
ql/termstructures/volatility/inflation/yoyinflationoptionletvolatilitystructure.hpp

- add vol type and displacement to yoy vol surfaces
- fix extrapolation in k-interpolated yoy vol surface
- add volatility methods taking a time parameter to cpi and yoy vol structures
- add quotes based ctor to constant yoy vol surface

several updates to inflation vol structures

---

ql/math/optimization/simplex.cpp

I hope it's better now. ;)
Minor changes from C to C++ added.
Of course, it can be refactored altogether.
But unit tests for simplex.cpp first. If I may.

Exception and minor C-to-C++ transition.

---

QuantLib.vcxproj.filters

rearranged QuantLib.vcxproj.filters

---

ql/experimental/exoticoptions/analyticpartialtimebarrieroptionengine.cpp

Correct bug in AnalyticPartialTimeBarrierOptionEngine.

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/CMakeLists.txt
ql/methods/finitedifferences/utilities/Makefile.am
ql/methods/finitedifferences/utilities/all.hpp
ql/methods/finitedifferences/utilities/fdmshoutloginnervaluecalculator.cpp
ql/methods/finitedifferences/utilities/fdmshoutloginnervaluecalculator.hpp
ql/pricingengines/vanilla/Makefile.am
ql/pricingengines/vanilla/all.hpp
ql/pricingengines/vanilla/fdblackscholesshoutengine.cpp
ql/pricingengines/vanilla/fdblackscholesshoutengine.hpp
ql/pricingengines/vanilla/fdshoutengine.hpp
test-suite/americanoption.cpp
test-suite/americanoption.hpp
test-suite/quantlibbenchmark.cpp

Added shout option engine in new-style FD framework 

---

Examples/BermudanSwaption/BermudanSwaption.vcxproj
Examples/BermudanSwaption/BermudanSwaption.vcxproj.filters
Examples/Bonds/Bonds.vcxproj
Examples/Bonds/Bonds.vcxproj.filters
Examples/CDS/CDS.vcxproj
Examples/CDS/CDS.vcxproj.filters
Examples/CallableBonds/CallableBonds.vcxproj
Examples/CallableBonds/CallableBonds.vcxproj.filters
Examples/ConvertibleBonds/ConvertibleBonds.vcxproj
Examples/ConvertibleBonds/ConvertibleBonds.vcxproj.filters
Examples/DiscreteHedging/DiscreteHedging.vcxproj
Examples/DiscreteHedging/DiscreteHedging.vcxproj.filters
Examples/EquityOption/EquityOption.vcxproj
Examples/EquityOption/EquityOption.vcxproj.filters
Examples/FRA/FRA.vcxproj
Examples/FRA/FRA.vcxproj.filters
Examples/FittedBondCurve/FittedBondCurve.vcxproj
Examples/FittedBondCurve/FittedBondCurve.vcxproj.filters
Examples/Gaussian1dModels/Gaussian1dModels.vcxproj
Examples/Gaussian1dModels/Gaussian1dModels.vcxproj.filters
Examples/GlobalOptimizer/GlobalOptimizer.vcxproj
Examples/GlobalOptimizer/GlobalOptimizer.vcxproj.filters
Examples/MarketModels/MarketModels.vcxproj
Examples/MarketModels/MarketModels.vcxproj.filters
Examples/Replication/Replication.vcxproj
Examples/Replication/Replication.vcxproj.filters
Examples/Repo/Repo.vcxproj
Examples/Repo/Repo.vcxproj.filters

This is just a removal of the deleted ReadMe.txt files from the Visual Studio projects and filters.

Remove the deleted readme files from the example VS projects.

---

ql/methods/finitedifferences/fdtypedefs.hpp
ql/qldefines.hpp
ql/termstructures/inflationtermstructure.cpp
ql/termstructures/yield/discountcurve.hpp
ql/termstructures/yield/forwardcurve.hpp
ql/termstructures/yield/forwardstructure.cpp
ql/termstructures/yield/interpolatedsimplezerocurve.hpp
ql/termstructures/yield/zerocurve.hpp
ql/termstructures/yield/zeroyieldstructure.cpp

Perhaps this is of general interest?!

Added macro to disable and enable deprecated warnings temporarily

---

Examples/BasketLosses/BasketLosses.cpp
Examples/BermudanSwaption/BermudanSwaption.cpp
Examples/Bonds/Bonds.cpp
Examples/CDS/CDS.cpp
Examples/CVAIRS/CVAIRS.cpp
Examples/CallableBonds/CallableBonds.cpp
Examples/ConvertibleBonds/ConvertibleBonds.cpp
Examples/DiscreteHedging/DiscreteHedging.cpp
Examples/EquityOption/EquityOption.cpp
Examples/FRA/FRA.cpp
Examples/FittedBondCurve/FittedBondCurve.cpp
Examples/Gaussian1dModels/Gaussian1dModels.cpp
Examples/GlobalOptimizer/GlobalOptimizer.cpp
Examples/LatentModel/LatentModel.cpp
Examples/MarketModels/MarketModels.cpp
Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp
Examples/MultidimIntegral/MultidimIntegral.cpp
Examples/Replication/Replication.cpp
Examples/Repo/Repo.cpp
ql/patterns/singleton.hpp
test-suite/quantlibbenchmark.cpp
test-suite/quantlibtestsuite.cpp

Now we only require that it's default-constructible.

Don't assume ThreadKey is convertible from int.

---

ql/time/daycounters/actualactual.cpp
test-suite/daycounters.cpp
test-suite/daycounters.hpp

Fix actual/actual (ISMA) day counter calculation for long/short final periods

---

ql/patterns/observable.cpp

Comparison between `boost::bind` objects doesn't work in gcc when using C++20 mode.  This change uses a custom equality-comparable function object.

Fix thread-safe observable in C++20 mode

---

QuantLib.natvis

Fixes https://github.com/lballabio/QuantLib/pull/1028#issuecomment-779117229 
cc @ralfkonrad

Add Period, InterestRate and InterestRateIndex types to the .natvis 

---

ql/time/calendars/unitedkingdom.cpp

Thanks to Ioannis Rigopoulos for the heads-up.

Add special UK bank holiday for 2022 Platinum Jubilee

---

.github/workflows/cmake.yml
CMakeLists.txt

Fixes #1090 in the cmake build

Set c++11 in CMakeLists.txt when on Mac OS

---

ql/math/matrixutilities/sparsematrix.hpp
test-suite/hestonmodel.cpp
test-suite/hestonmodel.hpp
test-suite/matrices.cpp
test-suite/matrices.hpp

and test for spare matrix memory layout

added test for local volatility pricing from Heston model. 

---

ql/pricingengines/vanilla/analyticptdhestonengine.cpp

I would like to submit the pull request to fix issue [1128](https://github.com/lballabio/QuantLib/issues/1128)

Added implementation of numberOfEvaluations

---

ql/time/calendars/canada.cpp
ql/time/calendars/canada.hpp

Add new Canadian holiday

---

ql/experimental/callablebonds/discretizedcallablefixedratebond.cpp
ql/experimental/callablebonds/discretizedcallablefixedratebond.hpp
ql/experimental/callablebonds/treecallablebondengine.cpp
test-suite/callablebonds.cpp
test-suite/callablebonds.hpp

Avoid callable-bond mispricing when a call date is close to a coupon date 

---

ql/math/integrals/kronrodintegral.cpp

Implementation of GaussKronrodNonAdaptive::setRelativeAccuracy … by Mickael Anas LAAOUINI) .

Implementation of `GaussKronrodNonAdaptive::setRelativeAccuracy`

---

ql/cashflows/cashflows.cpp
ql/cashflows/conundrumpricer.cpp
ql/experimental/credit/blackcdsoptionengine.cpp
ql/experimental/swaptions/haganirregularswaptionengine.cpp
ql/math/interpolations/multicubicspline.hpp
ql/pricingengines/blackformula.cpp
ql/pricingengines/capfloor/bacheliercapfloorengine.cpp
ql/pricingengines/capfloor/blackcapfloorengine.cpp
ql/termstructures/volatility/swaption/swaptionvolcube1.hpp
test-suite/amortizingbond.cpp
test-suite/zerocouponswap.cpp

Avoid syntax deprecated in C++20

---

ql/time/calendar.cpp
test-suite/calendars.cpp

Allow same-day for holidayList and businessDayList

---

ql/cashflows/couponpricer.cpp
ql/cashflows/couponpricer.hpp
test-suite/cashflows.cpp
test-suite/cashflows.hpp

Do not require a forecast curve to calculate past IBOR coupon amounts

---

Examples/MulticurveBootstrapping/MulticurveBootstrapping.cpp

- Removed single-curve case;
- More concise setup code

Simplify multi-curve example

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/CMakeLists.txt
ql/experimental/barrieroption/Makefile.am
ql/experimental/barrieroption/all.hpp
ql/experimental/barrieroption/suowangdoublebarrierengine.cpp
ql/experimental/barrieroption/suowangdoublebarrierengine.hpp
test-suite/doublebarrieroption.cpp

Rename `WulinYongDoubleBarrierEngine` to `SuoWangDoubleBarrierEngine`

---

ql/experimental/credit/basket.cpp

Regarding issue [#1253](https://github.com/lballabio/QuantLib/issues/1253) add the missing check of endDate.

Add check on endDate

---

ql/experimental/mcbasket/longstaffschwartzmultipathpricer.cpp
ql/experimental/mcbasket/longstaffschwartzmultipathpricer.hpp
ql/experimental/mcbasket/mcamericanpathengine.hpp
ql/methods/montecarlo/lsmbasissystem.cpp
ql/methods/montecarlo/lsmbasissystem.hpp
ql/pricingengines/basket/mcamericanbasketengine.cpp
ql/pricingengines/basket/mcamericanbasketengine.hpp
ql/pricingengines/vanilla/mcamericanengine.cpp
ql/pricingengines/vanilla/mcamericanengine.hpp
test-suite/mclongstaffschwartzengine.cpp

Typo correction in MakeMCAmericanEngine

---

.gitignore
LICENSE.TXT
ql/experimental/callablebonds/callablebond.hpp
ql/experimental/callablebonds/discretizedcallablefixedratebond.cpp
test-suite/callablebonds.cpp
test-suite/callablebonds.hpp

Avoid unexpected jumps in callable bond OAS

---

ql/models/shortrate/calibrationhelpers/swaptionhelper.cpp

this is consistent with MakeVanillaSwap

fix start date of underlying swap in swaption calibration helper

---

ql/experimental/catbonds/catrisk.cpp
ql/experimental/math/latentmodel.hpp
ql/experimental/mcbasket/mcpathbasketengine.hpp
ql/experimental/processes/extendedblackscholesprocess.cpp
ql/experimental/processes/hestonslvprocess.cpp
ql/math/integrals/gausslobattointegral.cpp
ql/math/matrixutilities/svd.cpp
ql/processes/blackscholesprocess.cpp
ql/processes/gjrgarchprocess.cpp
ql/processes/hestonprocess.cpp
test-suite/hestonmodel.cpp

This adds a few more Real and cast-related changes to consistently use Real throughout QuantLib. These changes were missing in the previous PR #1400

Further changes for consistent Real usage

---

configure.ac

Remove QL_PATCH_DARWIN

---

ql/math/modifiedbessel.cpp
test-suite/functions.cpp

fixed modified Bessel function for nu=x=y=0 case.

---

.clang-format

Source: https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html

Update clang-format Standard to c++14

---

ql/time/calendars/unitedkingdom.cpp
ql/time/calendars/unitedkingdom.hpp

Hi,
With the bank holiday announced it would be good to include this date in the list of holidays.
Best,
Tomass

Add the Queen's Funeral to the list of UK bank holidays

---

ql/patterns/singleton.hpp

As discussed in #1504, here is the workaround for a GCC bug.

Add workaround for GCC bug

---

Examples/EquityOption/EquityOption.cpp
ql/pricingengines/vanilla/qdfpamericanengine.cpp
test-suite/americanoption.cpp
test-suite/americanoption.hpp

added edge case detection needed by some integration method and fixed this [issue](https://github.com/lballabio/QuantLib/pull/1495#issuecomment-1299423277).

fixed QD+ fixed point engine for high precision Gauss-Lobatto integration

---

ql/models/volatility/garch.cpp

This can be expressed more idiomatically using a range-bound for loop.

Remove dependency on BOOST_FOREACH

---

ql/cashflows/cashflows.cpp
ql/cashflows/cashflows.hpp
ql/experimental/termstructures/crosscurrencyratehelpers.cpp
ql/pricingengines/swap/discountingswapengine.cpp

Avoid out parameters in `npvbps` signature

---

ql/time/calendars/australia.cpp
ql/time/calendars/australia.hpp

Add Australian calendar for ASX

---

ql/time/calendars/singapore.cpp

No info before 2019 on https://www.sgx.com/derivatives/trading

Singapore calendar update

---

ql/termstructures/yield/overnightindexfutureratehelper.cpp

Extend available maturities for SOFR quarterly contract

---

.github/workflows/cmake.yml
CMakePresets.json

Add install step to CMake CI jobs

---

cmake/GenerateHeaders.cmake

After having a second thought about #1654 this is perhaps not the most elegant solution but should solve #1651.

Fixes issues #1651

---

ql/time/calendars/hongkong.cpp
ql/time/calendars/india.cpp
ql/time/calendars/india.hpp
ql/time/calendars/southafrica.cpp
ql/time/calendars/southkorea.cpp

Hi,
Extending and correcting holidays for the listed calendars. We still see differences for the first three of them, but this should bring the results closer to the expected.
Best,
Fredrik

Corrections to HKEx, NSE, KRX, and South Africa calendars

---

ql/experimental/asian/analytic_cont_geom_av_price_heston.hpp
ql/experimental/asian/analytic_discr_geom_av_price_heston.hpp
ql/experimental/forward/analytichestonforwardeuropeanengine.cpp
ql/experimental/variancegamma/fftvanillaengine.hpp
ql/experimental/variancegamma/fftvariancegammaengine.cpp
ql/experimental/variancegamma/fftvariancegammaengine.hpp
ql/math/array.hpp
ql/math/generallinearleastsquares.hpp
ql/math/linearleastsquaresregression.hpp
ql/math/ode/adaptiverungekutta.hpp
ql/pricingengines/barrier/binomialbarrierengine.hpp

Also had to include the `<complex>` header in various places, which must have been pulled in through boost previously.

Use type traits from standard library

---

test-suite/paralleltestrunner.hpp

Allow filtering tests using Boost.Test's standard `--run_test=<filter>` option. This works out-of-the-box, except we should not pass this option to the subprocesses.
Also, use Boost.Process's `system()` with a vector of strings instead of `std::system()` with a string to avoid shell escaping issues: arguments with spaces becoming multiple arguments and globs (e.g. *) being expanded by the shell.

Support filtering tests in parallel unit test runner

---

QuantLib.vcxproj
QuantLib.vcxproj.filters
ql/CMakeLists.txt
ql/indexes/ibor/Makefile.am
ql/indexes/ibor/all.hpp
ql/indexes/ibor/destr.hpp
ql/indexes/ibor/swestr.hpp

QL-Swig PR coming up for these as well.
Thanks!

Add DESTR, SWESTR OIS indices

---

ql/experimental/barrieroption/vannavolgabarrierengine.cpp

Hi!
We benefit from getting as many results as possible so I hope these are okay to add. I changed all forward calculations to an intermediary variable to make it more readable.
Fredrik

Add additional results for VV barrier engine

---

test-suite/rangeaccrual.cpp

Initialise a vector of bool in a way which does not make GCC 13.1 irrationally upset

---

ql/models/shortrate/onefactormodels/markovfunctional.cpp

fix the algorithm to add instruments to the calibration set of the Markov model so that on each payment date the numeraire is known

fix calibration point algorithm

---

ql/termstructures/iterativebootstrap.hpp

Pass through max evaluations to the solver

---

ql/time/calendars/southkorea.cpp
test-suite/calendars.cpp

Hi,
This was recently announced: https://www.koreaherald.com/view.php?ud=20230831000303

Add special holiday 2 Oct 2023 for Korea

---

News.md
ql/cashflows/digitalcmscoupon.cpp
ql/cashflows/digitalcmscoupon.hpp
ql/cashflows/digitalcoupon.cpp
ql/cashflows/digitalcoupon.hpp
ql/cashflows/digitaliborcoupon.cpp
ql/cashflows/digitaliborcoupon.hpp
ql/experimental/coupons/digitalcmsspreadcoupon.cpp
ql/experimental/coupons/digitalcmsspreadcoupon.hpp
test-suite/digitalcoupon.cpp

In some configurations, it doesn't seem to like fancy default arguments.

Avoid internal compiler error on VC++17

---

CMakeLists.txt

See https://github.com/lballabio/QuantLib/pull/1807#discussion_r1394119213 for context

cmake: Roll back cmake version change

---

test-suite/timeseries.cpp

Test coverage of `TimeSeries` is completed as well as splitting large tests up into smaller ones.

TimeSeries: Complete test coverage

---

test-suite/period.cpp

The test coverage for `Period` is completed .

Period: Complete unit tests

---

ql/indexes/ibor/thbfix.hpp
ql/termstructures/yield/overnightindexfutureratehelper.cpp
ql/termstructures/yield/ratehelpers.cpp
ql/termstructures/yield/ratehelpers.hpp
test-suite/overnightindexedswap.cpp

Hi,
Minor change to make the imports more relevant.

Move calendar imports where they are used

---

ql/instruments/makeois.cpp
ql/instruments/makeois.hpp

Allow setting conventions and per-leg EOM in MakeOIS

---

ql/pricingengines/bond/bondfunctions.hpp

Avoid ambiguous calls to BondFunctions::atmRate

---

ql/instruments/overnightindexedswap.cpp
ql/instruments/vanillaswap.cpp
test-suite/overnightindexedswap.cpp
test-suite/swap.cpp

Register floating cash flows with OIS; add tests

---

ql/time/schedule.cpp

Add a missing include which is required in some builds

---

ql/math/integrals/expsinhintegral.hpp

See https://github.com/lballabio/QuantLib-SWIG/issues/649.

Add missing method to fallback class implementation

---

ql/termstructures/yield/fittedbonddiscountcurve.cpp
ql/termstructures/yield/fittedbonddiscountcurve.hpp
test-suite/fittedbonddiscountcurve.cpp

Add possibility to reset guess in fitted bond curves

---

ql/config.hpp.cfg

Add values for configuration #defines when using cmake

---

ql/experimental/callablebonds/callablebond.cpp
test-suite/callablebonds.cpp

OAS using nominal instead of percent price

---

Examples/Bonds/Bonds.cpp

- Don't use deposits to build a bond curve
- Avoid adding an artificial forward start to swaps
- Consistent calendars and indexes

Rework bond example

---

ql/currencies/africa.cpp
ql/currencies/america.cpp
ql/currencies/asia.cpp
ql/currencies/crypto.cpp
ql/currencies/europe.cpp
ql/currencies/oceania.cpp
ql/currency.hpp

Deprecate the correct `Currency::Data` constructor

---

ql/instruments/overnightindexfuture.cpp
ql/termstructures/yield/overnightindexfutureratehelper.cpp
test-suite/sofrfutures.cpp

Fixes #1999.
Supersedes #1996.

Allow for holidays at start or end of SOFR future periods

---

ql/math/optimization/simplex.cpp

These old versions of GCC are no longer supported.

Remove workaround for GCC 3.4 and below

---

ql/experimental/risk/creditriskplus.cpp
ql/experimental/risk/creditriskplus.hpp
ql/experimental/risk/sensitivityanalysis.cpp
ql/experimental/risk/sensitivityanalysis.hpp
test-suite/creditriskplus.cpp

Somewhat out of scope for the library.

Deprecate some experimental code

---

ql/termstructures/yield/ratehelpers.cpp
test-suite/piecewiseyieldcurve.cpp
test-suite/schedule.cpp

Allow creating a swap helper with frequency "Once"

---

ql/experimental/termstructures/basisswapratehelpers.hpp
ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/oisratehelper.hpp

Also, IborIborBasisSwapRateHelper and OvernightIborBasisSwapRateHelper.
Also, set the correct maturityDate.

Expose swap() on DatedOISRateHelper

---

ql/instruments/makevanillaswap.cpp
ql/termstructures/yield/ratehelpers.cpp
ql/termstructures/yield/ratehelpers.hpp
test-suite/piecewiseyieldcurve.cpp

Also known as "DatedSwapRateHelper". Similar to the new constructor for OISRateHelper.

Add SwapRateHelper constructor with fixed dates

---

ql/time/calendars/newzealand.cpp
ql/time/calendars/newzealand.hpp
test-suite/calendars.cpp

Add Wellington and Auckland variants for New Zealand calendar

---

ql/time/schedule.cpp
test-suite/schedule.cpp

Honor passed convention in case of end-of-month adjustment

---

ql/indexes/ibor/eurlibor.cpp
ql/indexes/ibor/eurlibor.hpp
ql/indexes/interestrateindex.hpp

* Use JoinHolidays for the fixing calendar
* Use TARGET in fixingDate since it is used in valueDate

Fix EURLibor index

---

ql/pricingengines/asian/choiasianengine.cpp

Discovered on:
- Ubuntu 20.04
- CXX17
using [QuantLib-Risks-Cpp](https://github.com/auto-differentiation/QuantLib-Risks-Cpp) and [XAD](https://github.com/auto-differentiation/xad), latest releases.
Consistency in types is needed for automatic differentiation support.

Fix for AD in choiasianengine.cpp

---

ql/instruments/overnightindexfuture.cpp
ql/termstructures/yield/overnightindexfutureratehelper.cpp

And OvernightIndexFutureRateHelper.

Add missing dependencies to OvernightIndexFuture

---

ql/experimental/callablebonds/blackcallablebondengine.cpp
test-suite/callablebonds.cpp

Fix discounting in callable-bond Black engine

---

ql/time/calendars/thailand.cpp

Added Thailand holidays for 2025 as requested in #2193.

Thailand Holidays 2025

---

ql/time/calendars/hongkong.cpp

Add Hong Kong Exchange 2025 holidays

Add Hong Kong Exchange 2025 holidays

---

ql/time/daycounters/actual365fixed.cpp
test-suite/daycounters.cpp

Add check for null frequency in Act/365 Canadian

---

ql/termstructures/yield/piecewiseyieldcurve.hpp

This class was deleted back in version 1.32

Remove the remains of MultiCurveSensitivities

---

ql/termstructures/yield/oisratehelper.cpp
ql/termstructures/yield/oisratehelper.hpp
test-suite/overnightindexedswap.cpp

Take fixing dates into account when calculating OIS-helper pillar

---

ql/termstructures/iterativebootstrap.hpp

Also, don't copy data into previousData when not doing convergence loop.

Support pillar dates > latestRelevantDate in IterativeBootstrap

---

ql/experimental/fx/blackdeltacalculator.cpp
ql/experimental/fx/blackdeltacalculator.hpp

Improved `BlackDeltaCalculator` doc strings, since from #2296 has emerged confusion in the constructor params.

Better docs string BlackDeltaCalculator
